<form method="post" action="<?php echo $this->seoUrl("/employee/contacts")?>">
    <input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" alt="Search" onfocus="if(this.value=='Search...') this.value='';" onblur="if(this.value=='') this.value='Search...';"/>
    <input type="submit" value="Search" name="submit" class="button"/>
</form>
<?php if (count($this->paginator)): ?>


<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>


<table>
    <thead>
        <?php if($this->paginator->count()>1):?>
        
            <tr>
                <td colspan="6">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        
        <?php endif?>
        <tr>
            <th>S.No.</th>
            <th>Name</th>
            <th>Email</th>
            <th>Extension No.</th>
            <th>Skype Id</th>
            <th>Contact No.</th>
            <th>Department</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $item): ?>
        <?php $sno++?>
        <tr>
            <td><?php echo $sno?></td>
            <td><?php echo $item->first_name." ".$item->last_name; ?></td>
            <td><?php echo $item->email; ?></td>
            <td><?php echo $item->extension_no; ?></td>
            <td><?php echo $item->skype; ?></td>
            <td><?php echo $item->contact_no; ?></td>
            <td><?php echo $item->department_name; ?></td>
        </tr>
        <?php endforeach; ?>
        <?php if($this->paginator->count()>1):?>
        <tfoot>
            <tr>
                <td colspan="6">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        </tfoot>
        <?php endif?>
        
    </tbody>
</table>
<?php endif; ?>