
<?php $date=new Base_Date();?>

<div id="employee-info-content">
<table>
    <tbody>
        <tr ><td colspan="2"><img src="<?php echo $this->user->getThumbnail()?>"></img> </td></tr>
        <tr ><td>Employee Code :</td><td><?php echo $this->user->getEmployeeCode()?></td></tr>
        <tr ><td>Designation : </td><td><?php echo $this->user->getDesignation() ?></td></tr>
        <tr ><td>Department : </td><td><?php echo $this->user->getDepartment() ?></td></tr>
        <tr ><td>Email :</td><td><?php echo $this->user->getEmail()?></td></tr>
        <tr ><td>Username :</td><td><?php echo $this->user->getUsername()?></td></tr>
        <tr ><td>Mobile No. :</td><td><?php echo $this->user->getMobile()?></td></tr>
        <tr ><td>Alt. Contact No. :</td><td><?php echo $this->user->getContactNo()?></td></tr>
        <tr ><td>Extension No. :</td><td><?php echo $this->user->getExtensionNo()?></td></tr>
        <tr ><td>Skype Id :</td><td><?php echo $this->user->getSkype()?></td></tr>
        <tr ><td>Gender :</td><td><?php echo ucfirst( $this->user->getSex())?></td></tr>
    </tbody>
</table>
</div>
