<link rel="stylesheet" type="text/css" href="/style/facebook-tag.css" media="all">
<script src="/js/facebook-tag.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/ext-core.js"></script>
<script type="text/javascript" src="/js/elastic-textarea.js"></script>
<script>$(loadPhotoTagging);</script>
<style type="text/css">
.comment{
	width: 470px;
	height: 22px;
	float:left !important;
	margin:0px 10px 0px 0px;
	border: 3px solid #FFFFFF;
}
</style>
<div class="my-photo" id="center">
<h2>MY PHOTOS</h2>
<h2 class="subheading"><?php //print $this->albumName;?>Photos of You</h2>
<div id="album-photo">
<!-- Start Heading -->
<span class="page_number">Back To <a href="/album/my-photos/">Photos of <?php print $this->userFullName;?></a>  |
<a href="/album/my-photos/photo-download/name/<?php print $this->photo;?>">Download Photo</a></span>
<span class="pages">Photo <?php print $this->photoPosition;?> of <?php print $this->numPhotoAlbum;?> 
	<span> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->prevId;?>);">&lt;</a> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->nextId;?>);">&gt;</a> </span>
</span>
<!-- End Heading -->
<?php 
	$imagePath = Zend_Registry::get('siteurl')."/media/album/custom/".$this->photo;
	$imagePath1 = PUBLIC_PATH."/media/album/custom/".$this->photo;

	$objBaseCommon = new Base_Common();
        $imageSize = $objBaseCommon->getimgwidhtheightstr($imagePath1, 443, 591);
?>
<!-- Start Tagged Images -->

<div class="viewallmyphoto" id="viewallmyphoto">
<a href="javascript:void(0);" class="no-mrgn auto">
<img class="auto" src="/media/album/custom/<?php print $this->photo;?>" <?php print $imageSize;?> id="crop-image" alt="" onclick="slideImage(<?php print $this->nextId;?>);">
</a>
</div>

<!-- End Tagged Images -->
<!-- Start Btns Area -->
<div class="untags">
<span id="fb-like-album-container">
<iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->likeSrcUrl;?>&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
<!--
<?php //if($this->numVote == 0){?>
<a href="javascript:void(0);" id="like-photo">
<img src="/images/fb.jpg" alt="" width="51" height="23" class="f-left">
</a>
<?php //}else{?>
<a href="javascript:void(0);" id="unlike-photo">
<img src="/images/fb-unlike.jpg" alt="" class="f-left">
</a>
<?php //}?>
-->
</span>


<a href="javascript: reportAbuse(<?php print $this->photoId;?>, 'photo');" class="button">REPORT</a>
<a id="<?php print $this->counter; ?>" href="javascript:void(0);" onmouseout="hideTag(<?php print $this->counter; ?>)" onmouseover="showTag(<?php print $this->counter; ?>)" onclick="untagMe(<?php print $this->counter; ?>,<?php print $this->nextId;?>);" class="button">UN-TAG IMAGE</a>

<div class="description"><?php print $this->caption;?></div>
</div>
<!-- End Btns Area -->
</div>


<!-- Start Comment Area -->
<div class="comment-area">
<ul id="album-location-tag-container">
<span id="loading-wall"><img src="<?php echo $this->cdnUri()?>/images/loading.gif" alt=""/></span>
</ul>
<ul id="album-comment-container">
<span id="loading-wall"><img src="<?php echo $this->cdnUri()?>/images/loading.gif" alt=""/></span>
</ul>
<ul>
<li><span id="errormassage" class="redMsg"></span>
<textarea id="comment" id="comment" class="comment" >Comment...</textarea>
<input name="submit" id="submit-album-comment" type="button" class="button2" value="Comment" />
<input name="submit" id="submit-album-comment-demo" type="button" class="button2" value="Comment" style="display:none;" />
</li>
</ul>
</div>
<!-- End Comment Area -->
</div>


<div style="position:absolute;top:450px;left:360px;z-index:100000;display:none;background:#FFFFFF;border:1px #CCCCCC solid;width:130px;height:17px; padding:4px; text-align:center;" id="photo-loading">
<table cellspacing="0" style="background-color:#FFFFFF;" align="center" valign="middle" cellpadding="0" width="130" border="0">
<td><img src="/images/loading.gif" alt=""></td>
<td align="left">loading...</td>
</table></div>

<input type="hidden" name="photo_id" id="photo_id" value="<?php print $this->photoId;?>" />
<input type="hidden" name="item_id" id="item_id" value="<?php print $this->photoId;?>" />
<input type="hidden" name="item_type" id="item_type" value="photo" />
<input type="hidden" name="item_type1" id="item_type1" value="photo_comment" />
<input type="hidden" name="tag-image-flag" id="tag-image-flag" value="0">

<script>


elasticTextArea("comment");		

function slideImage(photoId)
{
	var photo_id = $("#photo_id").val();
        var tagImageFlag = $("#tag-image-flag").val();
	var requesturl = "/album/my-photos/photo-slide-tagged";

            if(photo_id == photoId)
            {
                window.location="/album/my-photos";
                return false;
            }

	if(tagImageFlag == 0)
	{
		$("#photo-loading").show();
		
		$.post(requesturl, {photoId:photoId },
				   function(html){
                                       
                                                $("#photo_id").val(photoId);
                                                $("#item_id").val(photoId);
                                                $("#album-photo").html(html);
                                                $("#photo-loading").hide();
                                                loadImageByComment(photoId);
                                                loadLocationTag(photoId);
                                          
				});	
	}
}

$(document).ready(function(){
	$("a#like-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/like-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#unlike-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/unlike-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	var photo_id	=	$("#photo_id").val();
	var item_type	=	$("#item_type").val();
	var item_type1	=	$("#item_type1").val();
	var requesturl	=	"/album/my-photos/load-album-comment";
	
		$.post(requesturl, {album_id:photo_id,item_type:item_type1,item_type1:item_type1 },
				   function(html){
					$("#album-comment-container").html(html);		
						
				});	
	
});

$(document).ready(function(){
	var photo_id	=	$("#photo_id").val();
	
	var requesturl	=	"/album/my-photos/load-album-location-tag";
	
		$.post(requesturl, {photo_id:photo_id },
				   function(html){
					$("#album-location-tag-container").html(html);						
				});	
});

function loadLocationTag(photoId)
{
	var requesturl	=	"/album/my-photos/load-album-location-tag";
	
		$.post(requesturl, {photo_id:photoId },
				   function(html){
					$("#album-location-tag-container").html(html);						
				});	
}

function loadImageByComment(photo_id)
{
	var item_type	=	$("#item_type").val();
	var item_type1	=	$("#item_type1").val();
	var requesturl	=	"/album/my-photos/load-album-comment";

	$("#album-comment-container").html("<span id='loading-wall'><img src='/images/loading.gif' alt=''/></span>");
	
	$.post(requesturl, {album_id:photo_id,item_type:item_type,item_type1:item_type1 },
			   function(html){
				$("#album-comment-container").html("");
				$("#album-comment-container").html(html);	
										
			});	
}

$(document).ready(function(){
	$("input#submit-album-comment").click(function(){
		var comment		=	$("#comment").val();
		var item_id		=	$("#item_id").val();
		var item_type	=	$("#item_type").val();
		var item_type1	=	$("#item_type1").val();
		var requesturl	=	"/album/my-photos/album-photo-comment";
		if(comment == "" || comment == "Comment..." )
		{
			$("#errormassage").html("Please enter your comment.");
                        return false;
		}else{
                                $("input#submit-album-comment-demo").show();
                                $("input#submit-album-comment").hide();
				$.post(requesturl, {item_id:item_id,comment:comment,item_type:item_type1 },
						   function(html){					
							$("#album-comment-container").append(html).hide().slideDown("slow");
							$("#comment").val('Comment...');
							$("#comment").attr('style','');
                                                        $("#errormassage").html("");
                                                        $("input#submit-album-comment-demo").hide();
                                                        $("input#submit-album-comment").show();
						});	
		}
	});
	
});

$('textarea#comment').focus(function() {
    var textVal = $(this).val();
   if(textVal=='Comment...')
       {
            $(this).val('');
       }
});

$('textarea#comment').focusout(function() {
    var textVal = $(this).val();
   if(textVal=='')
       {
            $(this).val('Comment...');
       }
});



</script>


