<?php $this->mapLib();?>

<script type="text/javascript">

//* Global variable declaration
var geocoder = new google.maps.Geocoder();
var marker=null;
var map =null;
var infoWindow = new google.maps.InfoWindow();
function buildMap(latLng)
{
	 map = new google.maps.Map(document.getElementById('map_canvas'), {
	zoom: 8,
	center: latLng,
	mapTypeId: google.maps.MapTypeId.ROADMAP
	});
	marker = new google.maps.Marker({
	position: latLng,
	title: "Member's current location",
	map: map,
	draggable: false
});

//var content="<div><img src='<?php echo $this->userThumb;?>' /> <?php echo $this->fullName?></div>";
var content="<div><img src='/image?src=<?php echo $this->userThumb;?>&size=journal' /> <?php echo $this->fullName?></div>";
smartInfo(content, marker,'mouseover');
}

function smartInfo(content, marker, eventName)
{
google.maps.event.addListener(map, 'click', function(){infoWindow.close();});
google.maps.event.addListener(marker, eventName, function(e) {

	infoWindow.close();
infoWindow.setContent(content);
infoWindow.open(map, marker);

});

google.maps.event.addListener(map, 'click', function(e) {

infoWindow.close();

});
}
function expandMap()
{
$("#show-map").hide();
$("#close-map").show();
$("#map_canvas").css("height", "500px");
var latLng=marker.getPosition();
buildMap(latLng);
}

function shrinkMap()
{
$("#show-map").show();
$("#close-map").hide();
$("#map_canvas").css("height", "300px");
var latLng=marker.getPosition();
buildMap(latLng);
}


function plotMyJourney()
{
    var params = "userId=<?php echo $this->userId?>";
 $.ajax({
       type: "POST",
       url: "/profile/get-my-journey/",
       data : params,
       dataType: "json",
       success: function(json){
                if(json.error==0)
                {
                    $("#map_canvas").css("height", "500px");
                    var latLng = new google.maps.LatLng(json.coord[0].lat,json.coord[0].lng);
                    buildMap(latLng);
                    
                    var polyOptions = {
                    strokeColor: '#348698',
                    strokeOpacity: 1.0,
                    strokeWeight: 4
                    }
                    var poly = new google.maps.Polyline(polyOptions);
                    poly.setMap(map);
                    var path = poly.getPath();
                    var latiLongi=null;
                    for(i=0;i<json.coord.length;i++)
                    {
                        latiLongi=new google.maps.LatLng(json.coord[i].lat, json.coord[i].lng);
                        path.push(latiLongi);
                        var marker1 = new google.maps.Marker({
                            position: latiLongi,
                            title: 'Destintion #' + path.getLength(),
                            map: map
                          });
                          var content="<div><img src='<?php echo $this->userThumb;?>' /> <?php echo $this->fullName?><br>Destintion # "+ path.getLength()+" </div>";
                            smartInfo(content, marker1,'click');
                    }
                }
                else
                {
                     alert("you don't have any coordinate.");
                }

       },
       error: function (json, status, e){
                alert(json + status)

            }
});

}

function resetMap() {

if (marker != null) {
marker.setMap(null);
marker= null;
}


}

function initialize()
{
	var myLatitude='<?php echo $this->myLatitude?>';
	var myLongitude='<?php echo $this->myLongitude?>';
	if(myLatitude=="" || myLongitude=="")
	{
		alert("Member have no coordinates. Could'nt locate him");
		return false;
	}
	var latLng = new google.maps.LatLng(myLatitude, myLongitude);
	buildMap(latLng);
	
}
</script>
<?php 
				
if($this->view_map)
{
?>
<!-- google map starts -->
<div class="location">
    <a href="javascript:void(0);" onclick="shrinkMap()"class="blue"><?php echo strtoupper($this->fullName);?>'S LOCATION</a>
    <a href="javascript:void(0);" onclick="plotMyJourney()" class="red"><?php echo strtoupper($this->fullName);?>'S GAP JOURNEY</a>
</div>

<div class="where_map">
<div id="map_canvas" style="width: 815px; height: 300px" class="f-left"></div>

<div class="update-location"><img src="<?php echo $this->cdnUri()?>/images/show-btn.jpg" class="f-left" alt="" />
    <span class="red">
        <a id="show-map" href="javascript:void(0);" onclick="expandMap()" class="red"><?php echo $this->puts('SHOW MAP')?></a>
        <a id="close-map" href="javascript:void(0);" onclick="shrinkMap()" class="red" style="display:none"><?php echo $this->puts('CLOSE MAP')?></a>
    </span>

</div>
<?php 
}
else
	{
		echo "<div class='recently-added'>No journal posts available.</div>";
	}
	?>
</div>

<div class="clear"></div>

<script language='javascript' type="text/javascript">
//Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<!-- google map ends -->


<!-- top section ends -->

<!--<div id="journal-center">
<div class="desti-info"><h2>Destination Info</h2><div class="location-bread"><a href="#">New Zealand</a>  &gt;  Queenstown</div></div>
<div class="map2"><img src="<?echo $this->cdnUri()?>/images/map2-sml.jpg" alt="" /></div>
<?php

      foreach($this->destination as $_destination)
      {
        //print_r($_destination);
        echo $_destination->getTitle();



?>
        <p class="intro">
        
              <?php echo $_destination->getIntroduction();

      } ?>
        </p>


        <h2>You Can't Come Here and Not...</h2>
        <h3>Experience 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
        <h3>Experience 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc</p>
        <h3>Experience 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc</p>
        <div class="google-adds">
        <img src="<?echo $this->cdnUri()?>/images/google-adds.jpg" alt="" />
        </div>
        <h2>Hints and Tips</h2>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="content-btns"><a href="#">Read More</a><a href="#">ADD TIP FOR THIS LOCATION</a></div>
        <div class="city-details">
                <div class="city-based-nav">
                        <h2>New Zealand</h2>
                        <ul>
                                <li><a href="#">Before You Go</a></li>
                                <li><a href="#">Transport</a></li>
                                <li><a href="#">Culture &amp; History</a></li>
                                <li><a href="#">Places of Interest</a></li>
                                <li><a href="#">Don't Leave Without</a></li>
                        </ul>
                </div>
                <div class="city-based-nav">
                        <h2>Queenstown</h2>
                        <ul>
                                <li><a href="#">Let's Get Practical</a></li>
                                <li><a href="#">Eat, Sleep, Drink, Be Merry</a></li>
                        </ul>
        </div>

        </div>
        <div class="content-banner">
                <img src="<?echo $this->cdnUri()?>/images/content-banner.jpg" alt="" />
        </div>
</div>-->





