<script language="javascript" type="text/javascript">
function mySubmit()
{
	$("#searchfrm").submit();
}

function showView(blogId)
{    
    var  requestUrl	="/profile/comment/blogId/"+blogId;
    $.ajax({
			type: "POST",
			url: requestUrl,
			success: function(msg){ 
                         var div = document.getElementById('extra_'+blogId);
                         div.innerHTML = msg;
						 $('#extra_'+blogId).slideToggle();	
                   }
          });
}

function showEdit(id)
{ 
	$(".work-another-country_"+id).slideToggle();	
}
function like(item_id,vote)
{
	var params='';
	params+="vote="+vote;
	params+="&item_id="+item_id;
	params+="&item_type=blog";
	$("span#like_"+item_id).hide();
        $("span#loading_"+item_id).show();
	$.ajax({
		   type: "POST",
		   url: "/vote/do-vote/",
		   data: params,
		   dataType: "json",
		   success: function(json){
			if(json.error==1)
			{
				alert(json.msg);
			}
			else if(json.error==2)
			{
				$("span#loading_"+item_id).hide();
				$("#comment-main-"+item_id).show();
				if(vote==1)
				{
					$("span#unlike_"+item_id).show();
					$("span#like_"+item_id).hide();
					$("#you-like-this-"+item_id).show();
					$("#you-like-this-thumb-"+item_id).show();
				}
				else
				{
					$("span#unlike_"+item_id).hide();
					$("span#like_"+item_id).show();
					$("#you-like-this-"+item_id).hide();
					$("#you-like-this-thumb-"+item_id).hide();
				}
				//$("span#total_likes_"+item_id).html(json.total_up);
				//$("span#total_likes_left_"+item_id).html(json.total_up);
				//$("span#total_likes_"+item_id).hide();
				
				//display main DIV and other as per user vote and total likes
				if(vote==1)
				{
					$("div#journal_tag_div_"+item_id).show();
					$("div#journal_tag_div_"+item_id).addClass('like-dislike-img');
					
					//if Tags are available then display seperator
					if($("span#journal_tag_str_"+item_id).html()!=null)
					{
						$("span#journal_tag_sep_"+item_id).show();
					}					
				}
				else
				{
					if(json.total_up==0)
					{
						$("span#journal_tag_sep_"+item_id).hide();
						//if Tags are not available then hide main DIV
						if($("span#journal_tag_str_"+item_id).html()==null)
						{
							$("div#journal_tag_div_"+item_id).hide();
						}
					}
				}	
				
				if(json.total_up>1)
				{
					$("span#total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_plural");?>");
				}
				else if(json.total_up==1)
				{
					$("span#total_likes_"+item_id).show();
					$("span#total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_singular");?>");
				}
				else
				{
					$("span#total_likes_"+item_id).hide();
					$("span#total_likes_"+item_id).html(json.total_up);
				}
              }
		   },
		   error: function (json, status, e){
			   //alert("8resp="+json.response);

			}
	 });
}
</script>
<div id="journal-center">
    <h2> MY JOURNALS BY <?php echo  ucwords($this->userName); ?></h2>
<?php 
if(count($this->data)>0)
{
?>
<div id="blogs_listings" style="border:0px solid #ffcc00;">
<?php
	$date=new Base_Date();
	$date->setSysDateFormat("D jS F Y");
	
	$com_obj = new Application_Model_Comment();
	$vot_obj = new Application_Model_Vote();
	
	foreach($this->data as $row)
	{
		$tagsM=new Application_Model_Tags();
		$tagStr=$tagsM->getBlogTags($row->getId());
		$user=$row->getUserObj();
		$blog_seo_url = $this->seoUrl("/journal/view-post/blog_id/{$row->getId()}");
?>
<div class="user-journal-box"> 
		  <h3><a href="<?php echo $blog_seo_url;?>"><?php echo $row->getTitle();?></a></h3>
		  <div class="post-by">
		  Posted by <strong><span><a href="/<?php echo $user->username;?>"><?php echo $user->first_name.' '.$user->last_name; ?></a></span> </strong>| <span><?php echo $date->getSysDate($row->getAddedon());?></span> | <span><?php echo $com_obj->numComments('blog', $row->getId()) ?> <a href="javascript:void(0)" onclick="showView(<?php echo $row->getId();?>)">Comment</a></span> | 
		  <?php 
		  $likeStyle="";
		  $unlikeStyle="display:none";
					
		  if($this->userId=="")
		  {
		  ?>
          <a href="javascript: loginPopUp('Please login to like');">Like</a>
           <?php
		   }
		   else
		   {
			   $userVote = $vot_obj->getTotalVotes($row->getId(),"blog",1,$this->userId);
			   if($userVote>0)
			   {
					$likeStyle="display:none";
					$unlikeStyle="";
			   }
			?>
				<span style="display: none;" id="loading_<?php echo $row->getId();?>"><img alt="" src="<?php echo $this->cdnUri()?>/images/loading.gif"></span>
				<span style="<?php echo $unlikeStyle?>" id="unlike_<?php echo $row->getId();?>">
				<a href="javascript: like(<?php echo $row->getId();?>, -1);">Unlike</a>
				</span>

				<span style="<?php echo $likeStyle?>"  id="like_<?php echo $row->getId();?>">
				<a href="javascript: like(<?php echo $row->getId();?>, 1);">Like</a>
				</span>
		<?php } //end of else?>
		| <a href="javascript: reportAbuse(<?php echo $row->getId();?>, 'blog');">Report Abuse</a>
		  </div>
		  <div class="user-txt" style="margin-bottom: 5px;"><?php echo substr(strip_tags($row->content),0,300);?>... <a href="<?php echo $blog_seo_url;?>" title="Read more">Read more</a></div>
		  <div id="extra_<?php echo $row->getId();?>" style="display:none;"></div>
		  <?php
			//set total likes text
			$total_likes = 0;
			$total_likes = $vot_obj->getTotalVotes($row->getId(),"blog",1,null);
			$textPrint	=	$this->language("like_singular");
			if($total_likes > 1)
			{
				$textPrint	=	$this->language("like_plural");
			}
			
			//set like-dislike class and style
			$classTag		= "like-dislike";
			$mainDivStyle	= "display: none;";			
			if($tagStr!="" || $total_likes > 0)
			{
				$classTag		= "like-dislike like-dislike-img";
				$mainDivStyle	= "display: block;";
			}
		 ?>
		 <div class="<?php echo $classTag;?>" style="<?php echo $mainDivStyle;?>" id="journal_tag_div_<?php echo $row->getId();?>">
                   
		 <?php if ($total_likes>0){$totalLikeDisplay="";}else{$totalLikeDisplay="display:none";}?>
		 	<span class="like-dislike-l f-left">
            <span id="you-like-this-thumb-<?php echo $row->getId();?>"  style="<?php echo $unlikeStyle?>">
			<img src="<?php echo $this->cdnUri()?>/images/like-icon-2.jpg" alt="Like" class="f-left" />
			<span id="you-like-this-<?php echo $row->getId();?>" style="<?php echo $unlikeStyle?>"><?php echo $this->language("like_you");?></span>
            </span>
            <a href="<?php echo $this->seoUrl('/journal/user-like-this/type/blog/item_id/'.$row->getId());?>" class="like-this-l-link">
			<span id="total_likes_<?php echo $row->getId();?>"  style="<?php echo $totalLikeDisplay?>">
			<?php echo $total_likes.' '.$textPrint;?>
			</span>
			</a>
            </span>
			
			<?php
			//set style for seperator
			$displaySeperator = "display: none;";
			if($tagStr!="" && $total_likes > 0)
			{
				$displaySeperator = "display: block;";
			}			
			?>
			<span class="like-dislike-pipe-seperator" style="<?php echo $displaySeperator;?>" id="journal_tag_sep_<?php echo $row->getId();?>">&nbsp;</span>
			
		  <?php if(isset($tagStr) && $tagStr!=""){?>
		  <span class="like-dislike-r f-left" id="journal_tag_str_<?php echo $row->getId();?>">Tags: <?php echo $tagStr;?></span>
		  <?php }?>
		  
        </div>
		<div class="clear"></div>
	<a href="<?php echo $blog_seo_url;?>" class="orange-sml">View Journal</a>	 
	<?php
		 //$shareLink = Zend_Registry::get('siteurl')."/journal/view-post/blog_id/".$row->getId();
		 $shareLink = Zend_Registry::get('siteurl').$blog_seo_url;
	?>
	<span class="share-id-option">
		<a href="javascript://" id="share-link-dd-<?php echo $row->getId();?>" class="share-link-dd">Share It</a>
		<span id="share-link-dd_menu-<?php echo $row->getId();?>"  class="share-link-dd_menu" >
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt="" /></a>
		<!--<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=<?php //echo $shareLink;?>&amp;title=<?php //echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Delicious"><img src="/images/delicious-icon-sml.png" alt="" /></a>-->
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt="" /></a>
		</span>
	</span>
</div>
<script type="text/javascript">
$(document).ready(function() {

	$("#share-link-dd_menu-<?php echo $row->getId();?>").hide();
	$("#share-link-dd-<?php echo $row->getId();?>").click(function(e) {          
		e.preventDefault();
		$("#share-link-dd_menu-<?php echo $row->getId();?>").toggle("slow");
		$("#share-link-dd-<?php echo $row->getId();?>").toggleClass("menu-open");
	});
	
	$("#share-link-dd_menu-<?php echo $row->getId();?>").mouseup(function() {
		return false;
	});
	
});
</script>
<?php 
}//end of foreach
?>
</div>
<span style="display: none;" id="loading">
    <img alt="" src="<?php echo $this->cdnUri()?>/images/ajax-loader.gif">
</span>	
<div class="view-link">
	<a id="show-more-link" href="javascript: morePosts('<?php echo $this->userName;?>')">VIEW MORE POSTS</a>
</div>
<?php	
}//end of if
else
{
	echo "No journals found.";
}
?>
</div>
<script language="javascript" type="text/javascript">
var page=2;
function morePosts(username)
{
    $("span#loading").show();
    $("#show-more-link").hide();
	
    var params='';
    params += "page="+page+"&mode=ajax&username="+username;
    page = page+1;
    $.ajax({
               type: "POST",
               url: "/profile/view-morejournals/",
               data: params,
               dataType: "html",
               success: function(html)
			   {
					//alert("resp=>"+html);
					$("span#loading").hide();
					$("#show-more-link").show();

					if(html=="nodata")
					{
						$("#show-more-link").hide();
						$("#blogs_listings").append("<span style='color:#EF4733;'>No more journals found.</span>");
					}
					else
					{
						$("#blogs_listings").append(html);
					}
               },
               error: function (json, status, e)
			   {
                     alert(e+json+status);
               }
     });
}
</script>
