<!--<div class="amazon_box_top"><img src="<?php echo $site_url;?>/images/shop-landing/box2_top_l.jpg" width="15" height="15" /></div>
		<div class="amazon_box_mid">
		<script type="text/javascript">
		amazon_ad_tag="gapdae-21"; 
		amazon_ad_width="300"; 
		amazon_ad_height="250"; 
		amazon_color_logo="F74239"; 
		amazon_color_text="348698"; 
		amazon_color_link="F74239"; 
		amazon_ad_logo="hide"; 
		amazon_ad_link_target="new"; 
		amazon_ad_border="hide"; 
		amazon_ad_title="Stuff Your Backpack";</script>
		<script type="text/javascript" src="http://www.assoc-amazon.co.uk/s/asw.js"></script>
		</div>
	<div class="amazon_box_bot"><img src="<?php echo $site_url;?>/images/shop-landing/box2_bot_l.jpg" /></div>-->
<SCRIPT charset="utf-8" type="text/javascript" src="http://ws.amazon.co.uk/widgets/q?ServiceVersion=20070822&MarketPlace=GB&ID=V20070822/GB/gapdae-21/8002/bce2fb5c-5401-4225-80f5-b7bc497b3e7f"> </SCRIPT> <NOSCRIPT><A HREF="http://ws.amazon.co.uk/widgets/q?ServiceVersion=20070822&MarketPlace=GB&ID=V20070822%2FGB%2Fgapdae-21%2F8002%2Fbce2fb5c-5401-4225-80f5-b7bc497b3e7f&Operation=NoScript">Amazon.co.uk Widgets</A></NOSCRIPT>
