	<?php
	$site_url	=	Zend_Registry::get('siteurl');
	?>
	<!-- Start Main Center Area -->
	<div class="main-center">
	  <!-- Bottom Banner -->
	  <div class="ln-hght20" ></div>
	  <div class="ladding_page">
		<div class="left_part"><img src="<?php echo $site_url;?>/images/shop-landing/stuff1.jpg" width="623" height="75" />
		
		<div class="grn-right"></div>
		  <div class="test_part">
			<div class="landing_heading">GAP DAEMON EXPLORER PACK</div>
			We’ve teamed up with top travel tool provider CallUma to bring you these superb Gap Daemon products to give you help if and when you need it on the road </div>
	
	
	<!-- Explorer -->
	<div class="explorer">
	<div class="line"></div>
	<div class="heading">EXPLORER PACK</div>
	<div class="cntnwpr">
	Get ALL 5 services in one handy pack for only £29.95
	<ul>
	What's included:
	<li>Tag 'n' Traq</li>
	<li>Just text help</li>
	<li>PASS THE PHONE</li>
	<li>DOC STORE</li>
	<li>PASSPORT RENEW</li>
	</ul>
	</div>
	<div class="tracker"></div>
	<div class="ftr">
	<a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buy">BUY ALL PRODUCTS</a><span class="f-left" style=" line-height:24px;"> FOR JUST £29.95</span>
	</div>
	</div>
	<!-- Explorer -->
	
	<!-- TAG & TRAQ -->
	<div class="boxwpr">
	<div class="left">
	<div class="heading bgorg"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-org-l.jpg" width="15" height="15" align="left" /></div><span class="org">TAG 'N' TRAQ</span></div>
	<div class="cntnwpr">
	<p>Just one phone call, text message or online report via our Luggage Tracer website and we take it from there</p>
	<p>We liase with baggage handling agents, airlines, airport security, rail and the police, making calls on your behalf to find lost items</p>
	<p>We locate 98% of customers’ bags within 24 hours of them being lost</p>
	<ul>
	What’s included:
	<li>12 months</li>
	<li>Tags (Inc ties and wallet ID card)</li>
	</ul></div>
	</div>
	<div class="right">
	<div class="heading bgorg"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-org-r.jpg" width="15" height="15" align="right" /></div><span>OUT</span><img src="<?php echo $site_url;?>/images/shop-landing/flight-lndg.png" width="27" height="27" class="flight" /></div>
	<img src="<?php echo $site_url;?>/images/shop-landing/bar1.jpg" width="73" height="28" align="left" class="bargrph" />
	<div class="img"></div>
	</div>
	<div class="ftr"><a target="_blank" href="http://www.calluma.com/tagntraq.aspx?AID=GDMWL_LDN1" class="buy">Buy Now</a> <span class="blk">£9.95</span> <a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buyr">or buy the Explorer Pack for £29.95</a>
	<div class="btm"><img width="13" height="13" align="left" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-l.png" class="imgl"><img width="13" height="13" align="right" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-r.png" class="imgr"></div></div>
	</div>
	<!-- TAG & TRAQ -->
	
	<!-- JUST TEXT HELP -->
	<div class="boxwpr"><div class="prpl2"></div>
	<div class="left">
	<div class="heading bgprpl"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-prpl-l.png" width="15" height="15" align="left" /></div><span class="prpl">JUST TEXT HELP</span></div>
	<div class="cntnwpr">
	<div class="lft-p"><strong>In an emergency</strong>
	<p>In emergency situations please call the emergency services directly. If you do not know the emergency telephone number, call us and we can assist you</p></div>
	<div class="rght-p"><strong>Information texts</strong><p>Send a text message to the membership text line and ask for help or information</p></div>
	<br class="clear" />
	<p><strong>What’s included:</strong></p>
	<ul class="just">
	<li>7 Days for £3.95</li>
	<li>30 Days for £5.95</li>
	</ul>
		<ul class="just">
	<li>14 Days for £4.95</li>
	<li>360 Days for £9.95</li>
	</ul>
	</div>
	</div>
	<div class="right">
	<div class="heading bgprpl"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-prpl-r.png" width="15" height="15" align="right" /></div><span>OUT</span><img src="<?php echo $site_url;?>/images/shop-landing/flight-lndg.png" width="27" height="27" class="flight" /></div>
	<img src="<?php echo $site_url;?>/images/shop-landing/bar1.jpg" width="73" height="28" align="left" class="bargrph" />
	<div class="img2"></div>
	</div>
	<div class="ftr"><a target="_blank" href="http://www.calluma.com/justtexthelp.aspx?AID=GDMWL_LDN1" class="buy">CHOOSE YOUR PACKAGE</a> <a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buyr">or buy the Explorer Pack for £29.95</a>
	<div class="btm"><img width="13" height="13" align="left" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-l.png" class="imgl"><img width="13" height="13" align="right" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-r.png" class="imgr"></div></div>
	</div>
	<!-- JUST TEXT HELP -->
	
	<!-- PASS THE PHONE -->
	<div class="boxwpr">
	<div class="grn2abs"></div>
	<div class="left">
	<div class="heading bggrn"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-grn-l.png" width="15" height="15" align="left" /></div><span class="grn">PASS THE PHONE</span></div>
	<div class="cntnwpr">
	<p>When you need help abroad, let us break down the language barrier for you.</p>
	<p>Simply call our 24 hour worldwide helpline, explain the situation to one of our fully trained interpreters,<br />
	then Pass the Phone and we’ll speak the language for you!</p>
	<ul>
	Packages:
	<li>10 mins <strong>£9.90</strong></li>
	<li>20 mins <strong>£19.90</strong></li>
	<li>50 mins  <strong>£47.50</strong></li>
	</ul></div>
	</div>
	<div class="right">
	<div class="heading bggrn"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-grn-r.png" width="15" height="15" align="right" /></div><span>OUT</span><img src="<?php echo $site_url;?>/images/shop-landing/flight-lndg.png" width="27" height="27" class="flight" /></div>
	<img src="<?php echo $site_url;?>/images/shop-landing/bar1.jpg" width="73" height="28" align="left" class="bargrph" />
	<div class="img3"></div>
	</div>
	<div class="ftr"><a target="_blank" href="http://www.calluma.com/phoneinterpretation.aspx?AID=GDMWL_LDN1" class="buy">CHOOSE YOUR PACKAGE</a> <a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buyr">or buy the Explorer Pack for £29.95</a>
	<div class="btm"><img width="13" height="13" align="left" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-l.png" class="imgl"><img width="13" height="13" align="right" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-r.png" class="imgr"></div></div>
	</div>
	<!-- PASS THE PHONE -->
	
	<!-- DOC STORE -->
	<div class="boxwpr">
	<div class="docabs"></div>
	<div class="left">
	<div class="heading bggrn2"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-grn2-l.jpg" width="15" height="15" align="left" /></div><span class="grn2">DOC STORE</span></div>
	<div class="cntnwpr">
	<p><strong>Doc Store works as a virtual safe</strong> Upload copies of your passport, travel documents, <br />
	travellers cheque receipts, tickets, itinerary, driving licence, medical records, insurance policies etc.</p>
	<p>Your docs remain private and secure using our encrypted, password protected site, <br />
	ready for easy recovery should the originals be misplaced, stolen, lost or destroyed</p>
	<ul>
	What’s included:
	<li>12 months</li>
	<li>25 MB Storage</li>
	</ul></div>
	</div>
	<div class="right">
	<div class="heading bggrn2"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-grn2-r.jpg" width="15" height="15" align="right" /></div><span>OUT</span><img src="<?php echo $site_url;?>/images/shop-landing/flight-lndg.png" width="27" height="27" class="flight" /></div>
	<img src="<?php echo $site_url;?>/images/shop-landing/bar1.jpg" width="73" height="28" align="left" class="bargrph" />
	<div class="img4"></div>
	</div>
	<div class="ftr"><a target="_blank" href="#" class="buy">Buy Now</a> <span class="blk">£9.95</span><a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buyr">or buy the Explorer Pack for £29.95</a>
	<div class="btm"><img width="13" height="13" align="left" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-l.png" class="imgl"><img width="13" height="13" align="right" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-r.png" class="imgr"></div></div>
	</div>
	<!-- DOC STORE -->
	
	<!-- PASSPORT RENEW -->
	<div class="boxwpr">
	<div class="left">
	<div class="heading bgred"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-red-l.jpg" width="15" height="15" align="left" /></div><span class="red">PASSPORT RENEW</span></div>
	<div class="cntnwpr">
	<p>To sign up to our free passport renewal reminder service enter your passport details</p>
	<p>We will then send you an email 6 months prior to your expiry date to remind you to renew your passport</p>
	<ul>
	What’s included:
	<li>FREE</li>
	<li>Also included in the Explorer package</li>
	</ul></div>
	</div>
	<div class="right">
	<div class="heading bgred"><div class="top"><img src="<?php echo $site_url;?>/images/shop-landing/top-red-r.jpg" width="15" height="15" align="right" /></div><span>OUT</span><img src="<?php echo $site_url;?>/images/shop-landing/flight-lndg.png" width="27" height="27" class="flight" /></div>
	<img src="<?php echo $site_url;?>/images/shop-landing/bar1.jpg" width="73" height="28" align="left" class="bargrph" />
	<div class="img5"></div>
	</div>
	<div class="ftr"><a target="_blank" href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" class="buyr">or buy the Explorer Pack for £29.95</a>
	<div class="btm"><img width="13" height="13" align="left" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-l.png" class="imgl"><img width="13" height="13" align="right" src="<?php echo $site_url;?>/images/shop-landing/gry-ftr-r.png" class="imgr"></div></div>
	</div>
	<!-- PASSPORT RENEW -->
		</div>
		<div class="right_part">
		  <!--<div class="right_banner"><img src="<?php echo $site_url;?>/images/shop-landing/landing_banner_left1.jpg" width="297" height="249" /></div>-->
		  <div class="right_banner"><?php $banner = new Cms_Model_Banner(); $banner ->showBanner("right", "600", "160");?></div>
		  <div class="right_banner"><a href="http://www.calluma.com/explorer.aspx?AID=GDMWL_LDN1" target="_blank"><img src="<?php echo $site_url;?>/images/shop-landing/callluma.jpg" width="297" height="70" /></a></div>
		  <div class="right_banner"></div>
		</div>
	  </div>
	  <!-- Bottom Banner -->
	</div>
	<!-- End Main Center Area -->
