<?php 
if(count($this->data)>0)
{ 
	$date=new Base_Date();
	$date->setSysDateFormat("D jS F Y");
	
	$com_obj = new Application_Model_Comment();
	$vot_obj = new Application_Model_Vote();
	
	foreach($this->data as $row)
	{
		$tagsM=new Application_Model_Tags();
		$tagStr=$tagsM->getBlogTags($row->getId());
		$user=$row->getUserObj();
?>
<div class="user-journal-box"> 
		  <h3><a href="/journal/view-post/blog_id/<?php echo $row->getId();?>"><?php echo $row->getTitle();?></a></h3>
		  <div class="post-by">
		  Posted by <strong><span><a href="/<?php echo $user->username;?>"><?php echo $user->first_name.' '.$user->last_name; ?></a></span> </strong>| <span><?php echo $date->getSysDate($row->getAddedon());?></span> | <span><?php echo $com_obj->numComments('blog', $row->getId()) ?> <a href="javascript:void(0)" onclick="showView(<?php echo $row->getId();?>)">Comment</a></span> | 
		  <?php
		  $likeStyle="";
		  $unlikeStyle="display:none";
		  if($this->userId=="")
		  {
		  ?>
          <a href="javascript: loginPopUp('Please login to like');">Like</a>
           <?php
		   }
		   else
		   {
			   $userVote = $vot_obj->getTotalVotes($row->getId(),"blog",1,$this->userId);
			   if($userVote>0)
			   {
					$likeStyle="display:none";
					$unlikeStyle="";
			   }
			?>
				<span style="display: none;" id="loading_<?php echo $row->getId();?>"><img alt="" src="<?php echo $this->cdnUri()?>/images/loading.gif"></span>
				<span style="<?php echo $unlikeStyle?>" id="unlike_<?php echo $row->getId();?>">
				<a href="javascript: like('<?php echo $row->getId();?>', -1);">Unlike</a>
				</span>

				<span style="<?php echo $likeStyle?>"  id="like_<?php echo $row->getId();?>">
				<a href="javascript: like('<?php echo $row->getId();?>', 1);">Like</a>
				</span>
		<?php } //end of else?>
		| <a href="javascript: reportAbuse(<?php echo $row->getId();?>, 'blog');">Report Abuse</a>
		  </div>
		  <div class="user-txt"><?php echo substr(strip_tags($row->content),0,300);?>... <a href="/journal/view-post/blog_id/<?php echo $row->getId();?>" title="Read more">Read more</a></div>
		  <div id="extra_<?php echo $row->getId();?>" style="display:none;"></div>
		<?php
			//set total likes text
			$total_likes = 0;
			$total_likes = $vot_obj->getTotalVotes($row->getId(),"blog",1,null);
			$textPrint	=	$this->language("like_singular");
			if($total_likes > 1)
			{
				$textPrint	=	$this->language("like_plural");
			}
			
			//set like-dislike class and style
			$classTag		= "like-dislike";
			$mainDivStyle	= "display: none;";			
			if($tagStr!="" || $total_likes > 0)
			{
				$classTag		= "like-dislike like-dislike-img";
				$mainDivStyle	= "display: block;";
			}
		 ?>
		 
		 <div class="<?php echo $classTag;?>" style="<?php echo $mainDivStyle;?>" id="journal_tag_div_<?php echo $row->getId();?>">
                   
		 <?php if ($total_likes>0){$totalLikeDisplay="";}else{$totalLikeDisplay="display:none";}?>
		 	<span class="like-dislike-l f-left">
            <span id="you-like-this-thumb-<?php echo $row->getId();?>"  style="<?php echo $unlikeStyle?>">
			<img src="<?php echo $this->cdnUri()?>/images/like-icon-2.jpg" alt="Like" class="f-left" />
			<span id="you-like-this-<?php echo $row->getId();?>" style="<?php echo $unlikeStyle?>"><?php echo $this->language("like_you");?></span>
            </span>
            <a href="<?php echo $this->seoUrl('/journal/user-like-this/type/blog/item_id/'.$row->getId());?>" class="like-this-l-link">
			<span id="total_likes_<?php echo $row->getId();?>"  style="<?php echo $totalLikeDisplay?>">
			<?php echo $total_likes.' '.$textPrint;?>
			</span>
			</a>
            </span>
			
			<?php
			//set style for seperator
			$displaySeperator = "display: none;";
			if($tagStr!="" && $total_likes > 0)
			{
				$displaySeperator = "display: block;";
			}			
			?>
			<span class="like-dislike-pipe-seperator" style="<?php echo $displaySeperator;?>" id="journal_tag_sep_<?php echo $row->getId();?>">&nbsp;</span>
			
		  <?php if(isset($tagStr) && $tagStr!=""){?>
		  <span class="like-dislike-r f-left" id="journal_tag_str_<?php echo $row->getId();?>">Tags: <?php echo $tagStr;?></span>
		  <?php }?>
		  
        </div>
		<div class="clear"></div>
	<a href="/journal/view-post/blog_id/<?php echo $row->getId();?>" class="orange-sml">View Journal</a>	 
	<?php
		 $shareLink = Zend_Registry::get('siteurl')."/journal/view-post/blog_id/".$row->getId();
	?>
	<span class="share-id-option">
		<a href="javascript://" id="share-link-dd-<?php echo $row->getId();?>" class="share-link-dd">Share It</a>
		<span id="share-link-dd_menu-<?php echo $row->getId();?>"  class="share-link-dd_menu" >
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt="" /></a>
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt="" /></a>
		<!--<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=<?php //echo $shareLink;?>&amp;title=<?php //echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Delicious"><img src="/images/delicious-icon-sml.png" alt="" /></a>-->
		<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=<?php echo $shareLink;?>&amp;title=<?php echo $row->getTitle();?>&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt="" /></a>
		</span>
	</span>
</div>
<script type="text/javascript">
$(document).ready(function() {

	$("#share-link-dd_menu-<?php echo $row->getId();?>").hide();
	$("#share-link-dd-<?php echo $row->getId();?>").click(function(e) {          
		e.preventDefault();
		$("#share-link-dd_menu-<?php echo $row->getId();?>").toggle("slow");
		$("#share-link-dd-<?php echo $row->getId();?>").toggleClass("menu-open");
	});
	
	$("#share-link-dd_menu-<?php echo $row->getId();?>").mouseup(function() {
		return false;
	});
	
});
</script>
<?php 
}//end of foreach
}//end of if
?>
