<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<?php echo $this->headTitle(); ?>  
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta property="og:site_name" content="Gap Daemon" />
<meta property="og:title" content="Nature Image" />
<meta property="og:type" content="article" />
<meta property="og:description" content="My another test for today" />
<meta property="og:image" content="http://gd.pbodev.info/media/album/thumb/album_1299755697_62.jpg" />
<meta property="og:url" content="http://gd.pbodev.info/album/my-photos/photo/album/17/id/145" />
<meta property="fb:app_id" content="186016964775844" />  
<?php echo $this->headMeta(); ?>
	
  
	  <?php 
	  /*-------------- jquery ui----------------------*/
	  if($this->jQuery()->isEnabled())
		echo $this->jQuery();
	  /*-----------------------------------------------*/
	 ?>
  
  <?php echo $this->headScript(); ?>
  
  <?php echo $this->headLink(); ?>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox({
        loadingImage : '/images/facebox/loading.gif',
        closeImage   : '/images/facebox/closelabel.png'
      })
    })
  </script>
 
</head>




<body  >
   
<div id="mainwrapper">
    <div id="main" >

	<!-- Header -->
	<?php echo $this->pageElement('header')?>
	<!-- Header -->
	<div class="google-rgt-banner">
		<img src="/images/r-ban.jpg" />
	</div>
	<div id="contentArea">
		<!-- Left -->
		<div id="contentLeft">
			<?php echo $this->pageElement('left')?>
		</div>
		<!-- Left -->
		
		<div id="contentRight">
		<?php echo $this->layout()->content ?>
		</div>

	</div>
</div>

<!-- Footer -->
<?php echo $this->pageElement('footer')?>
<!-- Footer -->
</div>

</body>
</html>
