<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle(); ?>   
	<?php echo $this->headMeta(); ?>
	
  
	  <?php 
	  /*-------------- jquery ui----------------------*/
	  if($this->jQuery()->isEnabled())
		echo $this->jQuery();
	  /*-----------------------------------------------*/
	 ?>
  
  <?php echo $this->headScript(); ?>
  
  <?php echo $this->headLink(); ?>
  <?php if ($this->custom_head) {echo $this->custom_head;}?>
  <!--<script src="<?php echo $this->cdnUri()?>/js/menu.js" type="text/javascript"></script>
--></head>




<body class="single"<?php if ($this->custom_body) {echo $this->custom_body;}?>>

<!-- Header -->
<?php echo $this->pageElement('header')?>
<!-- Header -->

<!-- Middle Container -->
<div class="middle-container">
<div id="main" >
<div id="contentArea">

<!-- Left -->
<div id="contentLeft">
<?php echo $this->pageElement('left')?>
</div>
<!-- Left -->
		
<!-- Right -->
<div id="contentRight">
<?php echo $this->layout()->content ?>
<?php echo $this->pageElement('right-my-account')?>
</div>
<!-- Right -->

</div>
</div>
</div>
<!-- Middle Container -->

<!-- Footer -->
<?php echo $this->pageElement('footer')?>
<!-- Footer -->

</body>
</html>
