<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle(); ?>   
	<?php echo $this->headMeta(); ?>
	<?php 
	  /*-------------- jquery ui----------------------*/
	  if($this->jQuery()->isEnabled())
		echo $this->jQuery();
	  /*-----------------------------------------------*/
	?>
  <?php echo $this->headScript();?>
  <?php echo $this->headLink(); ?>
</head>

<body>
<div id="mainwrapper">
	<div id="main" >
	<!-- Header -->
	<?php echo $this->pageElement('header');?>
	<!-- Header -->	
	<div id="contentArea" class="nopadd">
		<?php echo $this->layout()->content;?>
	</div>
	</div>
	<!-- Footer -->
	<?php echo $this->pageElement('footer');?>
	<!-- Footer -->
</div>
</body>
</html>
