
<div class="content-box column-left">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;">Happy Diwali - 2011</h3>
    </div> <!-- End .content-box-header -->

    <div class="content-box-content" style="display: block; min-height:140px">
    <div class="tab-content default-tab" style="display: block;">
    
           
            
        <center><br /><embed src="http://www.goodlightscraps.com/content/diwali-greetings2011/diwali-card-1.swf" quality="high" width="450" height="375" type='application/x-shockwave-flash'></embed><br /></center>
        
            
    </div> <!-- End #tab3 -->        
    </div> <!-- End .content-box-content -->
</div>
<br class="clear"/>