  <div class="box1">
    <h1>YOUR PERSONAL TRAVEL COMMUNITY</h1>
    <p>Gap Daemon allows you to create your personal travel community online and links into your existing social network.</p>
    <ul class="social-icons">
		<li><span class="st_twitter_custom" displayText="Tweet"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/twitter-icon.jpg" alt="" /></a></span></li>
		<li><span class="st_facebook_custom" displayText="Facebook"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/facebook-icon.jpg" alt="" /></a></span></li>
		<li><span class="st_delicious_custom" displayText="Google Buzz"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/delicious-icon.jpg" alt="" /></a></span></li>
		<li><span class="st_gbuzz_custom" displayText="Google Buzz"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/gmail-icon.jpg" alt="" /></span></a></li>
		<li><span class="st_stumbleupon_custom" displayText="Google Buzz"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/stumbleupon-icon.jpg" alt="" /></a></span></li>
		<li><span class="st_digg_custom" displayText="Google Buzz"><a href="javascript:void(0);"><img src="<?echo $this->cdnUri()?>/images/digg-icon.jpg" alt="" /></span></a></li>
		<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:'1e8ad313-8884-476f-9ee5-3f7648e82180'});</script>
    </ul>
  </div>
