<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a href="/admin/user" class="add">Back</a>
	</span>
	User - Edit</div>	
		<div id="rightsidecontentpart">
			<span class='red'><? echo $this->msg;  ?></span>
			<div>
				<table cellspacing="2" cellpadding="3" border="0" align="left" width="53%">
					<tr>
						<td><b>Username:</b></td><td><label><?php echo $this->username;?></label></td>
					</tr>
					<?php if($this->image_name!="" && file_exists("media/picture/profile/".$this->image_name)){?>
					<tr>
					<td valign="top"><b>Profile Photo:</b><br /></td>
					<td>
					<div id="profile_image">
					<img width="100px" height="76px" border="0" src="<?php echo $this->thumbImage;?>" alt="" />
					<a href="javascript://" onclick="removeProfileImage('<?php echo $this->image_name;?>', <?php echo $this->user_id;?>)">Remove</a>
					</div>
					<span id="remove_image_response"></span>
					</td>
					</tr>
					<?php }?>
				</table>				
			</div><br class="clear" />
			<?php echo $this->form?>
			
		</div>
	</div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
<script type="text/javascript">
$(function() {
	$("#cityName").autocomplete({
		source: "/index/autosuggest-city/",
		minLength: 1,
		select: function(event, ui) {
		$("#cityId").val(ui.item.id);
		}
	});

	function split(val) {
		return val.split(/,\s*/);
	}
	
	function extractLast(term) {
		return split(term).pop();
	}
		
	$("#otherLanguages").autocomplete({
		source: function(request, response) {
			$.getJSON("/index/autosuggest-language/", {
				term: extractLast(request.term)
			}, response);
		},
		search: function() {
			// custom minLength
			var term = extractLast(this.value);
			if (term.length < 2) {
				return false;
			}
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});

function removeProfileImage(image, user_id)
{
	if(confirm("Are you sure? You want to delete user profile photo?"))
	{
		$("#remove_image_response").show();
		$("#remove_image_response").html("<img src='/images/ajax-loader.gif'>");
		var params="mode=ajax&image="+image+"&user_id="+user_id;
		//alert("param="+params);
		$.ajax({
				   type: "POST",
				   url: "/admin/user/remove-profileimage/",
				   data: params,
				   dataType: "json",
				   success: function(json)
				   {
						if(json.error==1)
						{
							$("#remove_image_response").html(json.response);
						}
						else
						{
							$("#remove_image_response").html(json.response);
							$("div#profile_image").html('');
							$("div#profile_image").hide();
						}	
				   },
				   error: function (json, status, e)
				   {
						alert("json="+json+" status="+status+" e="+e);
				   }
			 });
	}		 
}
</script>	 
