<div id="footer">
    <div class="footer-m">
	
	<div class="footer-logo">2010 Gap Daemon. All rights reserved</div>
	<div class="bookmark">Bookmark&nbsp;&nbsp;Us<br />
	<img src="<?echo $this->cdnUri()?>/images/bookmark.jpg" alt="" /></div>
	<div class="bookmark">Follow&nbsp;&nbsp;Us<br />
	<img src="<?echo $this->cdnUri()?>/images/twitter.jpg" alt="" /><img src="<?echo $this->cdnUri()?>/images/facebook.jpg" alt="" /></div>
	
	<div class="further-info">	
	<h1>FURTHER&nbsp;&nbsp;&nbsp;&nbsp;INFORMATION</h1>
	<ul class="f-left">
	<li><a href="<?php echo $this->seoUrl("/index/about")?>">About Us</a></li>
	<li><a href="<?php echo $this->seoUrl("/index/contact")?>">Contact Us</a></li>
	<li><a href="<?php echo $this->seoUrl("/index/work-for-us")?>">Work for Us</a></li>
	<li><a href="http://blog.gapdaemon.com" target="_blank">GD Blog</a></li>
	<li><a href="<?php echo $this->seoUrl("/index/safety-policy")?>">Safety Policy</a></li>
    </ul>
	
	<ul class="f-right">
	<li><a href="<?php echo $this->seoUrl("/index/terms-conditions")?>">Terms &amp; Conditions</a></li>
	<li><a href="<?php echo $this->seoURl("/index/privacy-policy")?>">Privacy Policy</a></li>
	<li><a href="<?php echo $this->seoURl("/index/press-media")?>">Press/Media</a></li>
	<li><a href="<?php echo $this->seoURl("/index/advertising-and-partnerships")?>">Advertising and <br/>Partnerships</a></li>		
    </ul>
	</div>
		
     </div>
</div>

<!-- Google Analytics Code -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18161261-1']);
  _gaq.push(['_setDomainName', '.gapdaemon.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

