<!-- Start Main Center Area -->
<div class="main-center">
<div class="map-top-boxs">

<!--Map box START -->
<div class="main-center-box">
<div class="map_details">
<?php echo $this->content("home_login_where_i_am");?>
</div>
</div>
<!--Map box END -->


<!--MEET OTHER BACKPACKERS START -->
<?php
$users	= array();
$userM	= new Application_Model_User();
$users	= $userM->fetchAll("status='active'","addedon DESC",3);

$userNs = new Zend_Session_Namespace('members');
$isLoggedIn = $userNs->userId;

if($isLoggedIn)
{
	/*
	$userFriend	= new Application_Model_Friend();
	$arrFriend	= $userFriend->getUserFriend($isLoggedIn);

	$friendsId="";
	if($arrFriend)
	{
		$friendsId	=	implode("', '",$arrFriend);
		$users		=	$userM->fetchAll("id IN('{$friendsId}')","addedon DESC",3);
	}
	else
	{
		$isLoggedIn=false;
	}*/
}
?>

<div class="main-center-box">
<div class="m-box-corner"><img src="/images/m-top.png" alt="" /></div>
<div class="m-box-content">
<?php echo $this->content("meet_backpackers");?>
<?php 
foreach($users as $user)
{
	if($user->getStatus()=="active")
	{
		$username = $user->getUsername();
		$name = $user->getFirstName()." ".$user->getLastName();
?>
<div class="m-tab-img">
<a href="<?php echo $this->seoUrl('/'.$username); ?>" alt="<?php echo $name;?>" title="<?php echo $name;?>">
<img src="/image?src=<?php echo $user->getThumbnail();?>&size=journal&<?php echo rand(1,100000);?>" border="0" alt="<?php echo $name;?>" title="<?php echo $name;?>" />
</a>
<p><a href="<?php echo $this->seoUrl('/'.$username); ?>" alt="<?php echo $name;?>" title="<?php echo $name;?>"><?php echo $name;?></a></p>
</div>
<?php
	}//end if
}//end foreach
?>
</div>
<div class="m-box-corner"><img src="/images/m-bottom.png" alt="" /></div>
</div>
<!--MEET OTHER BACKPACKERS END-->


<!-- Advertising START-->
<div class="advertise">
<div class="advertise-top-crnr"><img src="/images/gry-brdr-lft.jpg" width="9" height="9" align="left" /><img src="/images/gry-brdr-rght.jpg" width="9" height="9" align="right" /></div>
<div class="advertise-main-brdr">ADVERTISEMENT <!--<img src="/images/add-1.jpg" />-->
<?php
  $banner = new Cms_Model_Banner();
  $banner ->showBanner("right", "600", "160");
?> 
</div>
<div class="advertise-crnr-btm">
<img src="/images/gry-brdr-btmlft.jpg" width="9" height="9" align="left" />
<img src="/images/gry-brdr-btmrght.jpg" width="9" height="9" align="right" />
</div>
</div>
<!-- Advertising END -->
</div>

<div class="map-top-boxs">
<!--WHAT’S NEW ON GAP DAEMON? START-->
<div class="main-center-box">
<div class="m-box-corner"><img src="/images/m-top.png" alt="" /></div>
<div class="m-box-content"><h3>MOST POPULAR ON GAP DAEMON</h3><br />

<p>Take a look at the most popular articles, blog posts and features on Gap Daemon this week:</p>
<div class="m-line">&nbsp;</div>
<p>
<span>
<a href="http://blog.gapdaemon.com/2010/12/14/surviving-in-japan-coping-with-the-language-barrier/ ">Surviving Japan</a><br />
<a href="http://blog.gapdaemon.com/2010/12/06/five-essential-gap-year-apps/">Five Essential Gap Year Apps</a><br />
<a href="http://blog.gapdaemon.com/2011/01/11/five-weird-and-wonderful-travel-jobs/">Five Weird and Wonderful Travel Jobs</a><br />
</span>
</p>
</div>
<div class="m-box-corner"><img src="/images/m-bottom.png" alt="" /></div>
</div>
<!--WHAT’S NEW ON GAP DAEMON? END-->

<!--PHOTO OF THE WEEK START-->
<div class="main-center-box">
<div class="m-box-corner"><img src="/images/m-top.png" alt="" /></div>
<div class="m-box-content"><h3>PHOTO OF THE WEEK</h3><br />
  <img src="/images/photo-of-the-week.gif" width="278" height="128" style="border: 1px solid #e6e6e6;" alt="" />
  <p>Will Peach's recent trip to Iceland prompted some beautiful photography...<br />
    <a href="http://www.gapdaemon.com/journal/view-post/blog_id/89">Read more »</a></p>
</div>
<div class="m-box-corner"><img src="/images/m-bottom.png" alt="" /></div>
</div>
<!--PHOTO OF THE WEEK END-->

<!--MY JOURNALS START-->
<!--
<div class="main-center-box">
<div class="m-box-corner"><img src="/images/m-top.png" alt="" /></div>
<div class="m-box-content"><h3>JOURNAL POST OF THE WEEK</h3>
<div class="m-box-img"><img src="/images/mj.png" width="128" height="128" alt="" align="left" />
<span><a href="http://www.gapdaemon.com/journal/view-post/blog_id/83">The Hippy Market Formentera</a></span><br />

<span class="posted">Posted by 1 minute ago</span><br />
<span class="posted">|</span> <span class="comment">5 Comment</span>  <span class="posted">|</span>  <span class="comment">Like</span><br />
<span id="text-p">Curabitur est augue, vehicula sed sollicitudin.</span></div> <p>Curabitur est augue, vehicula sed sollicitudin ut, eleifend eget eros. Donec eu tortor id ante fermentum fermentum.   </p>
</div>
<div class="m-box-corner"><img src="/images/m-bottom.png" alt="" /></div>
</div>
-->
<?php echo $this->pageElement('home_journal');?>
<!--MY JOURNALS END-->

</div>
</div>
<!-- End Main Center Area -->
