<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a href="/admin/category/index/type/<?php echo $this->type?>" class="add">Back</a>
	</span>
	<?php echo $this->title?></div>	
		<div id="rightsidecontentpart">
			<span class='red'><? echo $this->successMsg;  ?></span>
			<?php echo $this->form?>
			
			<?php 
			//file_exists($_SERVER["DOCUMENT_ROOT"]."/media/picture/category/".$this->type."/".$this->imgName);
			if($this->imgName!="" && file_exists("media/picture/category/".$this->type."/".$this->imgName)){?>
			<br />
			<img src='/media/picture/category/<?php echo $this->type ?>/<?php echo $this->imgName ?>' width='128' height='84' align='left' class='f-left'> 
			<?php }?>
		</div>
	</div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
