<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a class="add" href="/admin/global-settings">Back</a>
	</span>
	Global Settings - Edit</div>
		
		<div id="rightsidecontentpart">
			<?php echo $this->form?>
		</div>
	</div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
