<?php
/* 
$this->custom_head .= '<script src="/js/fckeditor/fckeditor.js" type="text/javascript"></script>';
$this->custom_head .= "<script language='javascript' type='text/javascript' src='/js/customs.js'></script>";
$this->custom_body = ' onload="setupFCK(\'content\',400,600)" ';
*/
$this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
$this->ckeditor = 'ckeditor'; //To tell the layout ckeditor must be loaded .
?>
<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a href="/admin/articles/" class="add">Back</a>
	</span>Article - Add</div>
 <div id="rightsidecontentpart">
  <span class='red'>
<? echo $this->msg;  ?>
</span>

		<?php
		
			$this->form->setAction($this->url(array('action' => 'add'))); 
			echo $this->form;
		?>
  </div>
	</div>
</div>
<?php echo $this->setupEditor( 'content' ); ?>