<div class="right-box">
                <h2 class="box-head">PEOPLE WHO ARE HERE</h2>
                <ul class="people-here">
                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img2.jpg" alt="Kevina" /></a></div>
                        <a href="#">Kevina G</a>
                </li>
                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img1.jpg" alt="Diana D" /></a></div>
                        <a href="#">Diana D</a>
                </li>

                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img4.jpg" alt="Warren T" /></a></div>
                        <a href="#">Warren T</a>
                </li>
                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img3.jpg" alt="" /></a></div>
                        <a href="#">Diddy P</a>
                </li>
                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img2.jpg" alt="Kevina" /></a></div>
                        <a href="#">Kevina G</a>
                </li>
                <li>
                        <div class="people-img"><a href="#"><img src="<?echo $this->cdnUri()?>/images/img2.jpg" alt="Kevina" /></a></div>
                        <a href="#">Kevina G</a>
                </li>
                </ul>
                <div class="view-link"><a href="#">VIEW ALL</a></div>
        </div>