<div class="right-box">
                <h2 class="box-head">WHATS GOING ON</h2>
                <div class="right-inner-box">
                        <div class="right-inner-box-title"><a href="#">Father's Day (UK)</a></div>
                        <div class="whats-date">Sun, 20 Jun 10</div>
                        <p>Don't forget to get in touch with Dad!</p>
                </div>

                <div class="right-inner-box">
                        <div class="right-inner-box-title"><a href="#">Downtown Arts Festival</a></div>
                        <div class="whats-date">Mon, 21 Jun - Sat, 26 Jun 10</div>
                        <p>Get creative with the local arts scene. </p>
                </div>

                <div class="right-inner-box">
                        <div class="right-inner-box-title"><a href="#">Queenstown Street Market</a></div>
                        <div class="whats-date">Sun, 27 Jun 10</div>
                        <p>Grab yourself a bargain and soak up the atmosphere.</p>
                </div>
                <div class="view-link"><a href="#">VIEW ALL</a></div>
        </div>