Are you sure you want to delete?
<input type="button" name="yes" value="Yes" id="yes" />
<input type="button" name="no" value="No" id="no" />

<script>
$(document).ready(function(){
	$("input#no").click(function(){
		
		 $(document).trigger('close.facebox');
	});
});

$(document).ready(function(){
	$("input#yes").click(function(){

		var photoId	=	$("#current_photo_id").val();

		 var requesturl	=	"/album/my-photos/album-photo-delete";

		 $.post(requesturl, {photoId:photoId},
				   function(html){
			 		slidePhotoEdit(<?php print $this->nextId;?>);
			 		$("#photo-saved").show();
		 			$("#photo-saved").html('Photo has been deleted.');
		 			RAVIN_DelayedHide('photo-saved');			 				
				});
		
		
		$(document).trigger('close.facebox');
	});
});

function slidePhotoEdit(photoId)
{

	$("#photo-loading").show();
	 var requesturl	=	"/album/my-photos/album-photo-edit";
	 
	 $.post(requesturl, {photoId:photoId },
			   function(html){
				$("#photo-editing").html(html);		
				$("#photo-loading").hide();				
			});
}
</script>