<link rel="stylesheet" type="text/css" href="/style/facebook-tag.css" media="all">
<script src="/js/facebook-tag.js" type="text/javascript"></script>

<span class="page_number">Back To <a href="/album/my-photos/album-photos/id/<?php print $this->albumId;?>"><?php print $this->albumName;?></a>  |  
<a href="/album/my-photos/photo-download/name/<?php print $this->photo;?>">Download Photo</a></span>
<span class="pages">Photo <?php print $this->photoPosition;?> of <?php print $this->numPhotoAlbum;?> 
	<span> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->prevId;?>);"><</a> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->nextId;?>);">></a> </span>
</span>
<!-- End Heading -->

<!-- Start Tagged Images -->
<div class="viewallmyphoto">
<a href="javascript:void(0);">
<img width="591" src="/images/album/custom/<?php print $this->photo;?>" alt="" id="crop-image" onclick="slideImage(<?php print $this->nextId;?>);">
</a>
</div>
<!-- End Tagged Images -->

<!-- Start Btns Area -->
<div class="untags">
<span id="like-photo-container">
<?php if($this->numVote == 0){?>
<a href="javascript:void(0);" id="like-photo">
<img src="/images/fb.jpg" alt="" width="51" height="23" class="f-left">
</a>
<?php }else{?>
<a href="javascript:void(0);" id="unlike-photo">
<img src="/images/fb-unlike.jpg" alt="" class="f-left">
</a>
<?php }?>
</span>
<div class="description"><?php print $this->description;?></div>
<div class="f-right">
<a href="javascript:void(0);" id="photo-edit-button" class="button">Edit</a>
<a href="javascript:void(0);" id="photo-location" class="button">location</a>
<a href="javascript:void(0);" id="album-photo-tag" class="button">Tag</a>
<div id="icon">
  <div class="sign"><a href="#" class="signin"><span>SHARE IT</span></a></div>
  <div id="signin_menu">
    <div id="signin"> 
    <img src="/images/facebook.jpg" width="26" height="26" /> 
    <img src="/images/twiiter.jpg" width="26" height="26" /> 
    <img src="/images/delicious.jpg" width="26" height="26" /> 
    <img src="/images/digg.jpg" width="25" height="26" /> 
    <img src="/images/google.jpg" width="26" height="26" /> 
    <img src="/images/stumblr-upon.jpg" width="26" height="26" /> </div>
  </div>
</div>
</div>

<div id="tag" style="display:none;">
	<div id="tag-icon"></div>
	<div class="finish-taging">Click on an area in the photo tag
		<a href="javascript:void(0);" id="finish-tagging" class="button">FINISH TAGGING</a>
	</div>
</div>

</div>
<!-- End Btns Area -->
<script>
$(document).ready(function(){
	$("a#like-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/like-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#unlike-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/unlike-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#photo-edit-button").click(function(){

		 $("#photo-editing").fadeIn(800);
		 var photoId	=	$("#photo_id").val();

		 var requesturl	=	"/album/my-photos/album-photo-edit";
		 
		 $.post(requesturl, {photoId:photoId },
				   function(html){
					$("#photo-editing").html(html);						
				});

	});
});

$(document).ready(function(){
	$("a#photo-location").click(function(){
		
			$("#photo-location-box").fadeIn(800);
				
	});
});

$(document).ready(function(){
	$("div#close-photo-map").click(function(){
		
			$("#photo-location-box").fadeOut(800);
				
	});
});

$(document).ready(function(){
	$("a#album-photo-tag").click(function(){//

		$("#crop-image").attr("style","cursor: crosshair");
		$("#tag").slideDown(500);
		$("#tag-image-flag").val('1');
	});
});

$(document).ready(function(){
	$("a#finish-tagging").click(function(){//

		$("#crop-image").attr("style","");
		$("#tag").slideUp(500);
		$("#tag-image-flag").val('0');
	});
});


if('<?php echo $this->myLongitude?>'=="" || '<?php echo $this->myLatitude?>'=="")
{
	locateMe();
	
}else{

var latLng = new google.maps.LatLng('<?php echo $this->myLatitude?>', '<?php echo $this->myLongitude?>');
buildMap(latLng);
}
</script>