<div class="box f-left">
	<h1>Plot Your journey</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac ipsum mi. Ne sed odio tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<img src="<?echo $this->cdnUri()?>/images/map.jpg" alt="" class="map" />
</div>

<div class="box f-right">
	<h1>GAP DAEMON</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac ipsum mi. Ne sed odio tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<img src="<?echo $this->cdnUri()?>/images/gd.png" alt="" class="gd" />
</div>

<br class="clear" />

<div class="box1 f-left">
	<h1>MEET LIKE MINDED PEOPLE</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac ipsum mi. Ne sed odio tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<ul>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
	</ul>
</div>

<div class="box1 f-right">
	<h1>UPLOAD YOUR PHOTOS</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac ipsum mi. Ne sed odio tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<ul>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
		<li><img src="<?echo $this->cdnUri()?>/images/1.jpg" alt="" /></li>
	</ul>
</div>

<?php
$user=new Application_Model_User();
var_dump($user);
?>