<!--<script type="text/javascript" src="/js/latest/lp-js-library.js"></script>
<link rel="stylesheet" href="/style/global-static.css" type="text/css" media="all" />-->
<!-- Start Header -->
<div class="main-header">
<!-- Start Upper Part -->
<div class="logo-div">
<a href="<?echo $this->cdnUri()?>" class="logo"></a>
<!--<img src="<?echo $this->cdnUri()?>/images/top-banner.jpg" width="728" height="90" align="right" class="banner" />-->
<?php
	$bannerHeader = new Cms_Model_Banner();
	$bannerHeader->showBanner("top", "600", "120");
?>
</div>
<!-- End Upper Part -->
<!-- Start Main Menu -->
<div class="main-menu">
<ul id="mainNav" class="notReady">
<li><a href="<?echo $this->cdnUri()?>" class="active">HOME</a></li>
<?php if (Zend_Auth::getInstance()->hasIdentity()){ ?>
<li><a href="<?echo $this->cdnUri()?>/where-i-am">MY &nbsp;GAP &nbsp;DAEMON</a></li>
<?php }else{?>
<li><a href="<?echo $this->cdnUri()?>/index/user-login">MY &nbsp;GAP &nbsp;DAEMON</a></li>
<?php }?>
<li><a href="<?echo $this->cdnUri()?>/journals">JOURNALS</a></li>
<!--<li><a href="<?echo $this->cdnUri()?>/travelguides">TRAVEL &nbsp;GUIDES</a></li>-->
<li class="tab tabNotReady destinations current">
<a class="navHead" href="<?echo $this->cdnUri()?>/travelguides" rel="nofollow">
<span>TRAVEL &nbsp;GUIDES</span>
<img class="arrow invisible" src="/images/15x15_trans.gif" alt="More" />
</a>
</li>
<!--<li><a href="<?echo $this->cdnUri()?>/work-study-volunteer">WORK/STUDY/VOLUNTEER</a></li>
<li><a href="<?echo $this->cdnUri()?>/advice">ADVICE</a></li>-->
<li class="tab tabNotReady workstudy current">
<a class="navHead" href="<?echo $this->cdnUri()?>/work-study-volunteer" rel="nofollow">
<span>WORK/STUDY/VOLUNTEER</span>
<img class="arrow invisible" src="/images/15x15_trans.gif" alt="More" />
</a>
</li>
<li class="tab tabNotReady advice current">
<a class="navHead" href="<?echo $this->cdnUri()?>/advice" rel="nofollow">
<span>ADVICE</span>
<img class="arrow invisible" src="/images/15x15_trans.gif" alt="More" />
</a>
</li>
<li><a href="<?echo $this->cdnUri()?>/shop/amazon">TRAVEL &nbsp;SHOP	</a></li>
<li><a href="http://blog.gapdaemon.com/" target="_blank">GD &nbsp; BLOG</a></li>
</ul>

<script language="javascript" type="text/javascript">
// <![CDATA[
   _destinationsGlobalNav = function(data) {
        new DestinationsGlobalNav(data['nav'], "#mainNav > li.destinations");
    };
	
	_adviceGlobalNav = function(data) {
        new DestinationsGlobalNav(data['nav'], "#mainNav > li.advice");
    };
	
	_workstudyGlobalNav = function(data) {
        new DestinationsGlobalNav(data['nav'], "#mainNav > li.workstudy");
    };
// ]]>

<?
$travelGuides = $this->pageElement('header_travelguides_navigations');
$travelAdvice = $this->pageElement('header_advice_navigations');
$workstudyTab = $this->pageElement('header_wsv_navigations');
?>
var travelGuides = {"nav":<?php echo $travelGuides;?>};
var travelAdvice = {"nav":<?php echo $travelAdvice;?>};
var workstudyTab = {"nav":<?php echo $workstudyTab;?>};
jQuery(document).ready(function()
{
    if (typeof(_destinationsGlobalNav) != 'undefined') {
        _destinationsGlobalNav(travelGuides);
    }
	if (typeof(_adviceGlobalNav) != 'undefined') {
        _adviceGlobalNav(travelAdvice);
    }
	if (typeof(_workstudyGlobalNav) != 'undefined') {
        _workstudyGlobalNav(workstudyTab);
    }
});
</script>


</div>
<div class="clear"></div>
<!-- End Main Menu -->
</div>
<!-- End Header -->
