<?php
/* 
$this->custom_head .= '<script src="/js/fckeditor/fckeditor.js" type="text/javascript"></script>';
$this->custom_head .= "<script language='javascript' type='text/javascript' src='/js/customs.js'></script>";
$this->custom_body = ' onload="setupFCK(\'content\',400,600)" ';
*/
$this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
$this->ckeditor = 'ckeditor'; //To tell the layout ckeditor must be loaded .
?>
<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a href="/admin/journals/" class="add">Back</a>
	</span>
	
	Blog Post - Edit</div>
		<div id="rightsidecontentpart">
		    <span class='red'><? echo $this->successMsg;  ?></span>
			<?php echo $this->form ?>
		</div>
	</div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
<?php echo $this->setupEditor( 'content' ); ?>
