<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle(); ?>   
	<?php echo $this->headMeta(); ?>
	
  
	  <?php 
	  /*-------------- jquery ui----------------------*/
	  if($this->jQuery()->isEnabled())
		echo $this->jQuery();
	  /*-----------------------------------------------*/
	 ?>
  
  <?php echo $this->headScript(); ?>
  
  <?php echo $this->headLink(); ?>
  <!-- <script src="<?php //echo $this->cdnUri()?>/js/menu.js" type="text/javascript"></script> -->
</head>




<body  >
<div class="main-pager"><div id="main" >

	<!-- Header -->
	<?php echo $this->pageElement('header')?>
	<!-- Header -->

<div class="google-rgt-banner">
		<img src="/images/r-ban.jpg" />
	</div>

	<div id="contentArea">
		<!-- Left -->
		<div id="contentLeft">
			<?php echo $this->pageElement('left')?>
		</div>
		<!-- Left -->
		
		<div id="contentRight">
		<?php echo $this->layout()->content ?>
		
		<!-- Right -->
			<?php echo $this->pageElement('right-my-account')?>
		<!-- Right -->
		</div>
	</div>
</div>
</div>	<!-- Footer -->
	<?php echo $this->pageElement('footer')?>
	<!-- Footer -->


</body>
</html>
