<?php
$id = $this->countryId;
$lonelyPlanetCountry	= array();

//select details from lonely_planet_country table
$lonelyPlanetCountryM	=	new Application_Model_LonelyPlanetCountry();
$lonelyPlanetCountryM	=	$lonelyPlanetCountryM->fetchRow("country_id={$id}");
	
if(false!==$lonelyPlanetCountryM)
{
	$lonelyPlanetCountry = $lonelyPlanetCountryM;
}
?>
<?php
	$travelArr = array();
	$travelArr['getting there and away'] = "";
	$travelArr['getting around']	= "";
	$travelArr = unserialize($lonelyPlanetCountry->getTransport());
	if(isset($travelArr['getting there and away']))
	{
		$gettingThereAndAway = $travelArr["getting there and away"];
	}
	if(isset($travelArr['getting around']))
	{
		$gettingAround = $travelArr["getting around"];
	}
?>
<form name="frmTravel" id="frmTravel" enctype="multipart/form-data" method="post" action="/admin/featured-city/update-country-tab3-data">
	<input type="hidden" name="update_action" value="travel">
	<input type="hidden" name="lonelyPlanetCountryId" value="<?php echo $lonelyPlanetCountry->getId();?>">
	<input type="hidden" name="countryId" value="<?php echo $id;?>">
	<input type="hidden" name="page" value="<?php echo $this->page;?>">
	<table align="center" cellspacing="2" cellpadding="4" border="0" width="100%">
		<tr><td colspan="2"><div class="form-sub-head">Travel</div><span class="orange" id="tab3_msg"></span></td></tr>
		<tr><td valign="top">Getting There And Away</td><td valign="top"><textarea cols="40" rows="10" name="gettingThereAndAway" class="title-input-box" style="width:795px !important;"><?php echo $gettingThereAndAway;?></textarea></td></tr>
		<tr><td colspan="2">&nbsp;</td></tr>
		<tr><td valign="top">Getting Around</td><td valign="top"><textarea cols="40" rows="10" name="gettingAround" class="title-input-box" style="width:795px !important;"><?php echo $gettingAround;?></textarea></td></tr>
		<tr><td>&nbsp;</td><td><input type="submit" value="Save" name="btnSave" ></td><td></td></tr>
	</table>
</form>
