<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading" class="headingblack">
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a class="add f-right" href="/admin/featured-city/travelguides-slides">Back</a></span>
	Add New Slide</div>
	<div id="rightsidecontentpart">
	<?php if($this->errorMsg != ""){ ?>
	<span class='red'><?php print $this->errorMsg;?></span>
    <?php }?>
  	<?php echo $this->form;?>
	</div>
  </div>
</div>
