
<form   method="post">
<div class="table_bx_var">
          <div class="form_table">
<!--          <div class="form_row">
    
    
                      <div class="form_col1">
                        <label>Old Password: <span>*</span></label>
                      </div>
                      <div class="form_col2"><input type="text"></div>
                    </div>-->
                    
                    <div class="form_row">
                      <div class="form_col1">
                        <label><?php echo $this->form->password->getLabel();?><span>*</span></label>
                      </div>
                      <div class="form_col2"><?php echo $this->form->password;?>
                          <?php if ($this->password_msg){?>
                        <span class="input-notification attention png_bg"><?php echo $this->password_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                        <?php }?>
                      </div>
                    </div>
                    
                    <div class="form_row">
                      <div class="form_col1">
                        <label><?php echo $this->form->confirmPassword->getLabel();?><span>*</span></label>
                      </div>
                      <div class="form_col2"><?php echo $this->form->confirmPassword;?>
                          <?php if ($this->cpassword_msg){?>
                            <span class="input-notification attention png_bg"><?php echo $this->cpassword_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                            <?php }?>
                      </div>
                        
                    </div>
                    <div class="form_row">
                      <div class="form_col1">
                        <label>&nbsp;</label>
                      </div>
                      <div class="form_col2"><input type="submit" name="submit" id="submitbutton" class="button" value="Save">
                  &nbsp;
                  <input type="button" name="cancel" class="button" id="cancelUserButton" value="Cancel" onclick='javascript: location.href="/admin"'></div>
                    </div>
          </div>
    </div>
    </form>