<form method="post" action="<?php echo $this->seoUrl("/admin/user/sub-groups")?>">
    <input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" alt="Search" onfocus="if(this.value=='Search...') this.value='';" onblur="if(this.value=='') this.value='Search...';"/>
    <input type="submit" value="Search" name="submit" class="button"/>
</form>
<?php if (count($this->paginator)): ?>


<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>
<table>
    <thead>
        <?php if($this->paginator->count()>1):?>
        
            <tr>
                <td colspan="6">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        
        <?php endif?>
        <tr>
            <th>S.No.</th>
            <th>Title</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $item): ?>
        <?php $sno++?>
        <tr id="subgroup_<?php echo $item->id?>">
            <td><?php echo $sno?></td>
            <td><?php echo $item->title; ?></td>
            <td>
                <!-- Icons -->
                <a title="Edit" href="<?php echo $this->seoUrl("/admin/user/edit-sub-group/id/".$item->id)?>"><img alt="Edit" src="/images/pencil.png"></a>
                 <?php 
                    $image="/images/icons/cross_circle.png";
                    $title="Click here to make employee active!";
                ?>
               
                &nbsp;&nbsp;
                <a title="<?php echo $title?>" href="<?php echo $this->seoUrl("/admin/user/delete-sub-group/id/".$item->id)?>" onclick="return confirm('Are you sure you want to delete?');"><img alt="<?php echo $title?>"  src="<?php echo $image?>"></a> 
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if($this->paginator->count()>1):?>
        <tfoot>
            <tr>
                <td colspan="6">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        </tfoot>
        <?php endif?>
        
    </tbody>
</table>
<?php endif; ?>
<script>
    /*function deleteSubGroup(id){
       var params='id='+id;
       if(!confirm("Are you sure you want to delete?")){
           return false;
       }
        $.ajax({
                   type: "POST",
                   url: "/admin/user/delete-sub-group",
                   data: params,
                   dataType:"json",
                   success: function(json)
                   {
                       $("#subgroup_"+id).hide('slow');
                        
                   },
                   error: function (json, status, e)
                   {
                       alert("error");
                    
                   }
               });
    }*/
    
</script>