
<?php $date=new Base_Date();?>

<div id="employee-info-content">
<table>
    <tbody>
        <tr ><td colspan="2"><img src="<?php echo $this->user->getThumbnail()?>"></img> </td></tr>
        <tr ><td>User Id:</td><td># <?php echo $this->user->getId()?></td></tr>
        <tr ><td>Email :</td><td><?php echo $this->user->getEmail()?></td></tr>
        <tr ><td>Username :</td><td><?php echo $this->user->getUsername()?></td></tr>
        <tr ><td>Mobile No. :</td><td><?php echo $this->user->getMobile()?></td></tr>
        <tr ><td>Gender :</td><td><?php echo ucfirst( $this->user->getSex())?></td></tr>
        <tr ><td>Correspondence Address :</td><td><?php echo ucfirst( $this->user->getCorrespondenceAddress())?></td></tr>
    </tbody>
</table>
</div>
