<?php
	$this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
	$this->ckeditor = 'ckeditor'; //To tell the layout ckeditor must be loaded .
?>
<div id="rightsidemain">
	<div id="rightcontentpart">
		<div id="rightsideheading" class="headingblack">
			<span style="margin: 0pt 15px 0pt 0pt; float: right;"><a class="add f-right" href="/admin/content/index/type/<?php echo $this->type;?>">Back</a></span>
			Edit Content
		</div>
		<div id="rightsidecontentpart">
		<?php
		if(isset($this->weekPhoto) && $this->weekPhoto!="") {?>
		<!--<div><b>Photo of The Week:</b> <img src="/media/picture/home/thumb_<?php //echo $this->weekPhoto;?>" width="150" height="100"/></div>-->
		<?php }?>
	
		<?php //echo $this->form;?>
		<form method="post" action="" enctype="multipart/form-data">
		<table align="center" cellspacing="5" cellpadding="10" border="0" width="100%">
		<tr><td><?php echo $this->form->title->getLabel();?></td><td><?php echo $this->form->title;?></td></tr>
		<tr><td><?php echo $this->form->alias->getLabel();?></td><td><?php echo $this->form->alias;?></td></tr>
		<tr>
			<td valign="top"><?php echo $this->form->weekPhoto->getLabel();?><br /><span class="span-field-note">(Upload 278x128 dimensions image)</span></td>
			<td>
			<?php
			if(isset($this->weekPhoto) && $this->weekPhoto!="")
			{
			?>
			<!--<img src="/media/picture/home/thumb_<?php echo $this->editorPic;?>" width="138" height="125"/>-->
			<img src="<?echo $this->cdnUri();?>/image?src=<?echo $this->cdnUri();?>/media/picture/home/thumb_<?php echo $this->weekPhoto;?>&w=278&h=128" style="border: 1px solid rgb(230, 230, 230);" />
			<?php }?><br />
			<?php echo $this->form->weekPhoto;?></td>
		</tr>
		<tr><td><?php echo $this->form->body->getLabel();?></td><td><?php echo $this->form->body;?></td></tr>
		<tr><td><?php echo $this->form->status->getLabel();?></td><td><?php echo $this->form->status;?></td></tr>
		<tr><td><?php echo $this->form->weight->getLabel();?></td><td><?php echo $this->form->weight;?></td></tr>
		<tr><td>&nbsp;</td><td><?php echo $this->form->cmdSubmit;?></td></tr>
		</table>
		</form>
		</div>
	</div>
</div>
<script language="javascript" type="text/javascript">
document.getElementById("alias").readOnly = true;
</script>

<?php 
if($this->displayEditor==true)
{
	echo $this->setupEditor( 'body' );
}
?>
