<?php
	$this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
	$this->ckeditor = 'ckeditor'; //To tell the layout ckeditor must be loaded .
?>
<div id="rightsidemain">
	<div id="rightcontentpart">
		<div id="rightsideheading" class="headingblack">
			<span style="margin: 0pt 15px 0pt 0pt; float: right;"><a class="add f-right" href="/admin/content/index/type/<?php echo $this->type;?>">Back</a></span>
			Edit Content
		</div>
		<div id="rightsidecontentpart">
		<?php
		if(isset($this->weekPhoto) && $this->weekPhoto!="") {?>
		<div><b>Photo of The Week:</b> <img src="/media/picture/home/thumb_<?php echo $this->weekPhoto;?>" width="150" height="100"/></div>
		<?php }?>
	
		<?php echo $this->form;?>
		</div>
	</div>
</div>
<script language="javascript" type="text/javascript">
document.getElementById("alias").readOnly = true;
</script>

<?php 
if($this->displayEditor==true)
{
	echo $this->setupEditor( 'body' );
}
?>
