     
    <div id="rightsidemain">
  <div id="rightcontentpart">

	<div id="rightsideheading" class="headingblack">
	
	
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
	
	<a class="add f-right" href="/admin/banner/">Back</a></span>
	Edit Banner </div>
 <div id="rightsidecontentpart">
  <?php echo $this->msg;?>
<div>Banner Image : 
<img src="/index/resize-image/path/<?php echo base64_encode($this->image_path) ?>" />
</div>
		<?php
			
			 
			echo $this->form;
		?>
  </div>
	</div>
</div>
    