<?php //echo $this->totalItemCount; ?>

<form method="post" action="<?php echo $this->seoUrl("/admin/userPrivilege/index")?>">
    <input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" alt="Search" onfocus="if(this.value=='Search...') this.value='';" onblur="if(this.value=='') this.value='Search...';"/>
    <input type="submit" value="Search" name="submit" class="button"/>
</form>
<?php if (count($this->paginator)): ?>


<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>


<table>
    <thead>
        <?php if($this->paginator->count()>1):?>
        
            <tr>
                <td colspan="7">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        
        <?php endif?>
        <tr>
            <th>S.No.</th>
            <th>screen</th>
             <th>action</th>
             <th>Menu</th>
            <th>User</th>
            
        </tr>
    </thead>
    <tbody>
        <?php 
       
        foreach ($this->paginator as $item): ?>
        <?php  $sno++?>
        <tr>
            <td><?php echo $sno?></td>
            <td><?php echo $item->screen_id;?></td>
            <td><?php echo $item->action_id; ?></a></td>
            <td><?php echo $item->menu_id; ?></td>
            <td><?php echo ucfirst($item->first_name); ?></td>
             
        </tr>
        <?php endforeach; ?>
        <?php if($this->paginator->count()>1):?>
        <tfoot>
            <tr>
                <td colspan="5">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        </tfoot>
        <?php endif?>
        
    </tbody>
</table>
<?php endif; ?>

<script>
    function deleteRoles(id){
       var params='id='+id;
       if(!confirm("Are you sure you want to delete?")){
           return false;
       }
        $.ajax({
                   type: "POST",
                   url: "/admin/user/delete-role",
                   data: params,
                   dataType:"json",
                   success: function(json)
                   {
                       $("#role_"+id).hide('slow');
                        
                   },
                   error: function (json, status, e)
                   {
                       alert("error");
                    
                   }
               });
    }
    
</script>