<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="google-site-verification" content="h2KRP3HhaPKVpnBcx-SHa2GeBx8RJtcBoCF7q5TdMjo" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome</title>
<link href="/style/temp_css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="main-landing-page">
    <div id="landing-logo"></div>
    
    <div class="landing-cmn-text">
    	Gap Daemon is coming soon.<br  /><br /><br />
        <a href="http://blog.gapdaemon.com/" class="blog-go">Gap Daemon Blog</a>In the meantime go to the<br  /><br /><br />
        I'm a Beta tester, let me log in...
        <form class="landing-page-form"  id="test_frm" name="test_frm" method="post">
		    <div class="red-error"><?php echo $this->msg?></div>
        	<label>Username</label>
            <input type="text" name="test_username" class="landing-input"/>
           	<label>Password</label>
	         <input type="password" name="test_password" class="landing-input" /><br class="clear" />
             <button onclick="document.test_frm.submit()" class="submit-blog" ></button>
    </form>
    </div>    
    </div>    
</body>
</html>
