
<script type="text/javascript">
 $(document).ready(function(){
 
 	$("#btn-slide").click(function(event) {

			event.preventDefault();
		  $("#login_box").slideToggle();
	  });
	  
	  $("#login_box").blur(function() {
	  	alert(1);
	   	//$("#login_box").slideUp(500);
	  });
 
 });

</script>



<SCRIPT TYPE="text/javascript">
<!--
function submitenter(myfield,e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   myfield.form.submit();
   return false;
   }
else
   return true;
}
//-->
</SCRIPT>














<a href="javascript:;" class="login" id="btn-slide">
	<?=$this->puts("Login")?><img src="<?echo $this->cdnUri()?>/images/login.jpg" alt=""  />
</a>

<div id="login_box"  <?php if($this->lmsg <> ""){ echo ' style="display:block"'; }?>>
	<div class="topbg"></div>
	<div class="content_box">
		<form id="frmLogin" name="frmLogin" method="post" action="/index/login">
		
		<div class="div2 aqua_green"><strong>Sign into Gap Daemon</strong></div>
		<div class="div2"><a href="<?php echo $this->seoUrl("/index/register/");?>" class="cmn_register">REGISTER</a></div>
		<div class="f_connect"><a href="<?php echo $this->loginUrl;?>" class=""><img src="<?echo $this->cdnUri()?>/images/f_connect.gif" alt="" /></a></div>
		<div class="div2"><strong>Or enter your email or password
			<div class="clear mart5 orange"><?php echo $this->lmsg?></div></strong>
		</div>
		<?php //echo $this->getRequest()->_getParam("msg")?>
		
		<?php echo $this->form->email;?>
		
		<?php echo $this->form->password;?>
		<div class="div2 mart5"><a href="#" onclick="document.frmLogin.submit()" class="cmn_register marl">SIGN IN</a> <p><input type="checkbox"><label>Remember me</label></p></div>
		<div class="div2 padb"><a href="/index/username/" class="orange">Forgot username?</a>  <a href="/index/forgot/" class="orange">Forgot password?</a></div>
			
			<!-- don not delete ( Stand by form <div class="dis_area">
				<div class="dis_pic"><div class="social_icon"><img src="<?echo $this->cdnUri()?>/images/fb.png" alt="" /></div><img src="<?echo $this->cdnUri()?>/images/2.jpg" alt="" /></div>
				<p>Hello <span>Kevin G!</span></p>
			</div>
			<div class="div1"><input type="radio" class="inpu1" name="a"><label>I am already a Gap Daemon member</label></div>
			<div class="div1"><input type="radio" class="inpu1" name="a"><label>I am new to Gap Daemon</label></div>
			<div class="div1 padb">
				<input type="text" class="inpu2" value="Enter a Username" onfocus="if( this.value=='Enter a Username') value = '';" id="keywords" onblur="if (this.value == '') this.value = 'Enter a Username';">
				<input type="text" class="inpu2" value="Email Address" onfocus="if( this.value=='Email Address') value = '';" id="keywords" onblur="if (this.value == '') this.value = 'Email Address';">
				<input type="text" class="inpu2" value="Password" onfocus="if( this.value=='Password') value = '';" id="keywords" onblur="if (this.value == '') this.value = 'Password';">
				<input type="text" class="inpu2" value="Re-enter Password" onfocus="if( this.value=='Re-enter Password') value = '';" id="keywords" onblur="if (this.value == '') this.value = 'Re-enter Password';">
			</div>
			
			<div class="div1"><strong class="padb">What is your date of birth?</strong><br class="clear">
				<select>
					<option>DD</option>
				</select>
				<select>
					<option selected="select">Month</option>
					<option>January</option>
					<option>Feburary</option>
					<option>March</option>
					<option>April</option>
					<option>May</option>
					<option>June</option>
					<option>July</option>
					<option>August</option>
					<option>September</option>
					<option>October</option>
					<option>November</option>
					<option>December</option>
				</select>
				<select>
					<option>Year</option>
				</select>
			</div>
			<div class="div1"><strong class="padt">Are you a:</strong>
			<br class="clear" />
			<input type="checkbox" class="inpu3"> <label class="padr10">Traveler</label>
			<input type="checkbox" class="inpu3"> <label>Friend of a Traveler</label><div  class="clear padb10"></div>
			<input type="checkbox" class="inpu3"> <label> I agree to the <span class="orange">Terms of Use</span></label>
		</div>							
		<input type="submit" value="REGISTER NOW" class="r_now">-->
		</form>
		
	</div>
</div>