
<!-- new slider -->


<script type="text/javascript">
  $(document).ready(function(){
    $('#new_slider').bxSlider({
            prevText: 'previous',
            nextText: 'next'
        });
  });
</script>




<ul id="new_slider">

    <li >
        <div class="featured-journal-box-home-left"><img src="http://gd.pbodev.info/media/picture/profile/thumb_profile_116.jpg?57640" alt="" width="61"></div>
        <div class="featured-journal-box-home-right">
          <h3 class="main-heading2"><a href="/journal/view-post/blog_id/24">First Impressions</a></h3>
          <div class="post-by">
              Posted by <b>
                  <a href="/Will">Will Peach</a>
              </b> | <span>
                  2 days ago              </span> | <a href="/journal/view-post/blog_id/24#blog_comments_list">Comment</a>
              |                   <a href="javascript: loginPopUp('Please login to like');">Like</a>
                          </div>
        <div class="post-by-txt"><div>
	<p>
		<img alt="" src="/images/userfiles/images/View_from_rooftop_bar_Rex.jpg" style="width: 485px; height: 363px;"></p>
	<p>
		Saigon is both ghastly and a wonderment. Motor horns pepper all hours of the day, fruit markets expand endlessly into the horizons and locals never tire of sta... <a href="/journal/view-post/blog_id/24" title="Read more">Read more</a></p></div>
		<div class="like-dislike">
			  <span class="like-dislike-l f-left" id="you-like-this-thumb-24" style="">


			  </span>
			  <span class="like-dislike-r f-left" style="float: right;">Tags: <a href="/journal/index/search-cloud/"></a>, <a href="/journal/index/search-cloud/vietnam">vietnam</a>, <a href="/journal/index/search-cloud/Ho%20Chi%20Minh%20City">Ho Chi Minh City</a>, <a href="/journal/index/search-cloud/Saigon">Saigon</a></span>
		</div>
        <div class="clear"></div>
        <a href="/journal/Will" class="orange-sml">VIEW JOURNAL</a> &nbsp;&nbsp;
				<span class="share-id-option">
			<a href="javascript://" id="share-link-dd-24" class="share-link-dd">Share It</a>
			<span style="display: none;" id="share-link-dd_menu-24" class="share-link-dd_menu">
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt=""></a>
		</span>


		</span></div>
    </div>
    </li>


      <li >
        <div class="featured-journal-box-home-left"><img src="http://gd.pbodev.info/media/picture/profile/thumb_profile_116.jpg?40813" alt="" width="61"></div>
        <div class="featured-journal-box-home-right">
          <h3 class="main-heading2"><a href="/journal/view-post/blog_id/17">New Years Eve' 2010</a></h3>
          <div class="post-by">
              Posted by <b>
                  <a href="/Will">Will Peach</a>
              </b> | <span>
                  6 days ago              </span> | <a href="/journal/view-post/blog_id/17#blog_comments_list">Comment</a>
              |                   <a href="javascript: loginPopUp('Please login to like');">Like</a>
                          </div>
        <div class="post-by-txt"><p>
	New Years Eve; no countdown no fireworks. Kind of how I like it. Vung Tau’s two stretches of dirty beach remained serene in the new hours of 2010. No-one was around, not even the big hairy rats stirred. It was low key.</p>
<p>
	Vung Tau, home to seaside scenery and hordes of weekenders... <a href="/journal/view-post/blog_id/17" title="Read more">Read more</a></p></div>
		<div class="like-dislike">
			  <span class="like-dislike-l f-left" id="you-like-this-thumb-17" style="">


			  </span>
			  <span class="like-dislike-r f-left" style="float: right;">Tags: <a href="/journal/index/search-cloud/vungtau">vungtau</a>, <a href="/journal/index/search-cloud/vietnam">vietnam</a>, <a href="/journal/index/search-cloud/party">party</a>, <a href="/journal/index/search-cloud/new%20year">new year</a></span>
		</div>
        <div class="clear"></div>
        <a href="/journal/Will" class="orange-sml">VIEW JOURNAL</a> &nbsp;&nbsp;
				<span class="share-id-option">
			<a href="javascript://" id="share-link-dd-17" class="share-link-dd">Share It</a>
			<span style="display: none;" id="share-link-dd_menu-17" class="share-link-dd_menu">
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt=""></a>
		</span>


		</span></div>
    </li>

      <li >
        <div class="featured-journal-box-home-left"><img src="http://gd.pbodev.info/media/picture/profile/thumb_profile_116.jpg?57640" alt="" width="61"></div>
        <div class="featured-journal-box-home-right">
          <h3 class="main-heading2"><a href="/journal/view-post/blog_id/24">First Impressions</a></h3>
          <div class="post-by">
              Posted by <b>
                  <a href="/Will">Will Peach</a>
              </b> | <span>
                  2 days ago              </span> | <a href="/journal/view-post/blog_id/24#blog_comments_list">Comment</a>
              |                   <a href="javascript: loginPopUp('Please login to like');">Like</a>
                          </div>
        <div class="post-by-txt"><div>
	<p>
		<img alt="" src="/images/userfiles/images/View_from_rooftop_bar_Rex.jpg" style="width: 485px; height: 363px;"></p>
	<p>
		Saigon is both ghastly and a wonderment. Motor horns pepper all hours of the day, fruit markets expand endlessly into the horizons and locals never tire of sta... <a href="/journal/view-post/blog_id/24" title="Read more">Read more</a></p></div>
		<div class="like-dislike">
			  <span class="like-dislike-l f-left" id="you-like-this-thumb-24" style="">


			  </span>
			  <span class="like-dislike-r f-left" style="float: right;">Tags: <a href="/journal/index/search-cloud/"></a>, <a href="/journal/index/search-cloud/vietnam">vietnam</a>, <a href="/journal/index/search-cloud/Ho%20Chi%20Minh%20City">Ho Chi Minh City</a>, <a href="/journal/index/search-cloud/Saigon">Saigon</a></span>
		</div>
        <div class="clear"></div>
        <a href="/journal/Will" class="orange-sml">VIEW JOURNAL</a> &nbsp;&nbsp;
				<span class="share-id-option">
			<a href="javascript://" id="share-link-dd-24" class="share-link-dd">Share It</a>
			<span style="display: none;" id="share-link-dd_menu-24" class="share-link-dd_menu">
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/24&amp;title=First%20Impressions&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt=""></a>
		</span>


		</span></div>
    </div></li>
<li >
        <div class="featured-journal-box-home-left"><img src="http://gd.pbodev.info/media/picture/profile/thumb_profile_116.jpg?40813" alt="" width="61"></div>
        <div class="featured-journal-box-home-right">
          <h3 class="main-heading2"><a href="/journal/view-post/blog_id/17">New Years Eve' 2010</a></h3>
          <div class="post-by">
              Posted by <b>
                  <a href="/Will">Will Peach</a>
              </b> | <span>
                  6 days ago              </span> | <a href="/journal/view-post/blog_id/17#blog_comments_list">Comment</a>
              |                   <a href="javascript: loginPopUp('Please login to like');">Like</a>
                          </div>
        <div class="post-by-txt"><p>
	New Years Eve; no countdown no fireworks. Kind of how I like it. Vung Tau’s two stretches of dirty beach remained serene in the new hours of 2010. No-one was around, not even the big hairy rats stirred. It was low key.</p>
<p>
	Vung Tau, home to seaside scenery and hordes of weekenders... <a href="/journal/view-post/blog_id/17" title="Read more">Read more</a></p></div>
		<div class="like-dislike">
			  <span class="like-dislike-l f-left" id="you-like-this-thumb-17" style="">


			  </span>
			  <span class="like-dislike-r f-left" style="float: right;">Tags: <a href="/journal/index/search-cloud/vungtau">vungtau</a>, <a href="/journal/index/search-cloud/vietnam">vietnam</a>, <a href="/journal/index/search-cloud/party">party</a>, <a href="/journal/index/search-cloud/new%20year">new year</a></span>
		</div>
        <div class="clear"></div>
        <a href="/journal/Will" class="orange-sml">VIEW JOURNAL</a> &nbsp;&nbsp;
				<span class="share-id-option">
			<a href="javascript://" id="share-link-dd-17" class="share-link-dd">Share It</a>
			<span style="display: none;" id="share-link-dd_menu-17" class="share-link-dd_menu">
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=facebook&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Facebook"><img src="/images/facebook-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=twitter&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Twitter"><img src="/images/twitter-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=delicious&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Social"><img src="/images/social_03.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=digg&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Digg This"><img src="/images/digg-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=google&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Google"><img src="/images/gmail-icon-sml.png" alt=""></a>
			<a href="//www.addthis.com/bookmark.php?pub=jhuskisson&amp;v=250&amp;source=tbx-250&amp;tt=0&amp;s=stumbleupon&amp;url=http://gd.pbodev.info/journal/view-post/blog_id/17&amp;title=New%20Years%20Eve%27%202010&amp;content=&amp;lng=en" target="_blank" title="Send to Stumbleupon"><img src="/images/stumbleupon-icon-sml.png" alt=""></a>
		</span>


		</span></div>
    </li>
</ul>