<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	
	<?php echo $this->title ?></div>
		
		<div id="rightsidecontentpart">
		<span style='color:red'><?php echo $this->msg?></span>
			<?php echo $this->form?>
		</div>
	</div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
