<?php 
		/*-------Fetch work categories ------*/
			$categoryM=new Application_Model_Category();
			$workCats=$categoryM->getCategory(null, 'work');
		
		/*------------------------------------*/
		/*-------Fetch Study categories ------*/
			$categoryM=new Application_Model_Category();
			$studyCats=$categoryM->getCategory(null, 'study');
		/*------------------------------------*/	
		/*-------Fetch volunteer categories ------*/
			$categoryM=new Application_Model_Category();
			$volunteerCats=$categoryM->getCategory(null, 'volunteer');
		/*------------------------------------*/
?>

<div class="right-box-wide">
	<h2 class="box-heading">MORE CATEGORIES</h2>
	
	
	<?php if(count($workCats)>0){?>
	<h3>Work</h3>
	<ul class="journal-cat-list-right">
		<?php foreach($workCats as $id=>$_category){?>
		<li><a href="<?php echo $this->seoUrl("/work-study-volunteer/detail/id/$id")?>"><?php echo $_category?></a></li>
		<?php }?>
	</ul>
	<?php }?>
	
	<?php if(count($studyCats)>0){?>
	<h3>Study</h3>
	<ul class="journal-cat-list-right">
		<?php foreach($studyCats as $id=>$_category){?>
		<li><a href="<?php echo $this->seoUrl("/work-study-volunteer/detail/id/$id")?>"><?php echo $_category?></a></li>
		<?php }?>
	</ul>
	<?php }?>
	
	<?php if(count($volunteerCats)>0){?>
	<h3>Volunteer</h3>
	<ul class="journal-cat-list-right">
		<?php foreach($volunteerCats as $id=>$_category){?>
		<li><a href="<?php echo $this->seoUrl("/work-study-volunteer/detail/id/$id")?>"><?php echo $_category?></a></li>
		<?php }?>
	</ul>
	<?php }?>
</div>