<div id="main-left">
 <h2 class="main-heading">JOURNALS</h2>

<div class="create-your-journal">
	<?php
	//select Home page content
	$homeText1	=	"";
	$homeText2	=	"";
	
	$JournalHomeM	=	new Application_Model_JournalHome();
	$modelRes		=	$JournalHomeM->find(1);
	if(false!==$modelRes)
	{
		$homeText1	=	$modelRes->getLogoutText1();
		$homeText2	=	$modelRes->getLogoutText2();
		if($this->userId!="")
		{
			$homeText1	=	$modelRes->getLoginText1();
			$homeText2	=	$modelRes->getLoginText2();			
		}
	}
	?>
	<p><?php echo $homeText1;?></p>
	<div class="create-journal-buttons">
		<div class="create-journal-button-con">
		<?php if($this->userId==""){?>
		<a href="<?php echo $this->seoUrl("/index/register");?>" class="button-link">CREATE ACCOUNT</a> <?php echo $homeText2;?>
		<?php }else{?>
		<a href="/gapper/create-blog" class="button-link">ADD NEW POST</a> <?php echo $homeText2;?>
		<?php }?>
		</div>		
	</div>
</div>
<?php echo $this->partial('journal/features.phtml', array('data_fea'=>$this->data_fea, 'userId'=>$this->userId)) ?>

<div class=""></div>
<h2 class="main-heading">LATEST JOURNALS</h2> 

<!-- blogs -->

<?php echo $this->partial('journal/blogs.phtml', array('data'=>$this->data, 'userId'=>$this->userId)) ?>


<div class="clear"></div>
<span style="display: none;" id="loading">
    <img alt="" src="<?php echo $this->cdnUri()?>/images/loading.gif">
</span>
<?if(count($this->data)>0){?>
<a id="show-more-link" href="javascript: moreBlogs()" class="button-link">Show More</a>
<?}?>
<!-- blogs -->
</div>
<script language="javascript">
var page=2;
function moreBlogs()
{
    $("span#loading").show();
      $("#show-more-link").hide();

    var params='';
    var jrnl = $("#search-jrnl").val();
    var city = $("#search-city").val();
    var filt = $("#search-filtr").val();
    var tags = $("#search-cloud").val();
    params+="page="+page+"&mode=ajax&search-jrnl="+jrnl+"&search-city="+city+"&search-filtr="+filt+"&search-cloud="+tags;
    page=page+1;
    $.ajax({
               type: "POST",
               url: "/journal/blogs/",
               data: params,
               dataType: "html",
               success: function(html){

                $("span#loading").hide();
                $("#show-more-link").show();

                    if(html=="nodata"){
                        $("#show-more-link").hide();
                        $("#blogs").append("No more journals found.");
                    }else{
                        $("#blogs").append(html);

                    }

               },
               error: function (json, status, e){
                            alert(e+json+status);
                    }
     });
}


function like(item_id,vote)
{
	var params='';
	params+="vote="+vote;
	params+="&item_id="+item_id;
	params+="&item_type=blog";
	$("span#like_"+item_id).hide();
    $("span#loading_"+item_id).show();
	
	//featured journal
	$("span#featured_like_"+item_id).hide();
	$("span#featured_loading_"+item_id).show();
	
	$.ajax({
			type: "POST",
			url: "/vote/do-vote/",
			data: params,
			dataType: "json",
			success: function(json)
			{
			if(json.error==1)
			{
				alert(json.msg);
			}
			else if(json.error==2)
			{
				$("span#loading_"+item_id).hide();
				$("#comment-main-"+item_id).show();
				
				//featured journal
				$("span#featured_loading_"+item_id).hide();
				
				if(vote==1)
				{
					$("span#unlike_"+item_id).show();
					$("span#like_"+item_id).hide();
					$("#you-like-this-"+item_id).show();
					$("#you-like-this-thumb-"+item_id).show();
					
					//featured journal
					$("span#featured_unlike_"+item_id).show();
					$("span#featured_like_"+item_id).hide();
					$("#featured_you_like_this_"+item_id).show();
					$("#featured_you_like_this_thumb-"+item_id).show();
				}
				else
				{
					$("span#unlike_"+item_id).hide();
					$("span#like_"+item_id).show();
					$("#you-like-this-"+item_id).hide();
					$("#you-like-this-thumb-"+item_id).hide();
					
					//featured journal
					$("span#featured_unlike_"+item_id).hide();
					$("span#featured_like_"+item_id).show();
					$("#featured_you_like_this_"+item_id).hide();
					$("#featured_you_like_this_thumb-"+item_id).hide();
				}
				
				/*
				if(json.total_up>0)
				{
					$("#you-like-this-thumb-"+item_id).show();                               
				}
				else
				{
					$("#you-like-this-thumb-"+item_id).hide();
				}
				*/
				/*
				if(json.total_up>1)
				{
					$("span#total_likes_"+item_id).html(json.total_up + " members like this");
					$("span#total_likes_left_"+item_id).html(json.total_up + " members like this");
				}
				else
				{
					$("span#total_likes_"+item_id).html(json.total_up + " member likes this");
					$("span#total_likes_left_"+item_id).html(json.total_up + " member likes this");
				}*/
				
				//display main DIV and other as per user vote and total likes
				if(vote==1)
				{
					$("div#journal_tag_div_"+item_id).show();
					//$("div#journal_tag_div_"+item_id).addClass('like-dislike-img');
					
					//if Tags are available then display seperator
					if($("span#journal_tag_str_"+item_id).html()!=null)
					{
						$("span#journal_tag_sep_"+item_id).show();
					}
					
					//featured journal
					$("div#featured_journal_tag_div_"+item_id).show();
					$("div#featured_journal_tag_div_"+item_id).addClass('like-dislike-img');
					if($("span#featured_journal_tag_str_"+item_id).html()!=null)
					{
						$("span#featured_journal_tag_sep_"+item_id).show();
					}				
				}
				else
				{
					if(json.total_up==0)
					{
						$("span#journal_tag_sep_"+item_id).hide();
						//if Tags are not available then hide main DIV
						if($("span#journal_tag_str_"+item_id).html()==null)
						{
							$("div#journal_tag_div_"+item_id).hide();
						}
						
						//featured journal
						$("span#featured_journal_tag_sep_"+item_id).hide();
						//if Tags are not available then hide main DIV
						if($("span#featured_journal_tag_str_"+item_id).html()==null)
						{
							$("div#featured_journal_tag_div_"+item_id).hide();
						}
					}
				}
				
				if(json.total_up>1)
				{
					$("span#total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_plural");?>");
					
					//featured journal
					$("span#featured_total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_plural");?>");
				}
				else if(json.total_up==1)
				{
					$("span#total_likes_"+item_id).show();
					$("span#total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_singular");?>");
					
					//featured journal
					$("span#featured_total_likes_"+item_id).show();
					$("span#featured_total_likes_"+item_id).html(json.total_up + " <?php echo $this->language("like_singular");?>");
				}
				else
				{
					$("span#total_likes_"+item_id).hide();
					$("span#total_likes_"+item_id).html(json.total_up);
					
					//featured journal
					$("span#featured_total_likes_"+item_id).hide();
					$("span#featured_total_likes_"+item_id).html(json.total_up);
				}
			  }
			},
			error: function (json, status, e){

			}
	 });
}
function showCommentBox(item_id)
{
     $("#comment-main-"+item_id).show();
}
function blogComment(item_id, blogUserId)
{
	var comment = $("#blog-comment-"+item_id).val();
	if(comment == "" || comment == "Comment...")
	{
	  alert("Please enter comment");
	  $('#blog-comment-'+item_id).focus();
	  return false;	
	}
	
    var params='';
	params+="comment="+escape($("#blog-comment-"+item_id).val());
	params+="&item_id="+item_id;
	params+="&user_id="+blogUserId;
	params+="&item_type=blog";
	//$("span#like_"+item_id).hide();
        $("span#comment_loading_"+item_id).show();
        $("#saveComment_"+item_id).hide();
	$.ajax({
		   type: "POST",
		   url: "/comment/save-journal-comment/",
		   data: params,
		   dataType: "html",
		   success: function(html){

                    $("#saveComment_"+item_id).show();
                    $("span#comment_loading_"+item_id).hide();
                    $("#comment-list-"+item_id).append(html);
                    $("#blog-comment-"+item_id).val('Comment...');
		   },
		   error: function (json, status, e){

			}
	 });
}



function likeComment(item_id,vote)
{
	var params='';
	params+="vote="+vote;
	params+="&item_id="+item_id;
	params+="&item_type=blog_comment";
	$("span#like_"+item_id).hide();
        $("span#loading_comment_"+item_id).show();
	$.ajax({
		   type: "POST",
		   url: "/vote/do-vote/",
		   data: params,
		   dataType: "json",
		   success: function(json){
			if(json.error==1)
			{
				alert(json.msg);
			}
			else if(json.error==2)
			{
					$("span#loading_comment_"+item_id).hide();
					if(vote==1){
						$("span#unlike_comment_"+item_id).show();
						$("span#like_comment_"+item_id).hide();
						$("#you-like-this-comment-"+item_id).show();
						$("#you-like-comment-"+item_id).show();

					}else{
						$("span#unlike_comment_"+item_id).hide();
						$("span#like_comment_"+item_id).show();
						$("#you-like-this-comment-"+item_id).hide();
						$("#you-like-comment-"+item_id).hide();
					}

						if(json.total_up>0)
						{
							$("#you-like-this-comment-"+item_id).show();
						}
						else
						{
							$("#you-like-this-comment-"+item_id).hide();
						}

						if(json.total_up>1)
						{
							$("span#total_likes_comment_"+item_id).html(json.total_up + " <?php echo $this->language("like_plural");?>");
						}
						else
						{
							$("span#total_likes_comment_"+item_id).html(json.total_up + " <?php echo $this->language("like_singular");?>");
						}
				}
		   },
		   error: function (json, status, e){

			}
	 });
}

</script>
