<?php $this->mapLib(null, "true")->setGear();?>


<script language="javascript" type="text/javascript">
var siberia = new google.maps.LatLng(60, 105);
var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
var initialLocation;
function updateGapperLocation(latLng)
{
    var address = $('#address').val();
    $("#dialog-confirm").dialog({
			resizable: false,
			modal: false			
		});
   $("input#checkin-address").val(address);
}

function doUpdate()
{
    var latLng=marker.getPosition();
    saveLocationInDatabase(latLng.lat(),latLng.lng());
}

function doCancel()
{
    $("#dialog-confirm").dialog('close');
}

function acknowledgeMessage()
{
    plotMyJourney();
    $("#dialog-message").dialog('close');
}

function saveLocationInDatabase(lat, lng)
{
    var params="longitude="+lng+"&latitude="+lat+"&address="+$("#address").val();
    $("#loading-location").show();
    $.ajax({
           type: "POST",
           url: "/gapper/update-my-location/",
           data: params,
           dataType: "json",
           success: function(json){
				if(json.error==0)
				{
					$("#loading-location").hide();
					$("#coordinate_span").html($("#address").val());
					$("#dialog-message").dialog({
							modal: false,
							resizable: false						   
					});
					$("#dialog-confirm").dialog('close')
					//alert("Your location has been updated successfully.");
				}
				else
				{
					$("#loading-location").hide();
					alert("failed to update your location");
				}
           },
           error: function (json, status, e){

                }
    });
}

//* Global variable declaration
var geocoder = new google.maps.Geocoder();
var marker=null;
var map =null;
var point="/images/point-blue.png";
var infoWindow = new google.maps.InfoWindow();
function buildMap(latLng)
{
    map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

     
  marker = new google.maps.Marker({
    position: latLng,
    title: 'Double Click to set your current location here.',
    map: map,
    icon : point,
    draggable: true
  });
    geocodePosition(latLng);
    addingEventListnerToMaker(marker);
    //var content = '<div class="where-iam-info"><div class="section1"><img src="/image?src=<?php echo $this->userThumb;?>&size=journal"></div><div class="section2"><b><?php echo $this->fullName;?></b></div></div>';
	var content = "<div class='where-iam-info'><div class='section1'><img src='/image?src=<?php echo $this->userThumb;?>&size=journal'></div><div class='section2'><b><?php echo addslashes($this->fullName);?></b></div></div>";
    smartInfo(content, marker,'click');
    plotMyFriends();
}


function buildMap2(latLng)
{
	map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });


  marker = new google.maps.Marker({
    position: latLng,
    title: 'Double click to set your current location here.',
    map: map,
    icon : point,
    draggable: true
  });
    geocodePosition(latLng);
    addingEventListnerToMaker(marker);
    var content="<div><img src='/image?src=<?php echo $this->userThumb;?>&size=journal' /> <?php echo addslashes($this->fullName);?></div>";
    smartInfo(content, marker,'click');
}

function smartInfo(content, marker, eventName)
{	
    google.maps.event.addListener(map, 'click', function()
	{
		infoWindow.close();
	});
    google.maps.event.addListener(marker, eventName, function(e){    
    infoWindow.setContent(content);
	infoWindow.close();   
    infoWindow.open(map, marker);
    });

    google.maps.event.addListener(map, 'click', function(e) {
    infoWindow.close();    
    });
}
function expandMap()
{
    $("#show-map").hide();
    $("#close-map").show();
    $("#map_canvas").css("height", "500px");
    var latLng=marker.getPosition();
    buildMap(latLng);
}

function shrinkMap()
{
    $("#show-map").show();
    $("#close-map").hide();
    $("#map_canvas").css("height", "300px");
    var latLng=marker.getPosition();
    buildMap(latLng);
}
function toggleClass(cssClass)
{
    
}



function removeDestination(id)
{
	if(!confirm("Are you sure you want to delete this location?"))
	return false;
    
	var param="id="+id;
    $.ajax({
           type: "POST",
           url: "/gapper/remove-destination/",
           data: param,
           dataType: "json",
           success: function(json){
                    if(json.error==0)
                    {
                        plotMyJourney();
                    }
                    else
                    {
                         alert("Error");
                    }
           },
           error: function (json, status, e){
                    alert(json + status)

                }
    });
}
function plotMyJourney()
{
    var params = "userId=<?php echo $this->userId ?>";
     $.ajax({
           type: "POST",
           url: "/profile/get-my-journey/",
           data : params,
           dataType: "json",
           success: function(json){
                    if(json.error==0)
                    {
                        $("#map_canvas").css("height", "500px");
                        $("#show-map").hide();
                        $("#close-map").show();
                        var latLng = new google.maps.LatLng(json.coord[0].lat,json.coord[0].lng);
                        buildMap2(latLng);
                        
                        var polyOptions = {
                        strokeColor: '#348698',
                        strokeOpacity: 1.0,
                        strokeWeight: 4
                        }
                        var poly = new google.maps.Polyline(polyOptions);
                        poly.setMap(map);
                        var path = poly.getPath();
                        var latiLongi=null;
                        var image="/images/point-blue.png";
                        for(i=0;i<json.coord.length;i++)
                        {
                           
                            
                            latiLongi=new google.maps.LatLng(json.coord[i].lat, json.coord[i].lng);
                            
                            path.push(latiLongi);
                            var marker1 = new google.maps.Marker({
                                position: latiLongi,
                                title: 'Destination #' + path.getLength(),
                                map: map,
                                icon : image
                              });
                              //var content = '<div class="where-iam-info"><div class="section1"><img src="/image?src=<?php echo $this->userThumb;?>&size=journal"></div><div class="section2"><b><?php echo $this->fullName;?></b><br>Destination #'+ path.getLength()+'<br />Click <a href="javascript://" onclick="removeDestination('+json.coord[i].id+')">here</a> to remove this destination.</div></div>';
							  var content = "<div class='where-iam-info'><div class='section1'><img src='/image?src=<?php echo $this->userThumb;?>&size=journal'></div><div class='section2'><b><?php echo addslashes($this->fullName);?></b><br>Destination #"+ path.getLength()+"<br />Click <a href='javascript://' onclick='removeDestination("+json.coord[i].id+")'>here</a> to remove this destination.</div></div>";
                              smartInfo(content, marker1,'click');
                                
                              if(image=="/images/point-blue.png")
                              image="/images/point-green.png";
                        }
                    }
                    else
                    {
                         alert("You don't have any coordinate.");
                    }

           },
           error: function (json, status, e){
                    alert(json + status)

                }
    });   
}

function plotMyFriends()
{
    var image="/images/point-green.png";
    var friendLatiLongi="";
    <?php
    if($this->loc!=false)
	{
		foreach($this->loc as $_people)
		{
			$member_user_id = $_people['user_id'];
			$member_first_name = addslashes($_people['firstName']);
			$member_full_name = addslashes($_people['firstName']." ".$_people['lastName']);
			$member_thumbnail = $_people['thumbnail'];
			$member_address = addslashes($_people['address']);
	?>
	friendLatiLongi=new google.maps.LatLng(<?php echo $_people['latitude']?>, <?php echo $_people['longitude']?>);

	var marker1 = new google.maps.Marker({
	position: friendLatiLongi,
	title: "Member name: <?php echo $member_full_name;?>",
	map: map,
    icon : image
	});
    var addr =friendLatiLongi;
    //var content = '<div class="where-iam-info"><div class="section1"><img src="/image?src=<?php echo $_people['thumbnail'];?>&size=journal"></div><div class="section2"><b><?php echo $_people['firstName']?> <?php echo $_people['lastName']?></b><br/><?php echo $_people['address']?><br /><a href="/gapper/my-messages/username/<?php echo base64_encode($_people['user_id']);?>">Send <?php echo $_people['firstName']?> a message</a></div></div>';
	var content = "<div class='where-iam-info'><div class='section1'><img src='/image?src=<?php echo $member_thumbnail;?>&size=journal'></div><div class='section2'><b><?php echo $member_full_name;?></b><br /><?php echo $member_address;?><br /><a href='/gapper/my-messages/username/<?php echo base64_encode($member_user_id);?>'>Send <?php echo $member_first_name;?> a message</a></div></div>";

	smartInfo(content, marker1,'click');
	<?php
		}//end foreach
    }//end if
    ?>
}

function locateMe()
{
	  if(navigator.geolocation) {
              
	    browserSupportFlag = true;
	    navigator.geolocation.getCurrentPosition(function(position) {
	      initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
	      contentString = "Location found using W3C standard";
	      //map.setCenter(initialLocation);
              //alert(initialLocation);
	      buildMap(initialLocation);
	    }, function() {
	      handleNoGeolocation(browserSupportFlag);
	    });
	  } else if (google.gears) {
	    // Try Google Gears Geolocation
	    browserSupportFlag = true;
	    var geo = google.gears.factory.create('beta.geolocation');
	    geo.getCurrentPosition(function(position) {
	      initialLocation = new google.maps.LatLng(position.latitude,position.longitude);
	      contentString = "Location found using Google Gears";
	      //map.setCenter(initialLocation);
	      buildMap(initialLocation);
	      
	    }, function() {
	      handleNoGeolocation(browserSupportFlag);
	    });
	  } else {
	    // Browser doesn't support Geolocation
	    browserSupportFlag = false;
	    handleNoGeolocation(browserSupportFlag);
	  }
}


function handleNoGeolocation(errorFlag) {

	  if (errorFlag == true) {
	    initialLocation = newyork;
	    contentString = "Error: The Geolocation service failed.";
	  } else {
	    initialLocation = siberia;
	    contentString = "Error: Your browser doesn't support geolocation. Are you in Siberia?";
	  }
            contentString="We are unable to locate you on map. You are being located to the London, England";
            alert(contentString);

            var latLng = new google.maps.LatLng("51.5001524", "-0.1262362");
            buildMap(latLng);
           // buildMap(latLng);
          ///alert(initialLocation);
         // map.setCenter(initialLocation);
}

function geocodePosition(pos)
{
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}


function updateMarkerAddress(str) {
  document.getElementById('address').value = str;
  $("#checkin-address").val(str);
}

function searchAddress(txtBoxId)
{
    //var query = document.getElementById('address').value;
    var query = $("#"+txtBoxId).val();
   
    var request={ 'address': query };

    geocoder.geocode(request, locateDestination);
}

function locateDestination(results, status) {
     if (status == google.maps.GeocoderStatus.OK){
     
     //buildMap(results[0].geometry.location);
     shrinkMap()
     resetMap();
    marker = new google.maps.Marker({
    position: results[0].geometry.location,
    title: 'Double Click here to set your current location.',
    map: map,
    draggable: true
  });

    //map.panTo(marker.getPosition());
    //addingEventListnerToMaker(marker);
    buildMap(results[0].geometry.location);
     }else{
         alert("Unable to locate. Please try some other keyword.");
     }
}

function resetMap() {

  if (marker != null) {
    marker.setMap(null);
    marker= null;
  }


}

function initialize()
{
    var myLatitude='<?php echo $this->myLatitude?>';
	var myLongitude='<?php echo $this->myLongitude?>';
	if(myLatitude=="" || myLongitude=="")
	{
		locateMe();
    	return false;
	}
	
  	var latLng = new google.maps.LatLng(myLatitude, myLongitude);
    buildMap(latLng);
    geocodePosition(latLng);
    addingEventListnerToMaker(marker);
     
}

function addingEventListnerToMaker(marker)
{
     // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {
      
    updateMarkerAddress('Wait...');


  });

  google.maps.event.addListener(marker, 'dragend', function() {
      
    geocodePosition(marker.getPosition());

  });

  google.maps.event.addListener(marker, 'dblclick', function() {
    updateGapperLocation(marker.getPosition());
  });
}
// Onload handler to fire off the app.
<?
if($this->addedon=="")
{
?>
    google.maps.event.addDomListener(window, 'load', locateMe);
<?
}
else
{
        //locate me if my location if older than 24 hours.
        $current_time_stamp=time();
        $addedon_time_stamp=$this->addedon;
        $diff_time_stamp=$current_time_stamp=$addedon_time_stamp;
        $Date=new Base_Date();
        $hours=$Date->hourAgo($diff_time_stamp);
        if($hours>24)
        {
            ?>
                google.maps.event.addDomListener(window, 'load', locateMe);
            <?
        }else{
            ?>
                google.maps.event.addDomListener(window, 'load', initialize);
            <?
        }
}
?>

</script>
<div class="location">
		<a  id="my_location" href="javascript:void(0);" onclick="shrinkMap(); $('#my_location').removeClass('grey'); $('#my_location').addClass('blue');$('#my_journey').removeClass('blue'); $('#my_journey').addClass('grey'); " class="blue">MY LOCATION</a>
		<a id="my_journey" href="javascript:void(0);" onclick="plotMyJourney();  $('#my_location').removeClass('blue'); $('#my_location').addClass('grey');$('#my_journey').removeClass('grey'); $('#my_journey').addClass('blue');" class="grey">MY GAP JOURNEY</a>
        
        <div class="f-right show-hide-map">
           
                <a id="show-map" href="javascript:void(0);" onclick="expandMap()" ><?php echo $this->puts('SHOW MAP')?></a>
                <a id="close-map" href="javascript:void(0);" onclick="shrinkMap()" style="display:none"><?php echo $this->puts('HIDE MAP')?></a>
       
    	</div>
</div>
<div id="dialog-confirm" class="ui-dialog" title="" style="display:none">	
    <!-- pop up start -->
    <div id="login_box1" >
      <div class="topbg"></div>
      <div class="content_box" >
            <form id=""  action="" method="post">
        <div class="div2 aqua_green"><strong>Please Confirm</strong></div>
        <p>
            <input type="text" name="checkin-address" id="checkin-address" value="" />
            <input type="button" onclick="searchAddress('checkin-address')" value="Search">
        </p>
          <div id="login_error_msg" class="div2 clear mart5 orange"><strong></strong></div>

          <div class="input-field">
            <label class="required" for="email">This location will be set as your current location. Are you sure? </label>
          </div>
          <br class="clear" />

          <div class="div2 mart5">
              <a class="cmn_register marl"  href="javascript: doUpdate();">UPDATE</a>
              <a class="cmn_register marl"  href="javascript: doCancel();">CANCEL</a>
          </div>
          <p><span id="loading-location" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif"/></span></p>
        </form>
      </div>
    </div>
    <!-- pop up ends -->
</div>

<div id="dialog-message" class="ui-dialog" title="" style="display:none">
<!--update pop up start -->
<div id="login_box1" >
  <div class="topbg"></div>
  <div class="content_box">
	<form id=""  action="" method="post"> 
    <div class="div2 aqua_green"><strong>Confirmation</strong></div>
      <div id="login_error_msg" class="div2 clear mart5 orange"><strong></strong></div>

      <div class="input-field">
        <label class="required"><strong>You have successfully updated your current location.</strong>
	  	  <br class="clear" /><br class="clear" />
        <strong class="aqua_green">You current location is</strong> : <hr /> <p><strong><span id="coordinate_span" > </span>.</strong></p></label>
      </div>
       <br class="clear" />
      <div class="div2 mart5">
	  <a class="cmn_register marl"  href="javascript: acknowledgeMessage();">Ok</a>
      </div>
	  <br class="clear" /><br class="clear" />
    </form>
  </div>
</div>
<!--update pop up ends -->
</div>

<div class="where_map">
<div id="map_canvas" style="width: 815px; height: 300px" class="f-left"></div>
<div class="update-location">
	<span class="blue">UPDATE MY LOCATION :</span>
    <span><input type="text"  name="address"  id="address" value="" >
	<input type="button" value="Search" onclick="searchAddress('address')" >
	<input type="button" value="Check In" onclick="updateGapperLocation(marker.getPosition())" >
	</span>
	<!-- Publish Location START HERE -->
	<span class="blue">PUBLISH</span>
		<?php
		$UserPermissionObj	= new Application_Model_UserPermission();
		$wherePerCond		= "user_id='{$this->userId}' AND permission_id=3";
		$mapPermission		= $UserPermissionObj->fetchRow($wherePerCond);
		$permissionId		= $mapPermission->getId();
		$mapPermission		= $mapPermission->getFriendGroupId();
		?>
		<span class="share-id-option_wim"><a href="javascript://" id="publish-link-dd" class="share-link-dd">Public</a>
		<span id="publish-link-dd_menu"  class="share-link-dd_menup_wim">
		<span class="my-location-sub-head">Share My Gap Daemon Journey with</span><br />
		<form name="frmLocationPermission" id="frmLocationPermission" method="post">
		<?php
		$FriendGroupObj = new Application_Model_FriendGroup();
		$FriendGroup	= $FriendGroupObj->fetchAll();
		foreach($FriendGroup AS $group)
		{
			//$chk_status = ($mapPermission==$group->getId())?"checked='checked'":"";
			$chk_status = "";
			if($mapPermission==$group->getId())
			{
				$chk_status = "checked='checked'";
				echo "<script>document.getElementById('publish-link-dd').innerHTML='".$group->getName()."';</script>";
			}
		?>
		<label><input type="radio" name="friend_group_id" value="<?php echo $group->getId();?>" <?php echo $chk_status;?>> <?php echo $group->getName();?></label><br />
		<?php }?>
		<input type="hidden" name="set_permission_txt" value="">
		<input type="button" value="Update" onclick="updateMapPermission(<?php echo $permissionId;?>)" class="update-btn-wim" >
		</form>
		</span>
	</span>
	<span id="location_perm_resp"></span>
	<script type="text/javascript">
	$(document).ready(function()
	{
		$("#publish-link-dd_menu").hide();
		$("#publish-link-dd").click(function(e)
		{
			e.preventDefault();
			$("#publish-link-dd_menu").toggle("slow");
			$("#publish-link-dd").toggleClass("menu-open");
		});
		
		$("#publish-link-dd_menu").mouseup(function()
		{
			return false;
		});
	});
	
	function updateMapPermission(perm_id)
	{
		for (var i=0; i < document.frmLocationPermission.friend_group_id.length; i++)
		{
			if (document.frmLocationPermission.friend_group_id[i].checked)
			{
				var friend_group_id = document.frmLocationPermission.friend_group_id[i].value;
			}
		}
		$("#location_perm_resp").show();
		$("#location_perm_resp").html("<img src='/images/ajax-loader.gif'>");
		var params="mode=ajax&perm_id="+perm_id+"&friend_group_id="+friend_group_id;
		$.ajax({
			   type: "POST",
			   url: "/gapper/update-location-permission/",
			   data: params,
			   dataType: "json",
			   success: function(json){
				$("#location_perm_resp").html(json.msg);
				$("#publish-link-dd").html(json.set_permission);
				$("#publish-link-dd_menu").hide();
				RAVIN_DelayedHide("location_perm_resp");
			   },
			   error: function (json, status, e){
					//alert("Json=>"+json+" status=>"+status+" Error="+e);
					alert("Error Occured=>"+e);
			   }
		});
	}
	</script>
	<!-- Publish Location END HERE -->	
</div>
</div>
<div class="clear"></div>
<!-- google map ends -->






<!-- status update starts  (My Travel Wall)-->
<?php echo $this->partial('gapper/my-travel-wall.phtml', array('section_to_display'=>"where-i-am")) ?>


<!-- My travel wall ends -->


