<!-- top section starts -->



<div class="location"><a href="#" class="blue">MY LOCATION</a>      <a href="#" class="red">MY GAP JOURNEY</a></div>


<!-- google map starts -->
<?php $this->mapLib();?>


<script type="text/javascript">


function updateGapperLocation(latLng){


    $("#dialog-confirm").dialog({
			resizable: false,

			modal: true,
			buttons: {
				'Update': function() {
                                        saveLocationInDatabase(latLng.lat(),latLng.lng());
				},
				Cancel: function() {
					$(this).dialog('close');
				}
			}
		});

}

function saveLocationInDatabase(lat, lng)
{
    var params="longitude="+lng+"&latitude="+lat;
    $("#loading-location").show();
    $.ajax({
           type: "POST",
           url: "/gapper/update-my-location/",
           data: params,
           dataType: "json",
           success: function(json){
                        if(json.error==0)
                        {

                            $("#loading-location").hide();
                         $("#coordinate_span").html("Longitude : "+lng + "<br>Latitude : " + lat);
                         $("#dialog-message").dialog({
                                    modal: true,
                                    resizable: false,
                                    buttons: {
                                            Ok: function() {
                                                    $(this).dialog('close');
                                            }
                                    }
                            });
                            $("#dialog-confirm").dialog('close')
                         //alert("Your location has been updated successfully.");
                        }
                        else
                        {
                        $("#loading-location").hide();
                            alert("failed to update your location");
                        }

           },
           error: function (json, status, e){


                }
    });
  // $("#dialog-confirm").dialog('close');
}

var geocoder = new google.maps.Geocoder();
var marker=null;
var map =null;
function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}


function updateMarkerAddress(str) {
  document.getElementById('address').value = str;
  //document.getElementById('address_div').innerHTML = str;
}

function searchAddress()
{
    var query = document.getElementById('address').value;
    var request={ 'address': query };

     //resetMap();

 
  if (request.latLng) {
    marker = new google.maps.Marker({
      'position': request.latLng,
      'map': map,
      'title': request.latLng.toString(),
      'clickable': false,
      'icon': clickIcon,
      'shadow': shadow
    });
   
  }

  geocoder.geocode(request, locateDestination);
}

function locateDestination(results, status) {
    marker = new google.maps.Marker({
    position: results[0].geometry.location,
    title: 'Click here to set your current location.',
    map: map,
    draggable: true
  });

addingEventListerToMarker(marker);
    map.panTo(marker.getPosition());
    
}

function resetMap() {

  if (marker != null) {
    marker.setMap(null);
    marker= null;
  }
}

function initialize()
{
  var latLng = new google.maps.LatLng(<?php echo $this->myLatitude?>, <?php echo $this->myLongitude?>);
  map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  marker = new google.maps.Marker({
    position: latLng,
    title: 'Click here to set your current location.',
    map: map,
    draggable: true
  });


    geocodePosition(latLng);
    addingEventListerToMarker(marker);
 
}


function addingEventListerToMarker(marker)
{
    alert('test');
  // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {
    updateMarkerAddress('Wait...');
  });

  google.maps.event.addListener(marker, 'dragend', function() {
    geocodePosition(marker.getPosition());
  });

  google.maps.event.addListener(marker, 'click', function() {
    updateGapperLocation(marker.getPosition());
  });
}
// Onload handler to fire off the app.
//
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="dialog-confirm" title="Please Confirm..." style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
            This location will be set as your current location. Are you sure?</p>
        
        <p><span id="loading-location" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif"/></span></p>
</div>

<div id="dialog-message" title="Confirmation" style="display:none">
	<p>
		<span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
		You have successfully updated your current location.
	</p>
	<p>
		You current location is : <br> <b><span id="coordinate_span"> </span></b>.
	</p>
</div>


<div class="where_map">
<div id="map_canvas" style="width: 815px; height: 201px" class="f-left"></div>



<div class="update-location"><img src="<?echo $this->cdnUri()?>/images/show-btn.jpg" class="f-left" alt="" /><span class="red"><a href="#" class="red">Show Map</a></span>
    <span class="blue space-l">UPDATE MY LOCATION :</span>
    <span><input type="text"  name="address"  id="address" value="" >
<input type="button" value="Search" onclick="searchAddress()" ></span></div>
</div>
<div class="clear"></div>

<!-- google map ends -->




<!-- status update starts -->

<style type="text/css">

label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
<script type="text/javascript">
  $(document).ready(function(){

	  $("#status").focus(function(){$("span#msg").hide();});

    $("#commentForm").validate({
 	   submitHandler: function(form) {
	    	var params=$(form).serialize();
	    	$("span#loading").show();
	    	$("span#msg").hide();
	    	$("#share").hide();
	    	$.ajax({
	    		   type: "POST",
	    		   url: "/gapper/my-travel-wall/",
	    		   data: params,
	    		   dataType: "json",
	    		   success: function(json){

	    				$("span#loading").hide();
	    				$("#share").show();
	    				$("span#msg").show();

	    				if(json.error==0)
		    			{
	    					$("span#msg").html("Status updated successfully");
	    					$(reloadWall);

	    				}
	    				else
	    				{
	    					$("span#msg").html("Error");
	    				}

	    		   },
	    		   error: function (json, status, e){
	    			   $("span#msg").show();
	    			   $("span#msg").html("Exception : "+e+json);

	    			}
	    	 });
 	   }
 	});



  });
</script>
<div class="status-update">
	<span>STATUS UPDATE </span>
	<form class="cmxform" id="commentForm" method="post" action="">
	<input type="text" name="status" id="status" value="" class="update-txt required" />
	<input type="submit" name="share" id='share'  value="share" class="share-btn" /><div class="clear"></div>
	<?php if($this->loginUrl==""){?>


		<div class="send-stat"><em>Send my status update to Facebook</em><input class="styled" type="checkbox" name="facebook" id='facebook' value="1"/>
		</div>
		<?php }else{?>
			<a href="<?php echo $this->loginUrl;?>" ><img src="http://static.ak.fbcdn.net/rsrc.php/zB6N8/hash/4li2k73z.gif"></a>
		<?php } ?>
		<br/>





		<span id="loading" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif"/></span>
		<span id="msg"></span>
	</form>
</div>
<!-- status update ends -->


<!-- top section ends -->

<div id="center">
<div class="desti-info"><h2>Destination Info</h2><div class="location-bread"><a href="#">New Zealand</a>  &gt;  Queenstown</div></div>
<div class="map2"><img src="<?echo $this->cdnUri()?>/images/map2.jpg" alt="" /></div>
<h2><?php 

      foreach($this->destination as $_destination)
      {
        //print_r($_destination);
        echo $_destination->getTitle();



?></h2>
        <p class="intro"><?php echo $_destination->getIntroduction();} ?></p>


        <h2>You Can't Come Here and Not...</h2>
        <h3>Experience 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
        <h3>Experience 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc</p>
        <h3>Experience 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc</p>
        <div class="google-adds">
        <img src="<?echo $this->cdnUri()?>/images/google-adds.jpg" alt="" />
        </div>
        <h2>Hints and Tips</h2>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="hints-tips">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin accumsan ligula eu sapien consequat pellentesque. Pellentesque ac pellentesque sem. Vivamus sed est interdum erat tempor tempor et at diam. Quisque bibendum lorem eget nunc </p>
                <div class="like"><a href="#">Like  (10 Members Like this Tip)</a></div>
        </div>
        <div class="content-btns"><a href="#">Read More</a><a href="#">ADD TIP FOR THIS LOCATION</a></div>
        <div class="city-details">
                <div class="city-based-nav">
                        <h2>New Zealand</h2>
                        <ul>
                                <li><a href="#">Before You Go</a></li>
                                <li><a href="#">Transport</a></li>
                                <li><a href="#">Culture &amp; History</a></li>
                                <li><a href="#">Places of Interest</a></li>
                                <li><a href="#">Don't Leave Without</a></li>
                        </ul>
                </div>
                <div class="city-based-nav">
                        <h2>Queenstown</h2>
                        <ul>
                                <li><a href="#">Let's Get Practical</a></li>
                                <li><a href="#">Eat, Sleep, Drink, Be Merry</a></li>
                        </ul>
        </div>

        </div>
        <div class="content-banner">
                <img src="<?echo $this->cdnUri()?>/images/content-banner.jpg" alt="" />
        </div>
</div>
	




