<?php
//$this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
//$this->ckeditor = 'ckeditor'; //To tell the layout ckeditor must be loaded .
?>
<div id="rightsidemain">
	<div id="rightcontentpart">
		<div id="rightsideheading">Travel Shop CMS - Hot Affiliate Deals</div>
		<div id="rightsidecontentpart">
		<span class='red'><?php echo $this->errorMsg;?></span>
		<?php
			//$this->form->setAction($this->url(array('action' => 'add'))); 
			echo $this->form;
		?>
		</div>
	</div>
</div>
<?php //echo $this->setupEditor( 'content' ); ?>
