<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle(); ?>   
	<?php echo $this->headMeta(); ?>
	
  
	  <?php 
	  /*-------------- jquery ui----------------------*/
	  if($this->jQuery()->isEnabled())
		echo $this->jQuery();
	  /*-----------------------------------------------*/
	 ?>
  
  <?php echo $this->headScript(); ?>
  
  <?php echo $this->headLink(); ?>		
</head>

<body>

    <div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->
		
		<div id="sidebar">
                    <div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->
			
			
		  
			<!-- Logo (221px wide) -->
			<a href="/"><img id="logo" src="/images/logo.jpg" alt="ONSIS-We"></a>
		  
			
			        
                         <?php echo $this->pageElement('left-panel')?>
			
			
			
                    </div>
                </div> <!-- End #sidebar -->
		
		<div id="main-content"> <!-- Main Content Section with everything -->
			
			<noscript> <!-- Show a notification if the user has disabled javascript -->
				<div class="notification error png_bg">
					<div>
						Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
					</div>
				</div>
			</noscript>
			
			<!-- Page Head -->
			
                        <?php echo $this->navigation()->breadcrumbs()->setSeparator(" &gt; ")->setMaxDepth(3) ; ?><br><br>
                         <div class="clear"></div>
                        <?php echo  $this->flashMessages()?>
			 <div class="clear"></div>
                        <?php //echo $this->breadCrumb(); ?>
                       <?php echo $this->pageElement('header')?>
			
			<div class="clear"></div> <!-- End .clear -->
			<div class="content-box"><!-- Start Content Box -->
                            <div class="content-box-header">
                                <h3 ><?php              
                                    $page = $this->navigation()->findActive($this->navigation()->getContainer());
                                    if(isset($page['page']))
                                    echo $page['page']->getLabel();
                                    if($this->totalItems!="")
                                    echo " - Total ".$this->totalItems."(s) records found!";
                                ?></h3>
                                <div class="clear"></div>
                            </div> <!-- End .content-box-header -->

                        <div class="content-box-content">
                            <?php echo $this->layout()->content ?>
			</div> <!-- End .content-box-content -->
			</div> <!-- End .content-box -->
			
			<div class="clear"></div>
			
			
			
			
			<!-- Footer -->
                        <?php echo $this->pageElement('footer')?>
                        <!-- Footer -->

			
		</div> <!-- End #main-content -->
		
	</div>  
</body>
</html>
