<?php $user = $this->userObject; ?>
<?php
$userNs=new Zend_Session_Namespace("members");

?>
<style type="text/css">

label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }
em { font-weight: bold; padding-right: 1em; vertical-align: top; }
</style>
  <script>
      var user_id_login='<? echo $userNs->userId?>';
  $(document).ready(function(){

	  $("#status").focus(function(){$("span#msg").hide();});

    $("#commentForm").validate({
 	   submitHandler: function(form) {

                if(user_id_login=="")
                {
                    loginPopUp('Please login to post a message.');
                    return false;
                }
                
	    	var params=$(form).serialize();
	    	$("span#loading").show();
	    	$("span#msg").hide();
	    	$("#share").hide();
               

	    	$.ajax({
	    		   type: "POST",
	    		   url: "/profile/travel-wall/username/<?php echo $userNs->userUsername; ?>",
	    		   data: params,
	    		   dataType: "json",
	    		   success: function(json){

	    				$("span#loading").hide();
	    				$("#share").show();
	    				$("span#msg").show();

	    				if(json.error==0)
		    			{
	    					$("span#msg").html("Status updated successfully");
	    					$(reloadWall);

	    				}
	    				else
	    				{
	    					$("span#msg").html("Error");
	    				}

	    		   },
	    		   error: function (json, status, e){
	    			   $("span#msg").show();
	    			   $("span#msg").html("Exception : "+e+json);

	    			}
	    	 });
 	   }
 	});

 	$(reloadWall);

  });

  function reloadWall()
  {
	$("span#loading-wall").show();
	var params="mode=ajax";
	$.ajax({
		   type: "POST",
		   url: "/profile/reload-wall/username/<?php echo $user->getUsername(); ?>",
		   data: params,
		   dataType: "html",
		   success: function(html)
		   {
				$("span#loading-wall").hide();
				$("div#wall").html(html);

		   },
		   error: function (json, status, e){

			   $("span#wall").html("Exception : "+e+json);

			}
	 });
  }
  </script>
<script type="text/javascript" src="<?echo $this->cdnUri()?>/js/custom-form-elements.js"></script>
<script type="text/javascript">

        $(document).ready(function() {

        	$("#share-link-dd_menu").hide();
        	
            $("#share-link-dd").click(function(e) {          
				e.preventDefault();
                $("#share-link-dd_menu").toggle("slow");
				$("#share-link-dd").toggleClass("menu-open");
            });
			
			$("#share-link-dd_menu").mouseup(function() {
				return false;
			});
			
        });
</script>



	<div id="journal-center">
		<h2>TRAVEL WALL</h2>
		<h3 class="tw-sub-head"><a href="#"><?php echo $user->getFirstName();?></a> Had an amazing time visiting the sites</h3>
		<div class="time-stamp">10 July 2010, 9:17pm</div>


		<div class="user-post-msg">
		<h3>Post a Message</h3>
                <form class="cmxform" id="commentForm" method="post" action="">
		<textarea name='status' id='status' class="required user-wall-post" ></textarea><br class="clear" />
		<input type="submit"  name="share" id="share" value="Share"/>

                </form>

				<span id="loading" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif" alt="" /></span>
				<span id="msg"></span>
		</div>
			
			<span id="loading-wall" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif" alt=""/></span>

			<div id="wall">


			</div>
	</div>


<script type="text/javascript" language="javascript">

function like(item_id,vote)
{
	var params='';
	params+="vote="+vote;
	params+="&item_id="+item_id;
	params+="&item_type=status";
	$("span#like_"+item_id).hide();
        $("span#loading_"+item_id).show();
	$.ajax({
		   type: "POST",
		   url: "/vote/do-vote/",
		   data: params,
		   dataType: "json",
		   success: function(json){
			if(json.error==1)
			{
				alert(json.msg);
			}
			else if(json.error==2)
			{
                            $("span#loading_"+item_id).hide();
                             $("#comment-main-"+item_id).show();
                            if(vote==1){
                                $("span#unlike_"+item_id).show();
                                $("span#like_"+item_id).hide();
                                $("#you-like-this-"+item_id).show();


                            }else{
                                $("span#unlike_"+item_id).hide();
                                $("span#like_"+item_id).show();
                                $("#you-like-this-"+item_id).hide();
                            }


                            $("span#total_likes_"+item_id).html(json.total_up);
                            $("span#total_likes_left_"+item_id).html(json.total_up);
                        }
		   },
		   error: function (json, status, e){

			}
	 });
}

function showCommentBox(item_id)
{
     $("#comment-main-"+item_id).show();
      $("#status-comment-"+item_id).focus();
}

function likeComment(item_id,vote)
{
	var params='';
	params+="vote="+vote;
	params+="&item_id="+item_id;
	params+="&item_type=status_comment";
	$("span#like_"+item_id).hide();
        $("span#loading_comment_"+item_id).show();
	$.ajax({
		   type: "POST",
		   url: "/vote/do-vote/",
		   data: params,
		   dataType: "json",
		   success: function(json){
			if(json.error==1)
			{
				alert(json.msg);
			}
			else if(json.error==2)
			{
                            $("span#loading_comment_"+item_id).hide();
                            if(vote==1){
                                $("span#unlike_comment_"+item_id).show();
                                $("span#like_comment_"+item_id).hide();
                                $("#you-like-this-comment-"+item_id).show();
                            }else{
                                $("span#unlike_comment_"+item_id).hide();
                                $("span#like_comment_"+item_id).show();
                                $("#you-like-this-comment-"+item_id).hide();
                            }


                            $("span#total_likes_comment_"+item_id).html(json.total_up);
                            //$("span#total_likes_left_"+item_id).html(json.total_up);
                        }
		   },
		   error: function (json, status, e){

			}
	 });
}

function statusComment(item_id,commentedPersonId)
{
	var comment = $("#status-comment-"+item_id).val();
	if(comment == "" || comment == "Comment...")
	{
	  alert("Please enter comment");
	  $('#status-comment-'+item_id).focus();
	  return false;	
	}
 var params='';
	params+="comment="+$("#status-comment-"+item_id).val();
	params+="&item_id="+item_id;
	params+="&user_id="+commentedPersonId;
	params+="&item_type=status";
	//$("span#like_"+item_id).hide();
        $("span#comment_loading_"+item_id).show();
        $("#saveComment_"+item_id).hide();
	$.ajax({
		   type: "POST",
		   url: "/comment/save-comment/",
		   data: params,
		   dataType: "html",
		   success: function(html){

                    $("#saveComment_"+item_id).show();
                    $("span#comment_loading_"+item_id).hide();
                    $("#comment-list-"+item_id).append(html);
                    $("#status-comment-"+item_id).val('Comment...');
		   },
		   error: function (json, status, e){

			}
	 });
}

</script>
