<?php //echo $this->totalItemCount; ?>

<form method="post" action="<?php echo $this->seoUrl("/admin/db-config/database-configs")?>">
    <input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" alt="Search" onfocus="if(this.value=='Search...') this.value='';" onblur="if(this.value=='') this.value='Search...';"/>
    <input type="submit" value="Search" name="submit" class="button"/>
</form>
<?php if (count($this->paginator)): ?>
<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>
<table>
    <thead>
        <?php if($this->paginator->count()>1):?>
        
            <tr>
                <td colspan="7">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        
        <?php endif?>
        <tr>
            <th>S.No.</th>
            <th>Config id</th>
             <th>Server name</th>
            <th>Server port</th>
            <th>Database name</th>
            <th>Database user</th>
            <th>Transaction type</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
        <?php 
       
        foreach ($this->paginator as $item): ?>
        <?php  $sno++?>
        <tr>
            <td><?php echo $sno?></td>
            <td><?php echo $item->config_id;?></td>
            <td><?php echo $item->db_server_name; ?></td>
            <td><?php echo $item->db_server_port; ?></td>
            <td><?php echo $item->db_name; ?></td>
            <td><?php echo $item->db_user; ?></td>
            <td><?php echo $item->db_trans_type; ?></td>
            <td><?php echo $item->db_user; ?></td>
             <td>
                <!-- Icons -->
                <a title="Edit" href="<?php echo $this->seoUrl("/admin/db-config/edit-config/id/".$item->dbcnf_id)?>"><img alt="Edit" src="/images/pencil.png"></a>
                 <?php 
                    $image="/images/icons/cross_circle.png";
                    $title="Click here to delete configuration!";
                ?>
               
                &nbsp;&nbsp;
                <a title="<?php echo $title?>" href="<?php echo $this->seoUrl("/admin/db-config/delete-config/id/".$item->dbcnf_id)?>" onclick="javascript: return confirm('Are you sure you want to delete?');"><img alt="<?php echo $title?>"  src="<?php echo $image?>"></a> 
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if($this->paginator->count()>1):?>
        <tfoot>
            <tr>
                <td colspan="8">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        </tfoot>
        <?php endif?>
        
    </tbody>
</table>
<?php endif; ?>

