<form method="post" action="<?php echo $this->seoUrl("/pm/projects")?>">
    <input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" alt="Search" onfocus="if(this.value=='Search...') this.value='';" onblur="if(this.value=='') this.value='Search...';"/>
    <select name='status'>
        <option value=''>Status</option>
        <option <?php if($this->status=="open"){echo "selected='selected'";}?>value="open">Open</option>
        <option <?php if($this->status=="close"){echo "selected='selected'";}?>value="close">Close</option>
    </select>
    <?php if(count($this->projectManagers)>0){?>
    <select name='project_manager_id'>
        <option value=''>Project Manager</option>
        <?php foreach($this->projectManagers as $pm){?>
        <option <?php if($this->project_manager_id==$pm->project_manager_id){echo "selected='selected'";}?>value="<?php echo $pm->project_manager_id?>"><?php echo $pm->first_name." ".$pm->last_name?></option>
        <?php }?>
    </select>
    <?php }?>
    <?php if(count($this->teamLeaders)>0){?>
    <select name='team_leader_id'>
        <option value=''>Team Leader</option>
        <?php foreach($this->teamLeaders as $tl){?>
        <option <?php if($this->team_leader_id==$tl->team_leader_id){echo "selected='selected'";}?>value="<?php echo $tl->team_leader_id?>"><?php echo $tl->first_name." ".$tl->last_name?></option>
        <?php }?>
    </select>
    <?php }?>
    <input type="submit" value="Search" name="submit" class="button"/>
</form>
<?php if (count($this->paginator)): ?>


<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>


<table>
    <thead>
        <?php if($this->paginator->count()>1):?>
        
            <tr>
                <td colspan="7">
                         <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        
        <?php endif?>
        <tr>
            <th>S.No.</th>
            <th>Title</th>
            <th>Status</th>
            <th>Project Manager</th>
            <th>Team Leader</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $item): ?>
        <?php $sno++?>
        <tr>
            <td><?php echo $sno?></td>
            
            <td><?php echo $item->title; ?></td>
            <td <?php if($item->status=="close"){?> style="color:red" <?php }?>    > <?php echo $item->status; ?></td>
            
            <td><a href="javascript:#" onclick="openD('<?php echo $item->pm_id?>','<?php echo $item->pm_first_name." ".$item->pm_last_name; ?>')"><?php echo $item->pm_first_name." ".$item->pm_last_name; ?></a></td>
            <td><a href="javascript:#" onclick="openD('<?php echo $item->tl_id?>','<?php echo $item->tl_first_name." ".$item->tl_last_name; ?>')"><?php echo $item->tl_first_name." ".$item->tl_last_name; ?></a></td>
            <td><?php echo $item->start_date; ?></td>
            <td><?php echo $item->end_date; ?></td>
            <td>
                <!-- Icons -->
                <a title="Edit" href="<?php echo $this->seoUrl("/pm/edit-project/id/".$item->id)?>"><img alt="Edit" src="/images/pencil.png"></a>
                
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if($this->paginator->count()>1):?>
        <tfoot>
            <tr>
                <td colspan="7">
                        <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
                        <div class="clear"></div>
                </td>
            </tr>
        </tfoot>
        <?php endif?>
        
    </tbody>
</table>
<?php endif; ?>
<script>
    
    function openD(user_id,user_full_name)
    {
        $( "#dialog:ui-dialog" ).dialog( "destroy" );
         $("#userInfo").html("");
        $( "#dialog-modal" ).dialog({
                height: 460,
                width: 420,
                modal: true,
                title: user_full_name
        });
        $("#imgLoading").show();
        var params='id='+user_id;
        $.ajax({
                   type: "POST",
                   url: "/employee/employee-info",
                   data: params,
                   dataType: "html",
                   success: function(html)
                   {
                       $("#imgLoading").hide();
                        $("#userInfo").html(html);
                    
                        
                   },
                   error: function (json, status, e)
                   {
                      $("#userInfo").html("Error");
                       $("#imgLoading").hide();
                   }
               });


       
    }

</script>

<div id="dialog-modal" title="User Information" style="display:none">
    <img style="display:none" id="imgLoading" src="/images/loading.gif"/>
	<div id="userInfo"></div>
        
</div>