<link rel="stylesheet" type="text/css" href="/style/facebook-tag.css" media="all">
<script src="/js/facebook-tag-friend.js" type="text/javascript"></script>
<script>$(loadTagging);</script>

<span class="page_number">Back To <a href="/profile/album-photos/username/<?php print $this->userName;?>/id/<?php print $this->albumId;?>"><?php print $this->albumName;?></a>
<?php if($this->loggedInUserId != ""){?>  |  <a href="/album/my-photos/photo-download/name/<?php print $this->photo;?>">Download Photo</a><?php }?></span>
<span class="pages">Photo <?php print $this->photoPosition;?> of <?php print $this->numPhotoAlbum;?> 
	<span class="red-pagination"> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->prevId;?>,'left');"><</a> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->nextId;?>, 'right');">></a> </span>
</span>
<!-- End Heading -->
<?php 
	$imagePath = Zend_Registry::get('siteurl')."/media/album/custom/".$this->photo;

        $imagePath1 = PUBLIC_PATH."/media/album/custom/".$this->photo;

        $objBaseCommon = new Base_Common();
        $imageSize = $objBaseCommon->getimgwidhtheightstr($imagePath1, 443, 591);
?>
<!-- Start Tagged Images -->
<div class="viewallmyphoto">
<a href="javascript:void(0);" class="auto no-mrgn">
<img class="auto" src="/media/album/custom/<?php print $this->photo;?>" <?php print $imageSize;?> alt="" id="crop-image" onclick="slideImage(<?php print $this->nextId;?>, 'right');">
</a>
</div>
<!-- End Tagged Images -->

<!-- Start Btns Area -->
<div class="untags">
<span id="fb-like-album-container">
<iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->likeSrcUrl;?>&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
</span>

<div class="f-right">
<?php if($this->loggedInUserId != ""){?>
<a href="javascript:void(0);" id="album-photo-tag" class="button">Tag</a>
<?php }?>
<div id="icon">
  <div class="sign"><a href="#" class="signin"><span>SHARE IT</span></a></div>
  <div id="signin_menu">
    <div id="signin"> 
    <img src="/images/facebook.jpg" width="26" height="26" /> 
    <img src="/images/twiiter.jpg" width="26" height="26" /> 
    <img src="/images/delicious.jpg" width="26" height="26" /> 
    <img src="/images/digg.jpg" width="25" height="26" /> 
    <img src="/images/google.jpg" width="26" height="26" /> 
    <img src="/images/stumblr-upon.jpg" width="26" height="26" /> </div>
  </div>
</div>
</div>

<div id="tag" style="display:none;">
	<div id="tag-icon"></div>
	<div class="finish-taging">Click on an area in the photo tag
		<a href="javascript:void(0);" id="finish-tagging" class="button">FINISH TAGGING</a>
	</div>
</div>
<div class="description"><?php print $this->caption;?></div>
</div>
<!-- End Btns Area -->
<script>
$(document).ready(function(){
	$("a#like-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/like-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#unlike-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/unlike-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#album-photo-tag").click(function(){//
		$("#crop-image").attr("style","cursor: crosshair");
		$("#tag").slideDown(500);
		$("#tag-image-flag").val('1');
	});
});

$(document).ready(function(){
	$("a#finish-tagging").click(function(){//

		$("#crop-image").attr("style","");
		$("#tag").slideUp(500);
		$("#tag-image-flag").val('0');
		$("#tag-target").hide();
		$("#tag-input").hide();
	});
});


</script>