<link rel="stylesheet" type="text/css" href="/style/facebook-tag.css" media="all">
<script src="/js/facebook-tag.js" type="text/javascript"></script>
<script>$(loadPhotoTagging);</script>

<span class="page_number">Back To <a href="/profile/photos/username/<?php print $this->userName;?>/">Photos of <?php print ucfirst($this->userName);?></a>
<?php if($this->loggedInUserId != ""){?>  |  <a href="/album/my-photos/photo-download/name/<?php print $this->photo;?>">Download Photo</a><?php }?></span>
<span class="pages">Photo <?php print $this->photoPosition;?> of <?php print $this->numPhotoAlbum;?>
	<span class="red-pagination"> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->prevId;?>);">&lt;</a> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->nextId;?>);">&gt;</a> </span>
</span>
<!-- End Heading -->
<?php 
	$imagePath = Zend_Registry::get('siteurl')."/media/album/custom/".$this->photo;
	$imagePath1 = PUBLIC_PATH."/media/album/custom/".$this->photo;

        $objBaseCommon = new Base_Common();
        $imageSize = $objBaseCommon->getimgwidhtheightstr($imagePath1, 443, 591);
?>
<!-- Start Tagged Images -->
<div class="viewallmyphoto">
<a href="javascript:void(0);" class="no-mrgn auto">
<img class="auto" src="/media/album/custom/<?php print $this->photo;?>" <?php print $imageSize;?> alt="" id="crop-image" onclick="slideImage(<?php print $this->nextId;?>);">
</a>
</div>
<!-- End Tagged Images -->

<!-- Start Btns Area -->
<div class="untags">
<span id="fb-like-album-container">
<iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->likeSrcUrl;?>&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
</span>
<div class="description"><?php print $this->caption;?></div>
<a href="javascript: reportAbuse(<?php print $this->photoId;?>, 'photo');" class="button">REPORT</a>
</div>
<!-- End Btns Area -->
<script>
$(document).ready(function(){
	$("a#like-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/like-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#unlike-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/unlike-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});


</script>