<link rel="stylesheet" type="text/css" href="/style/facebook-tag.css" media="all">
<script src="/js/facebook-tag.js" type="text/javascript"></script>

<span class="page_number">Back To Photos of <a href="/album/my-photos/"><?php print $this->userFullName;?></a>  |
<a href="/album/my-photos/photo-download/name/<?php print $this->photo;?>">Download Photo</a></span>
<span class="pages">Photo <?php print $this->photoPosition;?> of <?php print $this->numPhotoAlbum;?>
	<span> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->prevId;?>);">&lt;</a> <a href="javascript:void(0);" onclick="slideImage(<?php print $this->nextId;?>);">&gt;</a> </span>
</span>
<!-- End Heading -->

<!-- Start Tagged Images -->
<div class="viewallmyphoto">
<a href="javascript:void(0);">
<img width="591" src="/images/album/custom/<?php print $this->photo;?>" alt="" id="crop-image" onclick="slideImage(<?php print $this->nextId;?>);">
</a>
</div>
<!-- End Tagged Images -->

<!-- Start Btns Area -->
<div class="untags">
<span id="like-photo-container">
<?php if($this->numVote == 0){?>
<a href="javascript:void(0);" id="like-photo">
<img src="/images/fb.jpg" alt="" width="51" height="23" class="f-left">
</a>
<?php }else{?>
<a href="javascript:void(0);" id="unlike-photo">
<img src="/images/fb-unlike.jpg" alt="" class="f-left">
</a>
<?php }?>
</span>
<div class="description"><?php print $this->description;?></div>
<a href="javascript: reportAbuse(<?php print $this->photoId;?>, 'photo');" class="button">REPORT</a>
<a href="#" class="button">UN-TAG IMAGE</a>
</div>
<!-- End Btns Area -->
<script>
$(document).ready(function(){
	$("a#like-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/like-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});

$(document).ready(function(){
	$("a#unlike-photo").click(function(){
		var photo_id	=	$("#photo_id").val();
		var item_type	=	'album_photo';
		var requesturl	=	"/album/my-photos/unlike-photo";

			$.post(requesturl, {photo_id:photo_id,item_type:item_type },
					   function(html){					
						$("#like-photo-container").html(html);
							
					});	
		
	});
});


</script>