<a href="javascript:void(0);" id="like-album">
<img src="/images/fb.jpg" alt="" class="f-left">
</a>
<script>
$(document).ready(function(){
	$("a#like-album").click(function(){
		var album_id	=	$("#album_id").val();
		var item_type	=	'album';
		var requesturl	=	"/album/my-photos/like-album";

		$.post(requesturl, {album_id:album_id, item_type:item_type },
					   function(html){					
						$("#like-album-container").html(html);
							
					});	
		
	});
});
</script>