MY LOCATION <a href="/gapper/my-gap-journy">My Gap Journy</a>
<br/><br/><br/>
<a href="/gapper/show-map">Show Map</a>
UPDATE MY LOCATION <input type="text" name="uml"></input><a href="/gapper/update">Update</a>
SHOW ON MAP 
<select name="som">
  <option>Only Me</option>
  <option>Nearby Traveller</option>
  <option>My Gap Journey</option>
</select>
<div>
STATUS UPDATE <input type="text" name="su"><a href="/gapper/update">Share</a><br/><input type="checkbox" checked="checked">Send my status update to Facebook</input>
<br/>DESTINATION INFO
</div>

<?php
