<script>
function sendRequest(id, status)
{
	$("div#req_response_"+id).html("<img src='/images/ajax-loader.gif'>");
	var params="mode=ajax&id="+id+"&status="+status;
	$.ajax({
		   type: "POST",
		   url: "/gapper/resend-request/",
		   data: params,
		   dataType: "html",
		   success: function(responseData)
		   {
				$("div#req_response_"+id).html(responseData);
				$("div#req_status_"+id).html("<b>Status:</b> Pending");
				RAVIN_DelayedHide("req_response_"+id);
				$("span#resend_link_id").html('');
				//alert("function call sucessfully ="+responseData);
		   },
		   error: function (json, status, e)
		   {
			   $("div#resp").html("Exception : "+e+json);
		   }
	 });
}

function mySubmit(){
	
	$("#searchfrm").submit();
	
}
</script>
<div id="center">
		 <h2><?php echo $this->puts("My Requests")?></h2>
		 <p><?php echo $this->puts("Here are your pending friend requests.")?> <!-- It display only Declined and Pending requests. --></p><br />
         <a href="/gapper/add-a-connection" class="orange-big"><?php echo $this->puts("Add a friend")?></a><br/><br />
         <form action = "/gapper/requests" method="post" name="searchfrm" id="searchfrm" style="display:inline">
			<!-- <div class="filter-conection">Filter requests by: 
			<select name="status"  onchange="mySubmit();">
            <option value="">Declined and Penidng Requests</option>
            <option value="decline" <?php echo $this->status=='decline'?'selected':''; ?>>Decline Requests</option>
            <option value="pending" <?php echo $this->status=='pending'?'selected':''; ?>>Pending Requests</option>
			</select>
			</div> -->
			 <div class="friend-results">
				<span class="f-left">
				<?php echo $this->totalFriends;
				//display search type
				$search_for ="Pending";
				if(isset($this->status) && $this->status=='decline')
				{
					$search_for ="Declined";
				}
				else if(isset($this->status) && $this->status=='pending')
				{
					$search_for ="Pending";
				}
				else
				{
					//$search_for ="Declined and Pending";
					$search_for ="Pending";
				}
				?> <?php echo $search_for;?> Requests
				</span> 
			</div>
		</form>
<div>
<?php 
if($this->totalFriends>0)
{
	foreach($this->paginator as $row)
	{
		$_friend	= new Application_Model_Friend();
		$_friend	= $_friend->find($row->id);

		$userid		= $_friend->getUserId();
		$friendid	= $_friend->getFriendId();
		$conntype	= $_friend->getConnectionType();
		$status		= $_friend->getStatus();

		$_friend->getId();
		$friendO = $_friend->getFriendObj();
		
		if(!is_null($friendO))
		{
			$thumb = "";
			//$thumb		= $_friend->getThumbnail();
			//echo "<br>img=>".$friendO->image." fac=>".$friendO->facebook_id." user id=>".$friendO->id;
			$thumb		= $_friend->getThumbnail($friendO->image, $friendO->facebook_id, $friendO->sex);

?>
<div class="friends-box">
   		<div class="friends-box-img">
			<a href ="/<?php echo $friendO->username?>">
			<?php //if(null != $friendO->image) { ?>
				<!--<img src="/media/picture/profile/thumb_<?php echo $friendO->image; ?>" width="86" style="float:left;margin:0 10px 5px 0;" border="0" />-->
			<?php //} else { ?>
				<!--<img src="/images/noimage-86x101.jpg" style="float:left;margin:0 10px 5px 0;" border="0" />-->
			<?php //} ?>
			<img src="/image?src=<?php echo $thumb;?>&size=friends" border="0" />
			</a>
		</div>
		<div class="friend-box-center"> 
			<a href ="/<?php echo $friendO->username?>"><span class="connect-name"><?php echo $friendO->first_name.' '.$friendO->last_name; ?></span></a>
			<span class="connect-type"><?php echo ucfirst($_friend->getConnectionType()); ?></span>
			<span class="connect-action">
				<span id="resend_link_id"><a href ="javascript://" onclick="sendRequest(<?php echo $_friend->getId()?>,'pending');"><b>Re-Send Request</b></a> |</span> <a href ="/gapper/remove-requests/id/<?php echo $_friend->getId();?>" onclick="return confirm('Are you sure?\r\n Do you really want to remove this friend request?');">Remove Request</a>
			</span>
			
		</div>
		<div class="friend-box-right">
			<div class="connection-you f-left"></div>
			<div id="req_status_<?php echo $_friend->getId()?>"><b>Status:</b> <?php echo ucwords($status);?></div>
			<div id="req_response_<?php echo  $_friend->getId()?>" style="clear:both; float:right;"></div>
		</div>   
</div>
<?php
    }//end of if
}//end of foreach
echo  "<div class='clear'>".$this->paginationControl($this->advices, 'Sliding', 'pagination.phtml', array("linkArray"=>$this->param))."</div>";
}//end of if
else
{
	echo "<span style='color:#ff0000;'>No requests found.</span>";
}
?>
</div>
</div>
