<div class="right-box">
        <h2 class="box-head">JOURNALS</h2>
        <div class="right-inner-box">
                <div class="right-inner-box-title"><a href="#">Travel advice for trips to Hong Kong</a></div>
                <div class="right-inner-box-by">By <a href="">Kevin G</a>  Sun, 20 Jun 10</div>
        </div>
        <div class="right-inner-box">
                <div class="right-inner-box-title"><a href="#">Check out some of my favourite climbing boots of all time</a></div>
                <div class="right-inner-box-by">By <a href="#">Joe C</a>  Sun, 18 Jun 10</div>
        </div>
        <div class="right-inner-box">
                <div class="right-inner-box-title"><a href="#">My chance meeting with a Zulu warrior</a></div>
                <div class="right-inner-box-by">By <a href="#">Casey B</a>  Sun, 17 Jun 10</div>
        </div>
        <div class="view-link"><a href="#">VIEW ALL</a></div>
</div>