<div class="pagination">
    <div class="paging-r f-right">
         <!-- First page link -->
        <?php 
       $arrayLink=array();
       
      
       if(is_array($this->linkArray))
       		$arrayLink=$this->linkArray;
        ?>
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array_merge(array('page' => $this->first),$arrayLink)); ?>">First</a> |
        <?php else: ?>
                <span class="disabled">First</span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array_merge(array('page' => $this->previous),$arrayLink)); ?>">&lt; Previous</a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array_merge(array('page' => $page),$arrayLink)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array_merge(array('page' => $this->next),$arrayLink)); ?>">Next &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Next &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array_merge(array('page' => $this->last),$arrayLink)); ?>">Last</a>
        <?php else: ?>
            <span class="disabled">Last</span>
        <?php endif; ?>
        &nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>
       
    </div>
 </div>