<div id="rightsidemain">
  <div id="rightcontentpart">
	<div id="rightsideheading" class="headingblack">
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
	<a href="/admin/continent/add/" class="add f-right">Add Continent</a></span>	
	<?php echo $this->title ?> - <span class='msg'>Total <?php echo $this->total?> continent(s) found! </span></div>	
 <div id="rightsidecontentpart">
<?php
if($this->total>0)
{
	
?>
<span class='red'><? echo $this->msg;?></span>
<?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml');?>
<table width='100%' border='0' class='dataTable' cellspacing='0' cellpadding='0'>
  <tr>
    <th>SNo.</th>
    <th>Continent</th>
    <th>Action</th>
  </tr>
  
	<?
	
	$sno=0;
	$page=$this->paginator->getCurrentPageNumber();
	$items_per_page=$this->paginator->getItemCountPerPage(); 
	if($page>1){
	$sno=$items_per_page*$page - $items_per_page ; 	
	}
	$rowClass='trbg1';
	
	foreach($this->paginator as $row)
	{
		$sno++;
				
		if($rowClass=="trbg1")
			$rowClass='trbg';
		else
			$rowClass='trbg1';
			
	$DATE=new Base_Date();
	
	?>
		<tr class='<?=$rowClass?>'>
    		<td><?=$sno?></td>
    		
    		<td><?=$row['name']?></td>
    		
	
			
    		<td>
    		<a href='/admin/continent/edit/id/<?=$row['id']?>/page/<?=$page?>'><img src='/images/admin-images/edit.gif' border='0' title='Edit'/></a>&nbsp;&nbsp;
            <!--<a href='/admin/continent/delete/id/<?=$row['id']?>' onclick="return confirm('Are you sure you want to delete the continent?')"><img src='/images/admin-images/false.gif' border='0' title='Click here to delete the continent'/></a>-->
    		</td>
    		
  		</tr>
	<? 	
	}
	?>
	</table><br />
	<?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml'); ?><br />
<?	
}
?>
</div>
</div>
</div>
