
<?php $date=new Base_Date();?>

<div id="employee-info-content">
<table>
    <tbody>
        
        <tr ><td>Config Name:</td><td><?php echo $this->config->getConfigName();?></td></tr>
        <tr ><td>Config Id :</td><td><?php echo $this->config->getConfigId()?></td></tr>
        <tr ><td>Parent Id :</td><td><?php echo $this->config->getParentConfigId()?></td></tr>
        <tr ><td>Description :</td><td><?php echo $this->config->getConfigDesc()?></td></tr>
        <tr ><td>Param-1:</td><td><?php echo $this->config->getParam1()?></td></tr>
        <tr ><td>Param-2:</td><td><?php echo $this->config->getParam2()?></td></tr>
        <tr ><td>Param-3:</td><td><?php echo $this->config->getParam3()?></td></tr>
        <tr ><td>Param-4:</td><td><?php echo $this->config->getParam4()?></td></tr>
        <tr ><td>Param-5:</td><td><?php echo $this->config->getParam5()?></td></tr>
        
    </tbody>
</table>
</div>
