
	<div id="rightsideheading">
	<img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />
	<span style="margin: 0pt 15px 0pt 0pt; float: right;">
		<a href="/admin/user" class="add">Back</a>
	</span>
	User - Add</div>
		<div id="rightsidecontentpart">
			<span class='red'><? echo $this->msg;  ?></span>
		
			<?php echo $this->form?>
			
		</div>






<script type="text/javascript">
$(function() {
	$("#cityName").autocomplete({
		source: "/index/autosuggest-city/",
		minLength: 1,
		select: function(event, ui) {
		$("#cityId").val(ui.item.id);
		}
	});

	function split(val) {
		return val.split(/,\s*/);
	}

	function extractLast(term) {
		return split(term).pop();
	}

	$("#otherLanguages").autocomplete({
		source: function(request, response) {
			$.getJSON("/index/autosuggest-language/", {
				term: extractLast(request.term)
			}, response);
		},
		search: function() {
			// custom minLength
			var term = extractLast(this.value);
			if (term.length < 2) {
				return false;
			}
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});

</script>	