<div id="rightsidemain">
<div id="rightcontentpart">
	<div id="rightsideheading"><img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />Change Password</div>
	<div id="rightsidecontentpart">

	<?php
		echo $this->msg;
		
		echo $this->form;
		?>
	</div>  
</div>
<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
</div>
