<div class="content-box"><!-- Start Content Box -->
				
        <div class="content-box-header">
                <h3><?php echo $this->pageHeading?></h3>
        </div> <!-- End .content-box-header -->
<?php //var_dump($this->messages)?>
        <div class="content-box-content">
            <form action="<?php echo $this->seoUrl("/admin/index/forgot-password")?>" method="post">
                <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
                        <p>
                            <label>Email</label>
                            <?php echo $this->form->email;?>
		
		
                             <?php if ($this->email_msg){?>
                            <span class="input-notification attention png_bg"><?php echo $this->email_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                            <?php }?>
                            <br><small>Enter your email address.</small>
                        </p>
                        
                        <p>
                                <input class="button" value="Proceed" type="submit">
                                
                        </p>

                </fieldset>

                <div class="clear"></div><!-- End .clear -->

            </form>
        </div> <!-- End .content-box-content -->
        
        
   
        

</div> <!-- End .content-box -->