<div class="content-box"><!-- Start Content Box -->
				
        <div class="content-box-header">
                <h3><?php echo $this->pageHeading?></h3>
        </div> <!-- End .content-box-header -->
<?php //var_dump($this->messages)?>
        <div class="content-box-content">
            <form action="<?php echo $this->seoUrl("/admin/index/login")?>" method="post">
                <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
                        <p>
                            <label><?php echo $this->form->email->getLabel();?></label>
                            <?php echo $this->form->email;?>
		
		
                             <?php if ($this->email_msg){?>
                            <span class="input-notification attention png_bg"><?php echo $this->email_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                            <?php }?>
                            <br><small>Enter username or email address.</small>
                        </p>
                        <p>
                            <label><?php echo $this->form->password->getLabel();?></label>
                            <?php echo $this->form->password;?>
                            <?php if ($this->password_msg){?>
                            <span class="input-notification attention png_bg"><?php echo $this->password_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                            <?php }?>
                            <br><small>Enter your 6-20 character password.</small>
                        </p>
                        <p>
                                <input class="button" value="Proceed" type="submit">
                                <a href="<?php echo $this->seoUrl("/admin/index/forgot-password")?>">Forgot Password?<a/>
                        </p>

                </fieldset>

                <div class="clear"></div><!-- End .clear -->

            </form>
        </div> <!-- End .content-box-content -->
        
        
   
        

</div> <!-- End .content-box -->


<?php




//echo $v3uuid = Base_Uuid::v3('1546058f-5a25-4334-85ae-e68f2a44bbaf', 'SomeRandomString');
//echo $v5uuid = Base_Uuid::v5('1546058f-5a25-4334-85ae-e68f2a44bbaf', 'SomeRandomString');

// Pseudo-random UUID

//echo $v4uuid = Base_Uuid::guid();


?>