
<?php
		$objModelVote	=	new Application_Model_Vote();
		foreach ($this->arrComment as $comment)
		{
			if($comment['imageName'] == "")
			{
				$imagePath	=	"/images/no-image.jpg";
			}else{
				$imagePath	=	"/media/picture/profile/".$comment['imageName'];
			}	
		/*-------- GET NUMBER OF VOTE -----------*/
	    $numVotes	=	$objModelVote->numVotes($this->item_type1, $comment['commentId']);
/*---------------------- CHECK CURRENT USER LIKE ---------------------*/
	   $whereLike = " item_type = '{$this->item_type1}' AND item_id = '{$comment['commentId']}' AND vote='1' ";
	   $arrVote	=	$objModelVote->fetchAll($whereLike);
	   $countVote=	count($arrVote);
           if($countVote == 1){
                $strMemberLike = $countVote.' '.$this->language("like_singular");
           }else{
                $strMemberLike = $countVote.' '.$this->language("like_plural");
           }
/*----------------------------------------------------------------------------------------------*/
           $whereLikeMember = " item_type = '{$this->item_type1}' AND item_id = '{$comment['commentId']}' AND vote='1' AND user_id='{$this->userId}' ";
	   $arrVoteMember = $objModelVote->fetchAll($whereLikeMember);
	   $countVoteMember =	count($arrVoteMember);
/*--------------------------------------------------------------------------------*/
					 $date = new Base_Date();
					 $strTime = $date->timeAgo($comment['addedon']);
?>
<li id="<?php print "album_comment_".$comment['commentId'];?>">
<div class="commnetor"><img src="<?php print $imagePath;?>" width="35" height="41" /></div>
<div class="commnetarea"><span class="commented-member"><a href="javascript://" onclick="commonUserLogin('/<?php echo $comment['commenterUserName'];?>',<?php echo $comment['commenterUserId'];?>);"><?php print $comment['commenterName'];?></a> </span> <?php print $this->textModifier($comment['comment']);?>
<div class="post">Posted <?php print $strTime;?>  | 
<?php if($countVoteMember > 0){?>
<span id="<?php print "com_".$comment['commentId'];?>"><?php if($numVotes > 0){ print $strMemberLike; }?> <a href="javascript:void(0);" onclick="return albumCommentUnlike(<?php print $comment['commentId'];?>);">Unlike</a></span>
<?php }else{?> 
<span id="<?php print "com_".$comment['commentId'];?>"><?php if($numVotes > 0){ print $strMemberLike; }?>
    <?php if($this->userId !=""){?>
    <a href="javascript:void(0);" onclick="return albumCommentLike(<?php print $comment['commentId'];?>);">Like</a>
    <?php }else{?>
    <a href="javascript: loginPopUp('Please login to like');" >Like</a>
    <?php }?>
</span>
<?php }
if($comment['permission'] == 1){ // Checking permission for remove comment
?>
|  <a href="javascript:void(0);" onclick="return removeAlbumComment(<?php print $comment['commentId'];?>);" >Remove</a>
<?php }?>
</div>
</div>
</li>
<?php }?>


<script>






function albumCommentLike(commentId)
{
	var requesturl	=	"/album/my-photos/like-album-comment";
	var item_type	=	$("#item_type1").val();
	var spanId		=	'com_'+commentId;

		$.post(requesturl, {commentId:commentId,item_type:item_type},
				   function(html){					
					$("#"+spanId).html(html);
						
				});	
	
}

function albumCommentUnlike(commentId)
{
	var requesturl	=	"/album/my-photos/unlike-album-comment";
	var item_type	=	$("#item_type1").val();
	var spanId		=	'com_'+commentId;

		$.post(requesturl, {commentId:commentId,item_type:item_type},
				   function(html){					
					$("#"+spanId).html(html);
						
				});	
	
}

function removeAlbumComment(albumCommentId)
{
    var answer= confirm('Are you sure you want to delete this comment?');
	
	if(!answer){
    return false;
  }

 
	var liId	=	'album_comment_'+albumCommentId;

	var requesturl	=	"/album/my-photos/remove-comment";

	$.post(requesturl, {albumCommentId:albumCommentId},
			   function(html){					
				$("#"+liId).slideUp('slow');
					
			});	
	
}


</script>
