<div class="right-box-wide search-dest">
	<h2 class="box-heading">SEARCH</h2>
	<form name="searchData" method="post" action="/work-study-volunteer/search">
		<input type="text" name="search-strg" id="search-strg" class="search-strg" value="<?php echo $this->searchstr!=''?$this->searchstr:'Search by Keyword'; ?>" onfocus="if(this.value=='Search by Keyword'){this.value=''}" onblur="if(this.value==''){this.value='Search by Keyword'}"  />
		<span class="in">IN</span><select class="search-filtr2" name="search-filtr" id="search-filtr">
				<option value=''>All Categories</option>
				<?php
				$categoryM		=	new Application_Model_Category();
				$adviceCategory	=	$categoryM->getCategory(null,'wsv');
				if(count($adviceCategory)>0)
				{
					foreach($adviceCategory as $id=> $_category)
					{
						$selected = "";
						if($this->searchfiltr==$id)
						{
							$selected = "selected='selected'";
						}
						echo "<option value='".$id."'".$selected.">".$_category."</option>";
					}
				}	
				?>
		</select>
		<div class="clear"></div>
		<input type="submit" name="" value="SEARCH" onclick="return validateForm();" class="submit-btn"  />
		<input type="button" name="" value="Reset" class="submit-btn" id="reset-form-field" />
	</form>	
</div>
<script language="javascript" type="text/javascript">
function validateForm()
{
	var str=$("#search-strg").val();
	if(str=="" || str=="Search by Keyword")
	{
		var title="Warning !";
		var msg ="Please enter a keyword and then press Search button.";
		alertBox(title,msg); // for more details, please look into lib.js
		return false;
	} 
	return true;
}

$('#reset-form-field').click(function() {
	$("input#search-strg").val('Search by Keyword');
	$("#search-filtr").val('');
});
</script>
