<form   method="post">
    <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
            
            <p>
                <label><?php echo $this->form->password->getLabel();?></label>
                <?php echo $this->form->password;?>
                <?php if ($this->password_msg){?>
                <span class="input-notification attention png_bg"><?php echo $this->password_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                <?php }?>
                <br><small>Enter your new 6-20 character password.</small>
            </p>
            <p>
                <label><?php echo $this->form->confirmPassword->getLabel();?></label>
                <?php echo $this->form->confirmPassword;?>
                <?php if ($this->cpassword_msg){?>
                <span class="input-notification attention png_bg"><?php echo $this->cpassword_msg ?></span> <!-- Classes for input-notification: success, error, information, attention -->
                <?php }?>
                <br><small>Re-enter your new 6-20 character password.</small>
            </p>
            <p>
                    <input class="button" value="Proceed" type="submit">
            </p>

    </fieldset>

    <div class="clear"></div><!-- End .clear -->

</form>