<?php
if($this->align=="")
    $this->align="left";
if($this->label=="")
    $this->label="";
?>
<div class="content-box column-<?php echo  $this->align?> <?php echo  $this->box_status?> ">
    <div class="content-box-header">
        <?php 
                $startTimestamp=mktime(0, 0, 0, 4, 1, date("Y")); //20011-04-01 00:00:00
                $endTimestamp=mktime(0, 0, 0, 3, 31, date("Y")+1); //2012-03-31 00:00:00
                $date=new Base_Date();
                ?>
        <h3 style="cursor: s-resize;"><?php echo $this->label?>Leave Account from <?php echo $date->getSysDate($startTimestamp, false) ?> to  <?php echo $date->getSysDate($endTimestamp, false)?></h3>
    </div> <!-- End .content-box-header -->

    <div class="content-box-content" style="display: block;  min-height:140px">
    <div class="tab-content default-tab" style="display: block;">
   <div class="div-table"> 
        
        <div class="div-row">
            <div class="div-cell-bold">Leave Type</div>
            <div class="div-cell-bold">Total Credited</div>
            <div class="div-cell-bold">Total Debited</div>
            <div class="div-cell-bold">Available Balance</div>
        </div>
        <?php $leaveBalance=$this->user->getLeaveBalance()?>
          <?php foreach($leaveBalance as $lb){ ?>
        <div class="div-row">
            <div class="div-cell"><?php echo $lb['title']?></div>
            <div class="div-cell"><?php echo $lb['credited']?></div>
            <div class="div-cell"><?php echo $lb['debited']?></div>
            <div class="div-cell"><?php echo $lb['balance']?></div>
        </div>
          <?php }?>

      </div>
    </div> <!-- End #tab3 -->        
    </div> <!-- End .content-box-content -->
</div>
