<?php $date=new Base_Date();?>
<?php
//echo $this->user->row->findParentDesignation();
?>
<table>
    <tbody>
        <tr ><td colspan="2"><img src="<?php echo $this->user->getProfileImage()?>"></img> <?php echo $this->form ?></td></tr>
        <tr ><td>Employee Code :</td><td><?php echo $this->user->getEmployeeCode()?></td></tr>
        <tr ><td>Name : </td><td><?php echo $this->user->getFirstName()." ".$this->user->getLastName() ?></td></tr>
        <tr ><td>Designation : </td><td><?php echo $this->user->getDesignation() ?></td></tr>
        <tr ><td>Department : </td><td><?php echo $this->user->getDepartment() ?></td></tr>
        <tr ><td>Email :</td><td><?php echo $this->user->getEmail()?></td></tr>
        <tr ><td>Username :</td><td><?php echo $this->user->getUsername()?></td></tr>
        <tr ><td>Date of Birth :</td><td><?php echo $this->formatDate(strtotime($this->user->getDob()), false)?></td></tr>
        <tr ><td>Father's Name : </td><td><?php echo $this->user->getFatherName() ?></td></tr>
        <tr ><td>PAN No. :</td><td><?php echo $this->user->getPan()?></td></tr>
        <tr ><td>Mobile No. :</td><td><?php echo $this->user->getMobile()?></td></tr>
        <tr ><td>Alt. Contact No. :</td><td><?php echo $this->user->getContactNo()?></td></tr>
        <tr ><td>Extension No. :</td><td><?php echo $this->user->getExtensionNo()?></td></tr>
        <tr ><td>Skype Id :</td><td><?php echo $this->user->getSkype()?></td></tr>
        <tr ><td>Date of Joining:</td><td><?php echo $this->formatDate(strtotime($this->user->getDoj()), false)?></td></tr>
        <tr ><td>Marriage Aniversary :</td><td><?php echo $this->formatDate(strtotime($this->user->getMarriageAnniversary()), false)?></td></tr>
        <tr ><td>Gender :</td><td><?php echo ucfirst( $this->user->getSex())?></td></tr>
        <tr ><td>Correspondence Address :</td><td><?php echo  $this->user->getCorrespondenceAddress()?></td></tr>
    </tbody>
</table>
