

<?php
if($this->align=="")
    $this->align="left";
?>
<div class="content-box column-<?php echo  $this->align?> <?php echo  $this->box_status?> ">
    <div class="content-box-header">
     
    <h3 style="cursor: s-resize;">Notice Board</h3>
    </div> <!-- End .content-box-header -->

    <div class="content-box-content" style="display: block;  min-height:200px">
    <div class="tab-content default-tab" style="display: block;">
            <div class="div-table">
                <?php if($this->latestNotice){?>
              
                <div class="noticeboard">
                       <div class="notice-title" >
                            <?php echo $this->latestNotice->getTitle();?>
                        </div>
                     <div class="notice-content" >
                            <p><?php echo $this->latestNotice->getContent();?> </p>
                     </div>
                        
                </div>
                
                <?php }?>
            </div>
    </div> <!-- End #tab3 -->        
    </div> <!-- End .content-box-content -->
</div>
