<?php if($this->status==1 ){?>
	<div class="normal-txt">
	
	<?php echo $this->content;?>
	</div>
<?php 
}
else
{?>
<!--<h2 class="main-heading4">Oops!! </h2>
<p class="oops-msg">You have reached a page that has changed or no longer exists.<br />Sorry, we could not find the page you were looking for. Maybe it's moved, or maybe the URL is incorrect, or maybe you performed an illegal operation.</p>
</h2>-->
<div class="wide-page">
<h2 class="main-heading4">Oops!! </h2>
<p class="oops-msg">This page has been removed.</p>
</div>
<?php }?>

