
<!--Right Part Content -->
  <div id="rightsidemain">
  <div id="rightcontentpart">
    <div id="rightsideheading" ><img src="/images/admin-images/bl-tl.gif" align="left" /><img src="/images/admin-images/bl-tr.gif" align="right" />Dashboard</div>
    
    <div id="rightsidecontentpart">
      
     <h2>Welcome to Administration Area</h2>
    </div>
	<div class="btm-curve"><img src="/images/admin-images/btm-r-l.gif" align="left" /><img src="/images/admin-images/btm-r-r.gif" align="right" /></div>
    
    </div>
  </div>
  </div>