<div class="box1">
    <div class="home-art-left">
      <h1>FEATURED ARTICLE</h1>
      <h3>NAME OF ARTICLE GOES HERE</h3>
      <p>Sed et euismod, te ullamcorper, consequat lobortis minim wisi augue, nisl diam esse. Ea consequat delenit eum iriure dolore ut ut nulla ex iusto et. Magna ex tincidunt illum luptatum eu te in in feugiat eros augue sit. Delenit, blandit, odio consequat duis vel aliquip duis at ipsum quis esse at et feugait, elit lorem velit hendrerit eum, feugiat commodo dolore ut vel.</p>
      <a href="#" class="orange-sml">Read More</a> </div>
    <div class="home-art-right"><img src="images/cook-img.jpg" alt="" /></div>
  </div>