<!--<div class="box">
    <h1>Plot Your journey</h1>
    <img src="<?echo $this->cdnUri()?>/images/map.jpg" alt="" class="map" />
    <div class="clear"></div>
    <form class="home-form-journy">
      <label>Where are you?</label>
      <input type="text" class="city-update f-left" value="Address, City or Country" onblur="if(this.value==''){this.value='Address, City or Country'}" onfocus="if(this.value=='Address, City or Country'){this.value=''}" />
      <input type="submit" value="Locate Me" class="city-update-btn  f-left" />
      <div class="clear"></div>
      <label>Who are you following?</label>
      <input type="text" class="following-search" value="Search Gap Daemon" onblur="if(this.value==''){this.value='Search Gap Daemon'}" onfocus="if(this.value=='Search Gap Daemon'){this.value=''}" />
      <input type="submit" value="" class="following-search-btn" />
    </form>
  </div>-->

<div class="box">
    <h1>See Where You Are</h1>
   

    <div id="map_canvas" style="width: 433px; height: 243px" class="f-left"></div>
    <div class="clear"></div>
    <div class="home-form-journy">
      <label>Where are you?</label>
      <input type="text" id="address" onkeyup="submitenter(this,event)" name="address" class="city-update f-left" value="Address, City or Country" onblur="if(this.value==''){this.value='Address, City or Country'}" onfocus="if(this.value=='Address, City or Country'){this.value=''}" />
       <input type="button" value="Check In" onclick="updateGapperLocation(marker.getPosition())" class="city-update-btn  f-left" >
      <div class="clear"></div>
      <label>Who are you following?</label>
      <input type="text" class="following-search" value="Search Gap Daemon" onblur="if(this.value==''){this.value='Search Gap Daemon'}" onfocus="if(this.value=='Search Gap Daemon'){this.value=''}" />
      <input type="submit" value="" class="following-search-btn" />

    </div>
  </div>



<div id="dialog-confirm" class="ui-dialog" title="" style="display:none">

		<!-- pop up start -->

		<div id="login_box1" >
  <div class="topbg"></div>
  <div class="content_box" >
	<form id=""  action="" method="post">
    <div class="div2 aqua_green"><strong>Please Confirm</strong></div>
      <div id="login_error_msg" class="div2 clear mart5 orange"><strong></strong></div>

      <div class="input-field">
        <label class="required" for="email">This location will be set as your current location. Are you sure? </label>
      </div>
	  <br class="clear" />

      <div class="div2 mart5">
	  <a class="cmn_register marl"  href="javascript: doUpdate();">UPDATE</a>
          <a class="cmn_register marl"  href="javascript: doCancel();">CANCEL</a>
      </div>
  	  <br class="clear" /><br class="clear" />
	   <p><span id="loading-location" style="display: none"><img src="<?php echo $this->cdnUri()?>/images/loading.gif"/></span></p>
    </form>
  </div>
</div>

		<!-- pop up ends -->

	</div>

<div id="dialog-message" class="ui-dialog" title="" style="display:none">
	<!--update pop up start -->
	<!--<div id="login_box1" >
	  <div class="topbg"></div>
	  <div class="content_box">
		<form id=""  action="" method="post">
		<div class="div2 aqua_green"><strong>Confirmation</strong></div>
		  <div id="login_error_msg" class="div2 clear mart5 orange"><strong></strong></div>

		  <div class="input-field">
			<label class="required"><strong>You have successfully updated your current location.</strong>
			  <br class="clear" /><br class="clear" />
			<strong class="aqua_green">You current location is</strong> : <hr /> <p><strong><span id="coordinate_span" > </span>.</strong></p></label>
		  </div>
		  <br class="clear" /><br class="clear" />

		</form>
	  </div>
	</div>-->
	<div id="login_box1">
	<div class="topbg"></div>
	<div class="content_box">
		<form id=""  action="" method="post"> 
			<div class="div2 aqua_green"><strong>Confirmation</strong></div>
			<div id="login_error_msg" class="div2 clear mart5 orange"><strong></strong></div>

			  <div class="input-field">
				<label class="required"><strong>You have successfully updated your current location.</strong>
				  <br class="clear" /><br class="clear" />
				<strong class="aqua_green">You current location is</strong> : <hr /> <p><strong><span id="coordinate_span" > </span>.</strong></p></label>
			  </div>
			  <br class="clear" />
			  <div class="div2 mart5"><a class="cmn_register marl"  href="javascript: acknowledgeMessage();">Ok</a></div>
			  <br class="clear" /><br class="clear" />
		</form>
	</div>
	</div>
	<!--update pop up ends -->
</div>

<?php $this->mapLib(null, "true")->setGear(); ?>
<?php
    $userNs=new Zend_Session_Namespace("members");
    $this->userId=$userNs->userId;
?>

<script type="text/javascript">
var user_login_id='<?php echo $this->userId?>';

 function submitenter(myfield,e)
 {
 var keycode;
 if (window.event) keycode = window.event.keyCode;
 else if (e) keycode = e.which;
 else return true;

 if (keycode == 13)
    {
    searchAddress();
    return false;
    }
 else
    return false;
 }




function updateGapperLocation(latLng){
if(user_login_id=="")
    {
        loginPopUp('Please Login to check in.');
        return false;
    }
    $("#dialog-confirm").dialog({
			resizable: false,

			modal: false
			
		});
}
function doUpdate()
{
    var latLng=marker.getPosition();
    saveLocationInDatabase(latLng.lat(),latLng.lng());
}
function doCancel()
{
    $("#dialog-confirm").dialog('close');
}
function acknowledgeMessage()
{
    plotMyJourney();
    $("#dialog-message").dialog('close');
}

function saveLocationInDatabase(lat, lng)
{
    var params="longitude="+lng+"&latitude="+lat+"&address="+$("#address").val();
    
	$("#loading-location").show();
    $.ajax({
           type: "POST",
           url: "/gapper/update-my-location/",
           data: params,
           dataType: "json",
           success: function(json){
				if(json.error==0)
				{
					 $("#loading-location").hide();
					 $("#coordinate_span").html($("#address").val());
					 $("#dialog-message").dialog({
								modal: false,
								resizable: false,
								/*buttons: {
										Ok: function() {
											plotMyJourney();
												$(this).dialog('close');
										}
								}*/
						});
					$("#dialog-confirm").dialog('close')
					//alert("Your location has been updated successfully.");
				}
				else
				{
					$("#loading-location").hide();
					alert("Failed to update your location.");
				}
           },
           error: function (json, status, e){
			   //alert("json===>"+json+" sta="+status+" err="+e)
           }
    });
}

//* Global variable declaration
var geocoder = new google.maps.Geocoder();
var marker=null;
var map =null;
var point="/images/point-blue.png";
var infoWindow = new google.maps.InfoWindow();
var siberia = new google.maps.LatLng(60, 105);
var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
var initialLocation;

function buildMap(latLng)
{
     map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });


  marker = new google.maps.Marker({
    position: latLng,
    title: 'Double Click to set your current location here.',
    map: map,
    icon : point,
    draggable: true
  });
    geocodePosition(latLng);
    addingEventListnerToMaker(marker);
    var content="<div><img src='<?php echo $this->userThumb;?>' /> <?php echo $this->fullName?></div>";
    smartInfo(content, marker,'click');
}

function smartInfo(content, marker, eventName)
{

    google.maps.event.addListener(map, 'click', function(){infoWindow.close();});
    google.maps.event.addListener(marker, eventName, function(e) {



    infoWindow.setContent(content);
    infoWindow.close();

    infoWindow.open(map, marker);

    });

    google.maps.event.addListener(map, 'click', function(e) {

    infoWindow.close();

    });
}
function expandMap()
{
    $("#show-map").hide();
    $("#close-map").show();
    $("#map_canvas").css("height", "500px");
    var latLng=marker.getPosition();
    buildMap(latLng);
}

function shrinkMap()
{
    $("#show-map").show();
    $("#close-map").hide();
    $("#map_canvas").css("height", "243px");
    var latLng=marker.getPosition();
    buildMap(latLng);
}

function removeDestination(id)
{
    if(!confirm("Are you sure you want to delete this location?"))
        return false;
    var param="id="+id;
     $.ajax({
           type: "POST",
           url: "/gapper/remove-destination/",
           data: param,
           dataType: "json",
           success: function(json){
                    if(json.error==0)
                    {
                        plotMyJourney();
                    }
                    else
                    {
                         alert("Error");
                    }

           },
           error: function (json, status, e){
                    //alert(json + status)

                }
    });
}
function plotMyJourney()
{
    var params = "userId=<?php echo $this->userId ?>";
     $.ajax({
           type: "POST",
           url: "/profile/get-my-journey/",
           data : params,
           dataType: "json",
           success: function(json){
                    if(json.error==0)
                    {
                        $("#map_canvas").css("height", "500px");
                        var latLng = new google.maps.LatLng(json.coord[0].lat,json.coord[0].lng);
                        buildMap(latLng);

                        var polyOptions = {
                        strokeColor: '#348698',
                        strokeOpacity: 1.0,
                        strokeWeight: 4
                        }
                        var poly = new google.maps.Polyline(polyOptions);
                        poly.setMap(map);
                        var path = poly.getPath();
                        var latiLongi=null;
                        var image="/images/point-blue.png";
                        for(i=0;i<json.coord.length;i++)
                        {
                            if(image=="/images/point-blue.png")
                            	image="/images/point-green.png";
                            else
                            	image="/images/point-blue.png"
                            latiLongi=new google.maps.LatLng(json.coord[i].lat, json.coord[i].lng);
                            path.push(latiLongi);
                            var marker1 = new google.maps.Marker({
                                position: latiLongi,
                                title: 'Destination #' + path.getLength(),
                                map: map,
                                icon : image
                              });
							  var content="<div><img src='<?php echo $this->userThumb;?>' /> <?php echo $this->fullName?><br>Destination # "+ path.getLength()+" <br>Click <a href='javascript:void(0);' onclick='removeDestination("+json.coord[i].id+")'>here</a> to remove this destination.</div>";
                                smartInfo(content, marker1,'click');
                        }
                    }
                    else
                    {
                         alert("You don't have any coordinate.");
                    }

           },
           error: function (json, status, e){
                    //alert(json + status)

                }
    });

}
function locateMe()
{
           

	  // Try W3C Geolocation method (Preferred)
	  if(navigator.geolocation)
          {
              
	    browserSupportFlag = true;
	    navigator.geolocation.getCurrentPosition(function(position) {
	      initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
	      contentString = "Location found using W3C standard";
	      //map.setCenter(initialLocation);
             
	      buildMap(initialLocation);
	    }, function() {
              
	      handleNoGeolocation(browserSupportFlag);
	    });
	  } 
          else if (google.gears)
          {
         
	    // Try Google Gears Geolocation
	    browserSupportFlag = true;
	    var geo = google.gears.factory.create('beta.geolocation');
	    geo.getCurrentPosition(function(position) {
	      initialLocation = new google.maps.LatLng(position.latitude,position.longitude);
	      contentString = "Location found using Google Gears";
	      //map.setCenter(initialLocation);
	      buildMap(initialLocation);

	    }, function() {
                
	      handleNoGeolocation(browserSupportFlag);
	    });
	  } 
          else
          {
         
	    // Browser doesn't support Geolocation
	    browserSupportFlag = false;
	    handleNoGeolocation(browserSupportFlag);
	  }
         
}

function handleNoGeolocation(errorFlag) {

	  if (errorFlag == true) {
	    initialLocation = newyork;
	    contentString = "Error: The Geolocation service failed.";
	  } else {
	    initialLocation = siberia;
	    contentString = "Error: Your browser doesn't support geolocation. Are you in Siberia?";
	  }
            contentString="We are unable to locate you on map. You are being located to the London, England";
            alert(contentString);
          
            var latLng = new google.maps.LatLng("51.5001524", "-0.1262362");
            buildMap(latLng);
           // buildMap(latLng);
          ///alert(initialLocation);
         // map.setCenter(initialLocation);

          

	}

function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
        
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}


function updateMarkerAddress(str) {

  document.getElementById('address').value = str;
}

function searchAddress()
{
    var query = document.getElementById('address').value;
    var request={ 'address': query };

    geocoder.geocode(request, locateDestination);
   
}

function locateDestination(results, status) {
     if (status == google.maps.GeocoderStatus.OK){

     //buildMap(results[0].geometry.location);
     
     shrinkMap()
     resetMap();
    marker = new google.maps.Marker({
    position: results[0].geometry.location,
    title: 'Double Click here to set your current location.',
    map: map,
    draggable: true
  });
 
    //map.panTo(marker.getPosition());
    buildMap(results[0].geometry.location);
   // addingEventListnerToMaker(marker);
    //alert(status);
    //updateMarkerAddress(results[0].formatted_address);;
     //alert(results[0].formatted_address);
     }else{
         alert("Unable to locate. Please try some other keyword.");
     }
     
}

function resetMap() {

  if (marker != null) {
    marker.setMap(null);
    marker= null;
  }


}

function initialize()
{
	var myLatitude='<?php echo $this->myLatitude?>';
	var myLongitude='<?php echo $this->myLongitude?>';
	if(myLatitude=="" || myLongitude=="")
	{
		locateMe();
		return false;
	}

  	var latLng = new google.maps.LatLng(myLatitude, myLongitude);
    buildMap(latLng);
    geocodePosition(latLng);
    addingEventListnerToMaker(marker);
}

function addingEventListnerToMaker(marker)
{
     // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {

    updateMarkerAddress('Wait...');


  });

  google.maps.event.addListener(marker, 'dragend', function() {

    geocodePosition(marker.getPosition());

  });

  google.maps.event.addListener(marker, 'dblclick', function() {
    updateGapperLocation(marker.getPosition());
  });
  
}
// Onload handler to fire off the app.
//
google.maps.event.addDomListener(window, 'load', locateMe);

</script>
